

/*
DROP TABLE IF EXISTS tim7020.cip_codes;
CREATE TEMPORARY TABLE tim7020.cip_codes AS 
	SELECT * FROM tim7020.institution_xref_cip_code;

INSERT IGNORE INTO tim7020.cip_codes (Codevalue, valueLabel, valueOrder)
SELECT * FROM institution_xref_cip_code_1st_program
UNION SELECT * FROM institution_xref_cip_code_2nd_program
UNION SELECT * FROM institution_xref_cip_code_3rd_program
UNION SELECT * FROM institution_xref_cip_code_4th_program
UNION SELECT * FROM institution_xref_cip_code_5th_program
UNION SELECT * FROM institution_xref_cip_code_6th_program;
*/
DROP TABLE IF EXISTS temp_alter;
CREATE TABLE temp_alter AS
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code';

INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_1st_program';

INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_2nd_program';

INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_3rd_program';


INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_4th_program';    


INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_5th_program';


INSERT INTO temp_alter (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME)
SELECT k.TABLE_SCHEMA, c.TABLE_NAME, k.COLUMN_NAME, c.CONSTRAINT_NAME
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as c
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE as k 
		ON k.TABLE_SCHEMA = 'tim7020-2' 
			AND k.TABLE_NAME = c.TABLE_NAME 
            AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
	WHERE c.REFERENCED_TABLE_NAME = 'institution_xref_cip_code_6th_program';    
    
SELECT * FROM temp_alter;

/*
SET @drop_command := CONCAT('ALTER TABLE ', @tname, ' DROP FOREIGN KEY ', @cname);
PREPARE stmt FROM @drop_command;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @add_command := CONCAT('ALTER TABLE ', @tname, ' ADD FOREIGN KEY '
*/