ALTER TABLE institution_hr_occupation 
    ADD COLUMN occupation_faculty_tenure_status MEDIUMINT COMMENT "EAPCAT|Occupation and faculty/tenure status",
    ADD COLUMN occupation SMALLINT COMMENT "OCCUPCAT|Occupation",
    ADD COLUMN faculty_tenure_status SMALLINT COMMENT "FACSTAT|Faculty and tenure status",
  ADD COLUMN total_employees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPTOT|Total employees",
    ADD COLUMN total_employees MEDIUMINT COMMENT "EAPTOT|Total employees",
  ADD COLUMN inst_employees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPTYP|Institution employees (excluding medical school)",
    ADD COLUMN inst_employees MEDIUMINT COMMENT "EAPTYP|Institution employees (excluding medical school)",
  ADD COLUMN med_school_employees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPMED|Medical school employees",
    ADD COLUMN med_school_employees FLOAT COMMENT "EAPMED|Medical school employees",
  ADD COLUMN full_time_employees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPFT|Full-time employees",
    ADD COLUMN full_time_employees MEDIUMINT COMMENT "EAPFT|Full-time employees",
  ADD COLUMN full_time_employees_inst_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPFTTYP|Full-time employees (excluding medical schools)",
    ADD COLUMN full_time_employees_inst MEDIUMINT COMMENT "EAPFTTYP|Full-time employees (excluding medical schools)",
  ADD COLUMN full_time_employees_med_school_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPFTMED|Full-time employees (medical school)",
    ADD COLUMN full_time_employees_med_school FLOAT COMMENT "EAPFTMED|Full-time employees (medical school)",
  ADD COLUMN part_time_employees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPPT|Part-time employees",
    ADD COLUMN part_time_employees MEDIUMINT COMMENT "EAPPT|Part-time employees",
  ADD COLUMN part_time_employees_inst_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPPTTYP|Part-time employees (excluding medical schools)",
    ADD COLUMN part_time_employees_inst MEDIUMINT COMMENT "EAPPTTYP|Part-time employees (excluding medical schools)",
  ADD COLUMN part_time_employees_med_school_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EAPPTMED|Part-time employees (medical school)",
    ADD COLUMN part_time_employees_med_school FLOAT COMMENT "EAPPTMED|Part-time employees (medical school)";