ALTER TABLE institution_comp_award_race_gender_age 
    ADD COLUMN award_level_cd TINYINT COMMENT "AWLEVELC|Award Level code",
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLT|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "CSTOTLT|Grand total",
  ADD COLUMN grand_total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLM|Grand total men",
    ADD COLUMN grand_total_men MEDIUMINT COMMENT "CSTOTLM|Grand total men",
  ADD COLUMN grand_total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLW|Grand total women",
    ADD COLUMN grand_total_women MEDIUMINT COMMENT "CSTOTLW|Grand total women",
  ADD COLUMN american_indian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSAIANT|American Indian or Alaska Native total",
    ADD COLUMN american_indian_total MEDIUMINT COMMENT "CSAIANT|American Indian or Alaska Native total",
  ADD COLUMN asian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSASIAT|Asian total",
    ADD COLUMN asian_total MEDIUMINT COMMENT "CSASIAT|Asian total",
  ADD COLUMN black_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSBKAAT|Black or African American total",
    ADD COLUMN black_total MEDIUMINT COMMENT "CSBKAAT|Black or African American total",
  ADD COLUMN hispanic_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSHISPT|Hispanic or Latino total",
    ADD COLUMN hispanic_total MEDIUMINT COMMENT "CSHISPT|Hispanic or Latino total",
  ADD COLUMN hawaiian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNHPIT|Native Hawaiian or Other Pacific Islander total",
    ADD COLUMN hawaiian_total MEDIUMINT COMMENT "CSNHPIT|Native Hawaiian or Other Pacific Islander total",
  ADD COLUMN white_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSWHITT|White total",
    ADD COLUMN white_total MEDIUMINT COMMENT "CSWHITT|White total",
  ADD COLUMN two_or_more_races_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS2MORT|Two or more races total",
    ADD COLUMN two_or_more_races_total MEDIUMINT COMMENT "CS2MORT|Two or more races total",
  ADD COLUMN race_ethnicity_unknown_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUNKNT|Race/ethnicity unknown total",
    ADD COLUMN race_ethnicity_unknown_total MEDIUMINT COMMENT "CSUNKNT|Race/ethnicity unknown total",
  ADD COLUMN nonresident_alien_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNRALT|Nonresident alien total",
    ADD COLUMN nonresident_alien_total MEDIUMINT COMMENT "CSNRALT|Nonresident alien total",
  ADD COLUMN ages_under_18_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUND18|Ages, under 18",
    ADD COLUMN ages_under_18 MEDIUMINT COMMENT "CSUND18|Ages, under 18",
  ADD COLUMN ages_18_24_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS18_24|Ages, 18-24",
    ADD COLUMN ages_18_24 MEDIUMINT COMMENT "CS18_24|Ages, 18-24",
  ADD COLUMN ages_25_39_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS25_39|Ages, 25-39",
    ADD COLUMN ages_25_39 MEDIUMINT COMMENT "CS25_39|Ages, 25-39",
  ADD COLUMN ages_40_and_above_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSABV40|Ages, 40 and above",
    ADD COLUMN ages_40_and_above MEDIUMINT COMMENT "CSABV40|Ages, 40 and above",
  ADD COLUMN age_unknown_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUNKN|Age unknown",
    ADD COLUMN age_unknown MEDIUMINT COMMENT "CSUNKN|Age unknown";