ALTER TABLE institution_outcome_measures 
    ADD COLUMN cohort_cat TINYINT COMMENT "OMCHRT|Cohort category",
  ADD COLUMN cohort_2013_14_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMRCHRT|2013-14 cohort",
    ADD COLUMN cohort_2013_14 MEDIUMINT COMMENT "OMRCHRT|2013-14 cohort",
  ADD COLUMN exclusions_2013_14_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMEXCLS|Exclusions to 2013-14 cohort",
    ADD COLUMN exclusions_2013_14 MEDIUMINT COMMENT "OMEXCLS|Exclusions to 2013-14 cohort",
  ADD COLUMN adjusted_2013_14_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMACHRT|Adjusted 2013-14 cohort",
    ADD COLUMN adjusted_2013_14 MEDIUMINT COMMENT "OMACHRT|Adjusted 2013-14 cohort",
  ADD COLUMN cert_4yr_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMCERT4|Number of adjusted cohort receiving a certificate at 4 years (August 31, 2017)",
    ADD COLUMN cert_4yr_2017 MEDIUMINT COMMENT "OMCERT4|Number of adjusted cohort receiving a certificate at 4 years (August 31, 2017)",
  ADD COLUMN assoc_4yr_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMASSC4|Number of adjusted cohort receiving an Associate's degree at 4 years (August 31, 2017)",
    ADD COLUMN assoc_4yr_2017 MEDIUMINT COMMENT "OMASSC4|Number of adjusted cohort receiving an Associate's degree at 4 years (August 31, 2017)",
  ADD COLUMN bach_4yr_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMBACH4|Number of adjusted cohort receiving a Bachelor's degree at 4 years (August 31, 2017)",
    ADD COLUMN bach_4yr_2017 FLOAT COMMENT "OMBACH4|Number of adjusted cohort receiving a Bachelor's degree at 4 years (August 31, 2017)",
  ADD COLUMN award_4yr_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDN4|Number of adjusted cohort receiving an award at 4 years (August 31, 2017)",
    ADD COLUMN award_4yr_2017 MEDIUMINT COMMENT "OMAWDN4|Number of adjusted cohort receiving an award at 4 years (August 31, 2017)",
  ADD COLUMN percent_award_4yr_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDP4|Percent of adjusted cohort receiving an award at 4 years (August 31, 2017)",
    ADD COLUMN percent_award_4yr_2017 SMALLINT COMMENT "OMAWDP4|Percent of adjusted cohort receiving an award at 4 years (August 31, 2017)",
  ADD COLUMN cert_6yr_2019_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMCERT6|Number of adjusted cohort receiving a certificate at 6 years (August 31, 2019)",
    ADD COLUMN cert_6yr_2019 MEDIUMINT COMMENT "OMCERT6|Number of adjusted cohort receiving a certificate at 6 years (August 31, 2019)",
  ADD COLUMN assoc_6yr_2019_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMASSC6|Number of adjusted cohort receiving an Associate's degree at 6 years (August 31, 2019)",
    ADD COLUMN assoc_6yr_2019 MEDIUMINT COMMENT "OMASSC6|Number of adjusted cohort receiving an Associate's degree at 6 years (August 31, 2019)",
  ADD COLUMN bach_6yr_2019_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMBACH6|Number of adjusted cohort receiving a Bachelor's degree at 6 years (August 31, 2019)",
    ADD COLUMN bach_6yr_2019 FLOAT COMMENT "OMBACH6|Number of adjusted cohort receiving a Bachelor's degree at 6 years (August 31, 2019)",
  ADD COLUMN award_6yr_2019_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDN6|Number of adjusted cohort receiving an award at 6 years (August 31, 2019)",
    ADD COLUMN award_6yr_2019 MEDIUMINT COMMENT "OMAWDN6|Number of adjusted cohort receiving an award at 6 years (August 31, 2019)",
  ADD COLUMN percent_award_6yr_2019_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDP6|Percent of adjusted cohort receiving an award at 6 years (August 31, 2019)",
    ADD COLUMN percent_award_6yr_2019 SMALLINT COMMENT "OMAWDP6|Percent of adjusted cohort receiving an award at 6 years (August 31, 2019)",
  ADD COLUMN cert_8yr_2021_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMCERT8|Number of adjusted cohort receiving a certificate at 8 years (August 31, 2021)",
    ADD COLUMN cert_8yr_2021 MEDIUMINT COMMENT "OMCERT8|Number of adjusted cohort receiving a certificate at 8 years (August 31, 2021)",
  ADD COLUMN assoc_8yr_2021_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMASSC8|Number of adjusted cohort receiving an Associate's degree at 8 years (August 31, 2021)",
    ADD COLUMN assoc_8yr_2021 MEDIUMINT COMMENT "OMASSC8|Number of adjusted cohort receiving an Associate's degree at 8 years (August 31, 2021)",
  ADD COLUMN bach_8yr_2021_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMBACH8|Number of adjusted cohort receiving a Bachelor's degree at 8 years (August 31, 2021)",
    ADD COLUMN bach_8yr_2021 FLOAT COMMENT "OMBACH8|Number of adjusted cohort receiving a Bachelor's degree at 8 years (August 31, 2021)",
  ADD COLUMN award_8yr_2021_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDN8|Number of adjusted cohort receiving an award at 8 years (August 31, 2021)",
    ADD COLUMN award_8yr_2021 MEDIUMINT COMMENT "OMAWDN8|Number of adjusted cohort receiving an award at 8 years (August 31, 2021)",
  ADD COLUMN enrolled_8yr_2021_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRYI|Number of adjusted cohort still enrolled at your institution at 8 years (August 31, 2021)",
    ADD COLUMN enrolled_8yr_2021 MEDIUMINT COMMENT "OMENRYI|Number of adjusted cohort still enrolled at your institution at 8 years (August 31, 2021)",
  ADD COLUMN num_adj_cohort_enrolled_subseq_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRAI|Number of adjusted cohort who enrolled subsequently at another institution at 8 years (August 31, 2021)",
    ADD COLUMN num_adj_cohort_enrolled_subseq_8yrs MEDIUMINT COMMENT "OMENRAI|Number of adjusted cohort who enrolled subsequently at another institution at 8 years (August 31, 2021)",
  ADD COLUMN num_adj_cohort_enrollment_status_unknown_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRUN|Number of adjusted cohort whose subsequent enrollment status is unknown at 8 years (August 31, 2021)",
    ADD COLUMN num_adj_cohort_enrollment_status_unknown_8yrs MEDIUMINT COMMENT "OMENRUN|Number of adjusted cohort whose subsequent enrollment status is unknown at 8 years (August 31, 2021)",
  ADD COLUMN num_adj_cohort_no_award_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMNOAWD|Number of adjusted cohort who did not receive an award from your institution at 8 years (August 31, 2021)",
    ADD COLUMN num_adj_cohort_no_award_8yrs MEDIUMINT COMMENT "OMNOAWD|Number of adjusted cohort who did not receive an award from your institution at 8 years (August 31, 2021)",
  ADD COLUMN pct_adj_cohort_award_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMAWDP8|Percent of adjusted cohort receiving an award at 8 years (August 31, 2021)",
    ADD COLUMN pct_adj_cohort_award_8yrs SMALLINT COMMENT "OMAWDP8|Percent of adjusted cohort receiving an award at 8 years (August 31, 2021)",
  ADD COLUMN pct_adj_cohort_enrolled_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRTP|Percent of adjusted cohort still or subsequently enrolled at 8 years (August 31, 2021)",
    ADD COLUMN pct_adj_cohort_enrolled_8yrs SMALLINT COMMENT "OMENRTP|Percent of adjusted cohort still or subsequently enrolled at 8 years (August 31, 2021)",
  ADD COLUMN pct_adj_cohort_enrolled_inst_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRYP|Percent of adjusted cohort still enrolled at your institution at 8 years (August 31, 2021)",
    ADD COLUMN pct_adj_cohort_enrolled_inst_8yrs SMALLINT COMMENT "OMENRYP|Percent of adjusted cohort still enrolled at your institution at 8 years (August 31, 2021)",
  ADD COLUMN pct_adj_cohort_enrolled_subseq_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRAP|Percent of adjusted cohort  enrolled subsequently at another institution at 8 years (August 31, 2021)",
    ADD COLUMN pct_adj_cohort_enrolled_subseq_8yrs SMALLINT COMMENT "OMENRAP|Percent of adjusted cohort  enrolled subsequently at another institution at 8 years (August 31, 2021)",
  ADD COLUMN pct_adj_cohort_enrollment_status_unknown_8yrs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "OMENRUP|Percent of adjusted cohort  enrollment status unknown at 8 years (August 31, 2021)",
    ADD COLUMN pct_adj_cohort_enrollment_status_unknown_8yrs SMALLINT COMMENT "OMENRUP|Percent of adjusted cohort  enrollment status unknown at 8 years (August 31, 2021)";