ALTER TABLE institution_comp_dist 
    ADD COLUMN cipcode FLOAT COMMENT "CIPCODE|CIPCODE - 2020 Classification",
    ADD COLUMN num_programs_all_award_levels MEDIUMINT COMMENT "PTOTAL|All award levels - number of programs offered",
    ADD COLUMN num_programs_distance_education_all_award_levels MEDIUMINT COMMENT "PTOTALDE|All award levels - number of programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN num_programs_distance_education_some_award_levels MEDIUMINT COMMENT "PTOTALDES|All award levels - number of programs with some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_associates MEDIUMINT COMMENT "PASSOC|Associate's degree - programs offered",
    ADD COLUMN programs_distance_education_associates MEDIUMINT COMMENT "PASSOCDE|Associate's degree - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_distance_education_some_associates MEDIUMINT COMMENT "PASSOCDES|Associate's degree - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_bachelors MEDIUMINT COMMENT "PBACHL|Bachelor's degree - programs offered",
    ADD COLUMN programs_distance_education_bachelors MEDIUMINT COMMENT "PBACHLDE|Bachelor's degree - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_distance_education_some_bachelors MEDIUMINT COMMENT "PBACHLDES|Bachelor's degree - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_masters MEDIUMINT COMMENT "PMASTR|Master's degree - programs offered",
    ADD COLUMN programs_distance_education_masters MEDIUMINT COMMENT "PMASTRDE|Master's degree - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_distance_education_some_masters MEDIUMINT COMMENT "PMASTRDES|Master's degree - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_doctors_research MEDIUMINT COMMENT "PDOCRS|Doctor's degree-research/scholarship - programs offered",
    ADD COLUMN programs_distance_education_doctors_research MEDIUMINT COMMENT "PDOCRSDE|Doctor's degree-research/scholarship - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_distance_education_some_doctors_research MEDIUMINT COMMENT "PDOCRSDES|Doctor's degree-research/scholarship - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_doctors_professional MEDIUMINT COMMENT "PDOCPP|Doctor's degree-professional practice - programs offered",
    ADD COLUMN programs_distance_education_doctors_professional MEDIUMINT COMMENT "PDOCPPDE|Doctor's degree-professional practice - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN programs_distance_education_some_doctors_professional MEDIUMINT COMMENT "PDOCPPDES|Doctor's degree-professional practice - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN doc_degree_other_programs MEDIUMINT COMMENT "PDOCOT|Doctor's degree-other - programs offered",
    ADD COLUMN doc_degree_other_distance_all MEDIUMINT COMMENT "PDOCOTDE|Doctor's degree-other - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN doc_degree_other_distance_some MEDIUMINT COMMENT "PDOCOTDES|Doctor's degree-other - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_less_than_12_weeks_programs MEDIUMINT COMMENT "PCERT1A|Certificates of less than 12 weeks - programs offered",
    ADD COLUMN cert_less_than_12_weeks_distance_all MEDIUMINT COMMENT "PCERT1ADE|Certificates of less than 12 weeks - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_less_than_12_weeks_distance_some MEDIUMINT COMMENT "PCERT1ADES|Certificates of less than 12 weeks - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_12_weeks_to_1_year_programs MEDIUMINT COMMENT "PCERT1B|Certificates of at least 12 weeks, but less than 1 year - programs offered",
    ADD COLUMN cert_12_weeks_to_1_year_distance_all MEDIUMINT COMMENT "PCERT1BDE|Certificates of at least 12 weeks, but less than 1 year - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_12_weeks_to_1_year_distance_some MEDIUMINT COMMENT "PCERT1BDES|Certificates of at least 12 weeks, but less than 1 year - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_1_year_to_2_years_programs MEDIUMINT COMMENT "PCERT2|Certificates of 1 year, but less than 2 years - programs offered",
    ADD COLUMN cert_1_year_to_2_years_distance_all MEDIUMINT COMMENT "PCERT2DE|Certificates of 1 year, but less than 2 years - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_1_year_to_2_years_distance_some MEDIUMINT COMMENT "PCERT2DES|Certificates of 1 year, but less than 2 years - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_2_years_to_4_years_programs MEDIUMINT COMMENT "PCERT4|Certificates of 2 years, but less than 4 years - programs offered",
    ADD COLUMN cert_2_years_to_4_years_distance_all MEDIUMINT COMMENT "PCERT4DE|Certificates of 2 years, but less than 4 years - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN cert_2_years_to_4_years_distance_some MEDIUMINT COMMENT "PCERT4DES|Certificates of 2 years, but less than 4 years - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN postbac_cert_programs MEDIUMINT COMMENT "PPBACC|Postbaccalaureate certificate - programs offered",
    ADD COLUMN postbac_cert_distance_all MEDIUMINT COMMENT "PPBACCDE|Postbaccalaureate certificate - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN postbac_cert_distance_some MEDIUMINT COMMENT "PPBACCDES|Postbaccalaureate certificate - some programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN postmasters_cert_programs MEDIUMINT COMMENT "PPMAST|Post-master's certificate - programs offered",
    ADD COLUMN postmasters_cert_distance_all MEDIUMINT COMMENT "PPMASTDE|Post-master's certificate - all programs in a CIP code can be completed entirely via distance education",
    ADD COLUMN post_masters_cert_complete_distance MEDIUMINT COMMENT "PPMASTDES|Post-master's certificate - some programs in a CIP code can be completed entirely via distance education";