ALTER TABLE institution_hr_salaries_gender_rank 
    ADD COLUMN academic_rank SMALLINT COMMENT "ARANK|Academic rank",
  ADD COLUMN inst_staff_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAINSTT|Instructional staff - total",
    ADD COLUMN inst_staff_total MEDIUMINT COMMENT "SAINSTT|Instructional staff - total",
  ADD COLUMN inst_staff_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAINSTM|Instructional staff - men",
    ADD COLUMN inst_staff_men MEDIUMINT COMMENT "SAINSTM|Instructional staff - men",
  ADD COLUMN inst_staff_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAINSTW|Instructional staff - women",
    ADD COLUMN inst_staff_women MEDIUMINT COMMENT "SAINSTW|Instructional staff - women",
  ADD COLUMN inst_staff_less_9mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA_9MCT|Instructional staff on less than 9-month contract-total",
    ADD COLUMN inst_staff_less_9mo_total MEDIUMINT COMMENT "SA_9MCT|Instructional staff on less than 9-month contract-total",
  ADD COLUMN inst_staff_less_9mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA_9MCM|Instructional staff on less than 9-month contract-men",
    ADD COLUMN inst_staff_less_9mo_men MEDIUMINT COMMENT "SA_9MCM|Instructional staff on less than 9-month contract-men",
  ADD COLUMN inst_staff_less_9mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA_9MCW|Instructional staff on less than 9-month contract-women",
    ADD COLUMN inst_staff_less_9mo_women MEDIUMINT COMMENT "SA_9MCW|Instructional staff on less than 9-month contract-women",
  ADD COLUMN inst_staff_9_12mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATOTLT|Instructional staff on 9, 10, 11 or 12 month contract-total",
    ADD COLUMN inst_staff_9_12mo_total MEDIUMINT COMMENT "SATOTLT|Instructional staff on 9, 10, 11 or 12 month contract-total",
  ADD COLUMN inst_staff_9_12mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATOTLM|Instructional staff on 9, 10, 11 or 12 month contract-men",
    ADD COLUMN inst_staff_9_12mo_men MEDIUMINT COMMENT "SATOTLM|Instructional staff on 9, 10, 11 or 12 month contract-men",
  ADD COLUMN inst_staff_9_12mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATOTLW|Instructional staff on 9, 10, 11 or 12 month contract-women",
    ADD COLUMN inst_staff_9_12mo_women MEDIUMINT COMMENT "SATOTLW|Instructional staff on 9, 10, 11 or 12 month contract-women",
  ADD COLUMN inst_staff_9mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MCT|Instructional staff on 9-month contract-total",
    ADD COLUMN inst_staff_9mo_total MEDIUMINT COMMENT "SA09MCT|Instructional staff on 9-month contract-total",
  ADD COLUMN inst_staff_9mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MCM|Instructional staff on 9-month contract-men",
    ADD COLUMN inst_staff_9mo_men MEDIUMINT COMMENT "SA09MCM|Instructional staff on 9-month contract-men",
  ADD COLUMN inst_staff_9mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MCW|Instructional staff on 9-month contract-women",
    ADD COLUMN inst_staff_9mo_women MEDIUMINT COMMENT "SA09MCW|Instructional staff on 9-month contract-women",
  ADD COLUMN inst_staff_10mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MCT|Instructional staff on 10-month contract-total",
    ADD COLUMN inst_staff_10mo_total MEDIUMINT COMMENT "SA10MCT|Instructional staff on 10-month contract-total",
  ADD COLUMN inst_staff_10mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MCM|Instructional staff on 10-month contract-men",
    ADD COLUMN inst_staff_10mo_men MEDIUMINT COMMENT "SA10MCM|Instructional staff on 10-month contract-men",
  ADD COLUMN inst_staff_10mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MCW|Instructional staff on 10-month contract-women",
    ADD COLUMN inst_staff_10mo_women MEDIUMINT COMMENT "SA10MCW|Instructional staff on 10-month contract-women",
  ADD COLUMN inst_staff_11mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MCT|Instructional staff on 11-month contract-total",
    ADD COLUMN inst_staff_11mo_total MEDIUMINT COMMENT "SA11MCT|Instructional staff on 11-month contract-total",
  ADD COLUMN inst_staff_11mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MCM|Instructional staff on 11-month contract-men",
    ADD COLUMN inst_staff_11mo_men MEDIUMINT COMMENT "SA11MCM|Instructional staff on 11-month contract-men",
  ADD COLUMN inst_staff_11mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MCW|Instructional staff on 11-month contract-women",
    ADD COLUMN inst_staff_11mo_women MEDIUMINT COMMENT "SA11MCW|Instructional staff on 11-month contract-women",
  ADD COLUMN instructional_staff_12mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MCT|Instructional staff on 12-month contract total",
    ADD COLUMN instructional_staff_12mo_total MEDIUMINT COMMENT "SA12MCT|Instructional staff on 12-month contract total",
  ADD COLUMN instructional_staff_12mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MCM|Instructional staff on 12-month contract men",
    ADD COLUMN instructional_staff_12mo_men MEDIUMINT COMMENT "SA12MCM|Instructional staff on 12-month contract men",
  ADD COLUMN instructional_staff_12mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MCW|Instructional staff on 12--month contract women",
    ADD COLUMN instructional_staff_12mo_women MEDIUMINT COMMENT "SA12MCW|Instructional staff on 12--month contract women",
  ADD COLUMN salary_outlays_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAOUTLT|Salary outlays - total",
    ADD COLUMN salary_outlays_total BIGINT COMMENT "SAOUTLT|Salary outlays - total",
  ADD COLUMN salary_outlays_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAOUTLM|Salary outlays - men",
    ADD COLUMN salary_outlays_men BIGINT COMMENT "SAOUTLM|Salary outlays - men",
  ADD COLUMN salary_outlays_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAOUTLW|Salary outlays - women",
    ADD COLUMN salary_outlays_women BIGINT COMMENT "SAOUTLW|Salary outlays - women",
  ADD COLUMN salary_outlays_9mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MOT|Salary outlays for instructional staff on 9-month contract-total",
    ADD COLUMN salary_outlays_9mo_total BIGINT COMMENT "SA09MOT|Salary outlays for instructional staff on 9-month contract-total",
  ADD COLUMN salary_outlays_9mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MOM|Salary outlays for instructional staff on 9-month contract-men",
    ADD COLUMN salary_outlays_9mo_men BIGINT COMMENT "SA09MOM|Salary outlays for instructional staff on 9-month contract-men",
  ADD COLUMN salary_outlays_9mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MOW|Salary outlays for instructional staff on 9-month contract-women",
    ADD COLUMN salary_outlays_9mo_women BIGINT COMMENT "SA09MOW|Salary outlays for instructional staff on 9-month contract-women",
  ADD COLUMN salary_outlays_10mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MOT|Salary outlays for instructional staff on 10-month contract-total",
    ADD COLUMN salary_outlays_10mo_total BIGINT COMMENT "SA10MOT|Salary outlays for instructional staff on 10-month contract-total",
  ADD COLUMN salary_outlays_10mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MOM|Salary outlays for instructional staff on 10-month contract-men",
    ADD COLUMN salary_outlays_10mo_men BIGINT COMMENT "SA10MOM|Salary outlays for instructional staff on 10-month contract-men",
  ADD COLUMN salary_outlays_10mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MOW|Salary outlays for instructional staff on 10-month contract-women",
    ADD COLUMN salary_outlays_10mo_women BIGINT COMMENT "SA10MOW|Salary outlays for instructional staff on 10-month contract-women",
  ADD COLUMN salary_outlays_11mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MOT|Salary outlays for instructional staff on 11-month contract-total",
    ADD COLUMN salary_outlays_11mo_total BIGINT COMMENT "SA11MOT|Salary outlays for instructional staff on 11-month contract-total",
  ADD COLUMN salary_outlays_11mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MOM|Salary outlays for instructional staff on 11-month contract-men",
    ADD COLUMN salary_outlays_11mo_men BIGINT COMMENT "SA11MOM|Salary outlays for instructional staff on 11-month contract-men",
  ADD COLUMN salary_outlays_11mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MOW|Salary outlays for instructional staff on 11-month contract-women",
    ADD COLUMN salary_outlays_11mo_women BIGINT COMMENT "SA11MOW|Salary outlays for instructional staff on 11-month contract-women",
  ADD COLUMN salary_outlays_12mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MOT|Salary outlays for instructional staff on 12-month contract-total",
    ADD COLUMN salary_outlays_12mo_total BIGINT COMMENT "SA12MOT|Salary outlays for instructional staff on 12-month contract-total",
  ADD COLUMN salary_outlays_12mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MOM|Salary outlays for instructional staff on 12-month contract-men",
    ADD COLUMN salary_outlays_12mo_men BIGINT COMMENT "SA12MOM|Salary outlays for instructional staff on 12-month contract-men",
  ADD COLUMN salary_outlays_12mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MOW|Salary outlays for instructional staff on 12-month contract-women",
    ADD COLUMN salary_outlays_12mo_women BIGINT COMMENT "SA12MOW|Salary outlays for instructional staff on 12-month contract-women",
  ADD COLUMN salary_outlays_9mo_eq_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9OT|Salary outlays for instructional staff equated to a 9-month contract-total",
    ADD COLUMN salary_outlays_9mo_eq_total BIGINT COMMENT "SAEQ9OT|Salary outlays for instructional staff equated to a 9-month contract-total",
  ADD COLUMN salary_outlays_9mo_eq_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9OM|Salary outlays for instructional staff equated to a 9-month contract-men",
    ADD COLUMN salary_outlays_9mo_eq_men BIGINT COMMENT "SAEQ9OM|Salary outlays for instructional staff equated to a 9-month contract-men",
  ADD COLUMN salary_outlays_9mo_eq_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9OW|Salary outlays for instructional staff equated to a 9-month contract-women",
    ADD COLUMN salary_outlays_9mo_eq_women BIGINT COMMENT "SAEQ9OW|Salary outlays for instructional staff equated to a 9-month contract-women",
  ADD COLUMN avg_salary_instr_staff_eq_9mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9AT|Average salary for instructional staff equated to a 9-month contract-total",
    ADD COLUMN avg_salary_instr_staff_eq_9mo_total MEDIUMINT COMMENT "SAEQ9AT|Average salary for instructional staff equated to a 9-month contract-total",
  ADD COLUMN avg_salary_instr_staff_eq_9mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9AM|Average salary for instructional staff equated to a 9-month contract-men",
    ADD COLUMN avg_salary_instr_staff_eq_9mo_men FLOAT COMMENT "SAEQ9AM|Average salary for instructional staff equated to a 9-month contract-men",
  ADD COLUMN avg_salary_instr_staff_eq_9mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SAEQ9AW|Average salary for instructional staff equated to a 9-month contract-women",
    ADD COLUMN avg_salary_instr_staff_eq_9mo_women FLOAT COMMENT "SAEQ9AW|Average salary for instructional staff equated to a 9-month contract-women",
  ADD COLUMN avg_salary_instr_staff_9mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MAT|Average salary for instructional staff on 9-month contract-total",
    ADD COLUMN avg_salary_instr_staff_9mo_total FLOAT COMMENT "SA09MAT|Average salary for instructional staff on 9-month contract-total",
  ADD COLUMN avg_salary_instr_staff_9mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MAM|Average salary for instructional staff on 9-month contract-men",
    ADD COLUMN avg_salary_instr_staff_9mo_men FLOAT COMMENT "SA09MAM|Average salary for instructional staff on 9-month contract-men",
  ADD COLUMN avg_salary_instr_staff_9mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA09MAW|Average salary for instructional staff on 9-month contract-women",
    ADD COLUMN avg_salary_instr_staff_9mo_women FLOAT COMMENT "SA09MAW|Average salary for instructional staff on 9-month contract-women",
  ADD COLUMN avg_salary_instr_staff_10mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MAT|Average salary for instructional staff on 10-month contract-total",
    ADD COLUMN avg_salary_instr_staff_10mo_total FLOAT COMMENT "SA10MAT|Average salary for instructional staff on 10-month contract-total",
  ADD COLUMN avg_salary_instr_staff_10mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MAM|Average salary for instructional staff on 10-month contract-men",
    ADD COLUMN avg_salary_instr_staff_10mo_men FLOAT COMMENT "SA10MAM|Average salary for instructional staff on 10-month contract-men",
  ADD COLUMN avg_salary_instr_staff_10mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA10MAW|Average salary for instructional staff on 10-month contract-women",
    ADD COLUMN avg_salary_instr_staff_10mo_women FLOAT COMMENT "SA10MAW|Average salary for instructional staff on 10-month contract-women",
  ADD COLUMN avg_salary_instr_staff_11mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MAT|Average salary for instructional staff on 11-month contract-total",
    ADD COLUMN avg_salary_instr_staff_11mo_total FLOAT COMMENT "SA11MAT|Average salary for instructional staff on 11-month contract-total",
  ADD COLUMN avg_salary_instr_staff_11mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MAM|Average salary for instructional staff on 11-month contract-men",
    ADD COLUMN avg_salary_instr_staff_11mo_men FLOAT COMMENT "SA11MAM|Average salary for instructional staff on 11-month contract-men",
  ADD COLUMN avg_salary_instr_staff_11mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA11MAW|Average salary for instructional staff on 11-month contract-women",
    ADD COLUMN avg_salary_instr_staff_11mo_women FLOAT COMMENT "SA11MAW|Average salary for instructional staff on 11-month contract-women",
  ADD COLUMN avg_salary_instr_staff_12mo_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MAT|Average salary for instructional staff on 12-month contract-total",
    ADD COLUMN avg_salary_instr_staff_12mo_total FLOAT COMMENT "SA12MAT|Average salary for instructional staff on 12-month contract-total",
  ADD COLUMN avg_salary_instr_staff_12mo_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MAM|Average salary for instructional staff on 12-month contract-men",
    ADD COLUMN avg_salary_instr_staff_12mo_men FLOAT COMMENT "SA12MAM|Average salary for instructional staff on 12-month contract-men",
  ADD COLUMN avg_salary_instr_staff_12mo_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SA12MAW|Average salary for instructional staff on 12-month contract-women",
    ADD COLUMN avg_salary_instr_staff_12mo_women FLOAT COMMENT "SA12MAW|Average salary for instructional staff on 12-month contract-women";