
        ALTER TABLE institution_ic_campuses 
            ADD FOREIGN KEY (inst_id) REFERENCES institution(inst_id), 
            ADD FOREIGN KEY (state) REFERENCES institution_xref_state(Codevalue), 
            ADD CHECK (fips_st_code IN ()), 
            ADD CHECK (bea_regions IN ()), 
            ADD CHECK (ope_eligibility_code IN ()), 
            ADD CHECK (sector IN ()), 
            ADD CHECK (level IN ()), 
            ADD CHECK (control IN ()), 
            ADD CHECK (highest_level_offering IN ()), 
            ADD CHECK (undergrad_offering IN ()), 
            ADD CHECK (grad_offering IN ()), 
            ADD CHECK (highest_degree_offered IN ()), 
            ADD CHECK (degree_granting_status IN ()), 
            ADD CHECK (hbcu IN ()), 
            ADD CHECK (tribal_college IN ()), 
            ADD CHECK (urban_locale IN ()), 
            ADD CHECK (open_to_public IN ()), 
            ADD FOREIGN KEY (institution_status) REFERENCES institution_xref_institution_status(Codevalue), 
            ADD CHECK (active_in_current_year IN ()), 
            ADD CHECK (primarily_postsecondary IN ()), 
            ADD CHECK (inst_indicator IN ()), 
            ADD CHECK (title_iv_indicator IN ()), 
            ADD CHECK (cbsa IN ()), 
            ADD CHECK (cbsa_type IN ()), 
            ADD CHECK (csa IN ()), 
            ADD CHECK (necta IN ()), 
            ADD CHECK (fips_county_code IN ()), 
            ADD CHECK (state_congressional_dist_id IN ()), 
            ADD CHECK (cert_lt_1yr IN ()), 
            ADD CHECK (cert_lt_12wks IN ()), 
            ADD CHECK (cert_12wks_lt_1yr IN ()), 
            ADD CHECK (cert_1yr_lt_2yr IN ()), 
            ADD CHECK (associates_degree IN ()), 
            ADD CHECK (cert_2yr_lt_4yr IN ()), 
            ADD CHECK (bachelors_degree IN ()), 
            ADD CHECK (postbacc_cert IN ()), 
            ADD CHECK (masters_degree IN ()), 
            ADD CHECK (post_masters_cert IN ()), 
            ADD CHECK (doctors_degree_research IN ()), 
            ADD CHECK (doctors_degree_prof_practice IN ()), 
            ADD CHECK (doctors_degree_other IN ()), 
            ADD CHECK (fulltime_undergrad_enrolled IN ()), 
            ADD CHECK (fulltime_undergrad_live_on_cmps IN ()), 
            ADD CHECK (oncampus_housing IN ()), 
            ADD FOREIGN KEY (cip_code_largest_program) REFERENCES institution_xref_cip_code_largest_program(Codevalue), 
            ADD CHECK (largest_program_length_credit_clock IN ());