ALTER TABLE institution_libraries 
    ADD COLUMN library_expenses_100k TINYINT COMMENT "LEXP100K|Were annual total library expenses greater than or equal to $100,000",
    ADD COLUMN library_collection_electronic TINYINT COMMENT "LCOLELYN|Is the Library collection entirely electronic",
  ADD COLUMN num_physical_books_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LPBOOKS|Number of physical books",
    ADD COLUMN num_physical_books FLOAT COMMENT "LPBOOKS|Number of physical books",
  ADD COLUMN num_digital_books_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEBOOKS|Number of digital/electronic books",
    ADD COLUMN num_digital_books INT COMMENT "LEBOOKS|Number of digital/electronic books",
  ADD COLUMN num_digital_databases_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEDATAB|Number of digital/electronic databases",
    ADD COLUMN num_digital_databases INT COMMENT "LEDATAB|Number of digital/electronic databases",
  ADD COLUMN num_physical_media_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LPMEDIA|Number of physical media",
    ADD COLUMN num_physical_media FLOAT COMMENT "LPMEDIA|Number of physical media",
  ADD COLUMN num_digital_media_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEMEDIA|Number of digital/electronic media",
    ADD COLUMN num_digital_media INT COMMENT "LEMEDIA|Number of digital/electronic media",
  ADD COLUMN num_physical_serials_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LPSERIA|Number of physical serials",
    ADD COLUMN num_physical_serials FLOAT COMMENT "LPSERIA|Number of physical serials",
  ADD COLUMN num_digital_serials_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LESERIA|Number of electronic serials",
    ADD COLUMN num_digital_serials INT COMMENT "LESERIA|Number of electronic serials",
  ADD COLUMN total_physical_collections_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LPCLLCT|Total physical library collections (books, media and serials)",
    ADD COLUMN total_physical_collections FLOAT COMMENT "LPCLLCT|Total physical library collections (books, media and serials)",
  ADD COLUMN total_electronic_collections_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LECLLCT|Total electronic library collections (books, databases, media and serials)",
    ADD COLUMN total_electronic_collections INT COMMENT "LECLLCT|Total electronic library collections (books, databases, media and serials)",
  ADD COLUMN total_library_collections_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LTCLLCT|Total library collections (physical and electronic)",
    ADD COLUMN total_library_collections INT COMMENT "LTCLLCT|Total library collections (physical and electronic)",
  ADD COLUMN total_physical_circulations_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LPCRCLT|Total physical library circulations (books and media)",
    ADD COLUMN total_physical_circulations FLOAT COMMENT "LPCRCLT|Total physical library circulations (books and media)",
  ADD COLUMN total_digital_circulations_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LECRCLT|Total digital/electronic circulations (books and media)",
    ADD COLUMN total_digital_circulations INT COMMENT "LECRCLT|Total digital/electronic circulations (books and media)",
  ADD COLUMN total_library_circulations_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LTCRCLT|Total library circulations (physical and digital/electronic)",
    ADD COLUMN total_library_circulations INT COMMENT "LTCRCLT|Total library circulations (physical and digital/electronic)",
    ADD COLUMN interlibrary_loan_services TINYINT COMMENT "LILLDYN|Does institution have interlibrary loan services ?",
  ADD COLUMN total_ill_documents_provided_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LILLDPR|Total interlibrary loans and documents provided to other libraries",
    ADD COLUMN total_ill_documents_provided FLOAT COMMENT "LILLDPR|Total interlibrary loans and documents provided to other libraries",
  ADD COLUMN total_ill_documents_received_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LILLDRC|Total interlibrary loans and documents received",
    ADD COLUMN total_ill_documents_received FLOAT COMMENT "LILLDRC|Total interlibrary loans and documents received",
    ADD COLUMN library_staff TINYINT COMMENT "LILSYN|Does  institution have Library Staff?",
  ADD COLUMN total_lib_fte_staff_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSTOTAL|Total library FTE staff",
    ADD COLUMN total_lib_fte_staff FLOAT COMMENT "LSTOTAL|Total library FTE staff",
  ADD COLUMN librarians_fte_staff_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSLIBRN|Librarians FTE staff",
    ADD COLUMN librarians_fte_staff FLOAT COMMENT "LSLIBRN|Librarians FTE staff",
  ADD COLUMN other_prof_fte_staff_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSOPROF|Other professional FTE staff",
    ADD COLUMN other_prof_fte_staff FLOAT COMMENT "LSOPROF|Other professional FTE staff",
  ADD COLUMN other_paid_fte_staff_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSOPAID|All other paid FTE staff (Except Student Assistants)",
    ADD COLUMN other_paid_fte_staff FLOAT COMMENT "LSOPAID|All other paid FTE staff (Except Student Assistants)",
  ADD COLUMN student_assistants_fte_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSSTAST|Student assistants FTE",
    ADD COLUMN student_assistants_fte FLOAT COMMENT "LSSTAST|Student assistants FTE",
  ADD COLUMN num_branches_libraries_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LBRANCH|Number of branches and independent libraries",
    ADD COLUMN num_branches_libraries FLOAT COMMENT "LBRANCH|Number of branches and independent libraries",
  ADD COLUMN total_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LSALWAG|Total salaries and wages from the library budget",
    ADD COLUMN total_salaries_wages DOUBLE COMMENT "LSALWAG|Total salaries and wages from the library budget",
    ADD COLUMN staff_fringe_benefits TINYINT COMMENT "LFRNGBYN|Are staff fringe benefits paid out of the library budget",
  ADD COLUMN total_fringe_benefits_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LFRNGBN|Total fringe benefits",
    ADD COLUMN total_fringe_benefits DOUBLE COMMENT "LFRNGBN|Total fringe benefits",
  ADD COLUMN one_time_purchases_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXMSBB|One-time purchases of books, serial backfiles, and other materials",
    ADD COLUMN one_time_purchases DOUBLE COMMENT "LEXMSBB|One-time purchases of books, serial backfiles, and other materials",
  ADD COLUMN ongoing_subscriptions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXMSCS|Ongoing commitments to subscriptions",
    ADD COLUMN ongoing_subscriptions DOUBLE COMMENT "LEXMSCS|Ongoing commitments to subscriptions",
  ADD COLUMN other_materials_services_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXMSOT|Other materials/services expenditures",
    ADD COLUMN other_materials_services DOUBLE COMMENT "LEXMSOT|Other materials/services expenditures",
  ADD COLUMN total_materials_services_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXMSTL|Total materials/services expenditures",
    ADD COLUMN total_materials_services DOUBLE COMMENT "LEXMSTL|Total materials/services expenditures",
  ADD COLUMN preservation_services_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXOMPS|Preservation services",
    ADD COLUMN preservation_services DOUBLE COMMENT "LEXOMPS|Preservation services",
  ADD COLUMN other_op_maintenance_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXOMOT|Other operation and maintenance expenditures",
    ADD COLUMN other_op_maintenance DOUBLE COMMENT "LEXOMOT|Other operation and maintenance expenditures",
  ADD COLUMN total_op_maintenance_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXOMTL|Total operations and maintenance expenditures",
    ADD COLUMN total_op_maintenance DOUBLE COMMENT "LEXOMTL|Total operations and maintenance expenditures",
  ADD COLUMN total_expenditures_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LEXPTOT|Total expenditures (salaries/wages, benefits, materials/services, and operations/maintenance)",
    ADD COLUMN total_expenditures DOUBLE COMMENT "LEXPTOT|Total expenditures (salaries/wages, benefits, materials/services, and operations/maintenance)",
    ADD COLUMN salaries_wages_materials_services DOUBLE COMMENT "LSWMSOM|Salaries/wages, materials/services, and operations/maintenance";