ALTER TABLE institution_fy_enroll_headcount 
    ADD COLUMN student_level SMALLINT COMMENT "EFFYALEV|Level and degree/certificate-seeking status of student",
    ADD COLUMN student_level_ug_grad SMALLINT COMMENT "EFFYLEV|Undergraduate or graduate level of student",
    ADD COLUMN study_level SMALLINT COMMENT "LSTUDY|Original level of study on survey form",
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYTOTLT|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "EFYTOTLT|Grand total",
  ADD COLUMN grand_total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYTOTLM|Grand total men",
    ADD COLUMN grand_total_men MEDIUMINT COMMENT "EFYTOTLM|Grand total men",
  ADD COLUMN grand_total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYTOTLW|Grand total women",
    ADD COLUMN grand_total_women MEDIUMINT COMMENT "EFYTOTLW|Grand total women",
  ADD COLUMN ai_an_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYAIANT|American Indian or Alaska Native total",
    ADD COLUMN ai_an_total MEDIUMINT COMMENT "EFYAIANT|American Indian or Alaska Native total",
  ADD COLUMN ai_an_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYAIANM|American Indian or Alaska Native men",
    ADD COLUMN ai_an_men MEDIUMINT COMMENT "EFYAIANM|American Indian or Alaska Native men",
  ADD COLUMN ai_an_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYAIANW|American Indian or Alaska Native women",
    ADD COLUMN ai_an_women MEDIUMINT COMMENT "EFYAIANW|American Indian or Alaska Native women",
  ADD COLUMN asian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYASIAT|Asian total",
    ADD COLUMN asian_total MEDIUMINT COMMENT "EFYASIAT|Asian total",
  ADD COLUMN asian_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYASIAM|Asian men",
    ADD COLUMN asian_men MEDIUMINT COMMENT "EFYASIAM|Asian men",
  ADD COLUMN asian_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYASIAW|Asian women",
    ADD COLUMN asian_women MEDIUMINT COMMENT "EFYASIAW|Asian women",
  ADD COLUMN black_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYBKAAT|Black or African American total",
    ADD COLUMN black_total MEDIUMINT COMMENT "EFYBKAAT|Black or African American total",
  ADD COLUMN black_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYBKAAM|Black or African American men",
    ADD COLUMN black_men MEDIUMINT COMMENT "EFYBKAAM|Black or African American men",
  ADD COLUMN black_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYBKAAW|Black or African American women",
    ADD COLUMN black_women MEDIUMINT COMMENT "EFYBKAAW|Black or African American women",
  ADD COLUMN hispanic_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYHISPT|Hispanic or Latino total",
    ADD COLUMN hispanic_total MEDIUMINT COMMENT "EFYHISPT|Hispanic or Latino total",
  ADD COLUMN hispanic_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYHISPM|Hispanic or Latino men",
    ADD COLUMN hispanic_men MEDIUMINT COMMENT "EFYHISPM|Hispanic or Latino men",
  ADD COLUMN hispanic_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYHISPW|Hispanic or Latino women",
    ADD COLUMN hispanic_women MEDIUMINT COMMENT "EFYHISPW|Hispanic or Latino women",
  ADD COLUMN nh_opi_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNHPIT|Native Hawaiian or Other Pacific Islander total",
    ADD COLUMN nh_opi_total MEDIUMINT COMMENT "EFYNHPIT|Native Hawaiian or Other Pacific Islander total",
  ADD COLUMN native_hawaiian_pacific_islander_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNHPIM|Native Hawaiian or Other Pacific Islander men",
    ADD COLUMN native_hawaiian_pacific_islander_men MEDIUMINT COMMENT "EFYNHPIM|Native Hawaiian or Other Pacific Islander men",
  ADD COLUMN native_hawaiian_pacific_islander_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNHPIW|Native Hawaiian or Other Pacific Islander women",
    ADD COLUMN native_hawaiian_pacific_islander_women MEDIUMINT COMMENT "EFYNHPIW|Native Hawaiian or Other Pacific Islander women",
  ADD COLUMN white_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYWHITT|White total",
    ADD COLUMN white_total MEDIUMINT COMMENT "EFYWHITT|White total",
  ADD COLUMN white_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYWHITM|White men",
    ADD COLUMN white_men MEDIUMINT COMMENT "EFYWHITM|White men",
  ADD COLUMN white_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYWHITW|White women",
    ADD COLUMN white_women MEDIUMINT COMMENT "EFYWHITW|White women",
  ADD COLUMN two_or_more_races_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFY2MORT|Two or more races total",
    ADD COLUMN two_or_more_races_total MEDIUMINT COMMENT "EFY2MORT|Two or more races total",
  ADD COLUMN two_or_more_races_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFY2MORM|Two or more races men",
    ADD COLUMN two_or_more_races_men MEDIUMINT COMMENT "EFY2MORM|Two or more races men",
  ADD COLUMN two_or_more_races_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFY2MORW|Two or more races women",
    ADD COLUMN two_or_more_races_women MEDIUMINT COMMENT "EFY2MORW|Two or more races women",
  ADD COLUMN race_ethnicity_unknown_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYUNKNT|Race/ethnicity unknown total",
    ADD COLUMN race_ethnicity_unknown_total MEDIUMINT COMMENT "EFYUNKNT|Race/ethnicity unknown total",
  ADD COLUMN race_ethnicity_unknown_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYUNKNM|Race/ethnicity unknown men",
    ADD COLUMN race_ethnicity_unknown_men MEDIUMINT COMMENT "EFYUNKNM|Race/ethnicity unknown men",
  ADD COLUMN race_ethnicity_unknown_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYUNKNW|Race/ethnicity unknown women",
    ADD COLUMN race_ethnicity_unknown_women MEDIUMINT COMMENT "EFYUNKNW|Race/ethnicity unknown women",
  ADD COLUMN nonresident_alien_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNRALT|Nonresident alien total",
    ADD COLUMN nonresident_alien_total MEDIUMINT COMMENT "EFYNRALT|Nonresident alien total",
  ADD COLUMN nonresident_alien_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNRALM|Nonresident alien men",
    ADD COLUMN nonresident_alien_men MEDIUMINT COMMENT "EFYNRALM|Nonresident alien men",
  ADD COLUMN nonresident_alien_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFYNRALW|Nonresident alien women",
    ADD COLUMN nonresident_alien_women MEDIUMINT COMMENT "EFYNRALW|Nonresident alien women";