ALTER TABLE institution_comp_award_race_gender 
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLT|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "CSTOTLT|Grand total",
  ADD COLUMN grand_total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLM|Grand total men",
    ADD COLUMN grand_total_men MEDIUMINT COMMENT "CSTOTLM|Grand total men",
  ADD COLUMN grand_total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSTOTLW|Grand total women",
    ADD COLUMN grand_total_women MEDIUMINT COMMENT "CSTOTLW|Grand total women",
  ADD COLUMN ai_an_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSAIANT|American Indian or Alaska Native total",
    ADD COLUMN ai_an_total MEDIUMINT COMMENT "CSAIANT|American Indian or Alaska Native total",
  ADD COLUMN ai_an_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSAIANM|American Indian or Alaska Native men",
    ADD COLUMN ai_an_men MEDIUMINT COMMENT "CSAIANM|American Indian or Alaska Native men",
  ADD COLUMN ai_an_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSAIANW|American Indian or Alaska Native women",
    ADD COLUMN ai_an_women MEDIUMINT COMMENT "CSAIANW|American Indian or Alaska Native women",
  ADD COLUMN asian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSASIAT|Asian total",
    ADD COLUMN asian_total MEDIUMINT COMMENT "CSASIAT|Asian total",
  ADD COLUMN asian_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSASIAM|Asian men",
    ADD COLUMN asian_men MEDIUMINT COMMENT "CSASIAM|Asian men",
  ADD COLUMN asian_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSASIAW|Asian women",
    ADD COLUMN asian_women MEDIUMINT COMMENT "CSASIAW|Asian women",
  ADD COLUMN black_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSBKAAT|Black or African American total",
    ADD COLUMN black_total MEDIUMINT COMMENT "CSBKAAT|Black or African American total",
  ADD COLUMN black_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSBKAAM|Black or African American men",
    ADD COLUMN black_men MEDIUMINT COMMENT "CSBKAAM|Black or African American men",
  ADD COLUMN black_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSBKAAW|Black or African American women",
    ADD COLUMN black_women MEDIUMINT COMMENT "CSBKAAW|Black or African American women",
  ADD COLUMN hispanic_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSHISPT|Hispanic or Latino total",
    ADD COLUMN hispanic_total MEDIUMINT COMMENT "CSHISPT|Hispanic or Latino total",
  ADD COLUMN hispanic_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSHISPM|Hispanic or Latino men",
    ADD COLUMN hispanic_men MEDIUMINT COMMENT "CSHISPM|Hispanic or Latino men",
  ADD COLUMN hispanic_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSHISPW|Hispanic or Latino women",
    ADD COLUMN hispanic_women MEDIUMINT COMMENT "CSHISPW|Hispanic or Latino women",
  ADD COLUMN nh_opi_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNHPIT|Native Hawaiian or Other Pacific Islander total",
    ADD COLUMN nh_opi_total MEDIUMINT COMMENT "CSNHPIT|Native Hawaiian or Other Pacific Islander total",
  ADD COLUMN nh_opi_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNHPIM|Native Hawaiian or Other Pacific Islander men",
    ADD COLUMN nh_opi_men MEDIUMINT COMMENT "CSNHPIM|Native Hawaiian or Other Pacific Islander men",
  ADD COLUMN nh_opi_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNHPIW|Native Hawaiian or Other Pacific Islander women",
    ADD COLUMN nh_opi_women MEDIUMINT COMMENT "CSNHPIW|Native Hawaiian or Other Pacific Islander women",
  ADD COLUMN white_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSWHITT|White total",
    ADD COLUMN white_total MEDIUMINT COMMENT "CSWHITT|White total",
  ADD COLUMN white_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSWHITM|White men",
    ADD COLUMN white_men MEDIUMINT COMMENT "CSWHITM|White men",
  ADD COLUMN white_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSWHITW|White women",
    ADD COLUMN white_women MEDIUMINT COMMENT "CSWHITW|White women",
  ADD COLUMN two_or_more_races_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS2MORT|Two or more races total",
    ADD COLUMN two_or_more_races_total MEDIUMINT COMMENT "CS2MORT|Two or more races total",
  ADD COLUMN two_or_more_races_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS2MORM|Two or more races men",
    ADD COLUMN two_or_more_races_men MEDIUMINT COMMENT "CS2MORM|Two or more races men",
  ADD COLUMN two_or_more_races_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CS2MORW|Two or more races women",
    ADD COLUMN two_or_more_races_women MEDIUMINT COMMENT "CS2MORW|Two or more races women",
  ADD COLUMN race_ethnicity_unknown_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUNKNT|Race/ethnicity unknown total",
    ADD COLUMN race_ethnicity_unknown_total MEDIUMINT COMMENT "CSUNKNT|Race/ethnicity unknown total",
  ADD COLUMN race_ethnicity_unknown_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUNKNM|Race/ethnicity unknown men",
    ADD COLUMN race_ethnicity_unknown_men MEDIUMINT COMMENT "CSUNKNM|Race/ethnicity unknown men",
  ADD COLUMN race_ethnicity_unknown_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSUNKNW|Race/ethnicity unknown women",
    ADD COLUMN race_ethnicity_unknown_women MEDIUMINT COMMENT "CSUNKNW|Race/ethnicity unknown women",
  ADD COLUMN nonresident_alien_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNRALT|Nonresident alien total",
    ADD COLUMN nonresident_alien_total MEDIUMINT COMMENT "CSNRALT|Nonresident alien total",
  ADD COLUMN nonresident_alien_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNRALM|Nonresident alien men",
    ADD COLUMN nonresident_alien_men MEDIUMINT COMMENT "CSNRALM|Nonresident alien men",
  ADD COLUMN nonresident_alien_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CSNRALW|Nonresident alien women",
    ADD COLUMN nonresident_alien_women MEDIUMINT COMMENT "CSNRALW|Nonresident alien women";