ALTER TABLE institution_gr_gt2yr_200pct 
  ADD COLUMN revised_bach_cohort_2013_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAREVCT|Revised bachelor's degree-seeking cohort, (cohort year 2013)",
    ADD COLUMN revised_bach_cohort_2013 FLOAT COMMENT "BAREVCT|Revised bachelor's degree-seeking cohort, (cohort year 2013)",
  ADD COLUMN exclusions_bach_cohort_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAEXCLU|Exclusions from bachelor's degree-seeking cohort within 150% percent of normal time",
    ADD COLUMN exclusions_bach_cohort_150pct FLOAT COMMENT "BAEXCLU|Exclusions from bachelor's degree-seeking cohort within 150% percent of normal time",
  ADD COLUMN adjusted_bach_cohort_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAAC150|Adjusted bachelor's degree-seeking cohort within 150% of normal time",
    ADD COLUMN adjusted_bach_cohort_150pct FLOAT COMMENT "BAAC150|Adjusted bachelor's degree-seeking cohort within 150% of normal time",
  ADD COLUMN num_completed_bach_100pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BANC100|Number completed a bachelor's degree within 100% of normal time (4-years)",
    ADD COLUMN num_completed_bach_100pct FLOAT COMMENT "BANC100|Number completed a bachelor's degree within 100% of normal time (4-years)",
  ADD COLUMN grad_rate_bach_100pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAGR100|4-year Graduation rate - bachelor's degree within 100% of normal time",
    ADD COLUMN grad_rate_bach_100pct FLOAT COMMENT "BAGR100|4-year Graduation rate - bachelor's degree within 100% of normal time",
  ADD COLUMN num_completed_bach_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BANC150|Number completed a bachelor's degree within 150% of normal time (6-years)",
    ADD COLUMN num_completed_bach_150pct FLOAT COMMENT "BANC150|Number completed a bachelor's degree within 150% of normal time (6-years)",
  ADD COLUMN grad_rate_bach_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAGR150|6-year Graduation rate - bachelor's degree within 150% of normal time",
    ADD COLUMN grad_rate_bach_150pct FLOAT COMMENT "BAGR150|6-year Graduation rate - bachelor's degree within 150% of normal time",
  ADD COLUMN additional_exclusions_bach_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAAEXCL|Additional exclusions from bachelor's degree-seeking cohort",
    ADD COLUMN additional_exclusions_bach_cohort FLOAT COMMENT "BAAEXCL|Additional exclusions from bachelor's degree-seeking cohort",
  ADD COLUMN adjusted_bach_cohort_200pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAAC200|Adjusted bachelor's degree-seeking cohort within 200% of normal time",
    ADD COLUMN adjusted_bach_cohort_200pct FLOAT COMMENT "BAAC200|Adjusted bachelor's degree-seeking cohort within 200% of normal time",
  ADD COLUMN num_completed_bach_150_200pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BANC200A|Number completed a bachelor's degree between 150% and 200% of normal time",
    ADD COLUMN num_completed_bach_150_200pct FLOAT COMMENT "BANC200A|Number completed a bachelor's degree between 150% and 200% of normal time",
  ADD COLUMN still_enrolled_ba_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BASTEND|Still enrolled",
    ADD COLUMN still_enrolled_ba FLOAT COMMENT "BASTEND|Still enrolled",
  ADD COLUMN num_completed_bach_200pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BANC200|Number completed a bachelor's degree within 200% of normal time (8-years)",
    ADD COLUMN num_completed_bach_200pct FLOAT COMMENT "BANC200|Number completed a bachelor's degree within 200% of normal time (8-years)",
  ADD COLUMN grad_rate_bach_200pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "BAGR200|8-year Graduation rate - bachelor's degree within 200% of normal time",
    ADD COLUMN grad_rate_bach_200pct FLOAT COMMENT "BAGR200|8-year Graduation rate - bachelor's degree within 200% of normal time",
  ADD COLUMN revised_degree_cohort_2017_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4REVCT|Revised degree/certificate-seeking cohort, (cohort year 2017)",
    ADD COLUMN revised_degree_cohort_2017 FLOAT COMMENT "L4REVCT|Revised degree/certificate-seeking cohort, (cohort year 2017)",
  ADD COLUMN exclusions_degree_cohort_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4EXCLU|Exclusions from degree/certificate-seeking cohort within 150% percent of normal time",
    ADD COLUMN exclusions_degree_cohort_150pct FLOAT COMMENT "L4EXCLU|Exclusions from degree/certificate-seeking cohort within 150% percent of normal time",
  ADD COLUMN adjusted_degree_cohort_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4AC150|Adjusted degree/certificate-seeking cohort within 150% of normal time",
    ADD COLUMN adjusted_degree_cohort_150pct FLOAT COMMENT "L4AC150|Adjusted degree/certificate-seeking cohort within 150% of normal time",
  ADD COLUMN num_completed_degree_100pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4NC100|Number completed a degree/certificate within 100% of normal time",
    ADD COLUMN num_completed_degree_100pct FLOAT COMMENT "L4NC100|Number completed a degree/certificate within 100% of normal time",
  ADD COLUMN grad_rate_degree_100pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4GR100|Graduation rate - degree/certificate within 100% of normal time",
    ADD COLUMN grad_rate_degree_100pct FLOAT COMMENT "L4GR100|Graduation rate - degree/certificate within 100% of normal time",
  ADD COLUMN num_completed_degree_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4NC150|Number completed a degree/certificate  within 150% of normal time",
    ADD COLUMN num_completed_degree_150pct FLOAT COMMENT "L4NC150|Number completed a degree/certificate  within 150% of normal time",
  ADD COLUMN grad_rate_150pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4GR150|Graduation rate - degree/certificate within 150% of normal time",
    ADD COLUMN grad_rate_150pct_norm_time FLOAT COMMENT "L4GR150|Graduation rate - degree/certificate within 150% of normal time",
  ADD COLUMN additional_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4AEXCL|Additional exclusions from degree/certificate-seeking cohort",
    ADD COLUMN additional_exclusions FLOAT COMMENT "L4AEXCL|Additional exclusions from degree/certificate-seeking cohort",
  ADD COLUMN adj_cohort_200pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4AC200|Adjusted degree/certificate-seeking cohort within 200% of normal time",
    ADD COLUMN adj_cohort_200pct_norm_time FLOAT COMMENT "L4AC200|Adjusted degree/certificate-seeking cohort within 200% of normal time",
  ADD COLUMN num_completed_150pct_200pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4NC200A|Number completed a  degree/certificate between 150% and 200% of normal time",
    ADD COLUMN num_completed_150pct_200pct_norm_time FLOAT COMMENT "L4NC200A|Number completed a  degree/certificate between 150% and 200% of normal time",
  ADD COLUMN still_enrolled_l4_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4STEND|Still enrolled",
    ADD COLUMN still_enrolled_l4 FLOAT COMMENT "L4STEND|Still enrolled",
  ADD COLUMN num_completed_200pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4NC200|Number completed a degree/certificate within 200% of normal time",
    ADD COLUMN num_completed_200pct_norm_time FLOAT COMMENT "L4NC200|Number completed a degree/certificate within 200% of normal time",
  ADD COLUMN grad_rate_200pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "L4GR200|Graduation rate - degree/certificate within 200% of normal time",
    ADD COLUMN grad_rate_200pct_norm_time FLOAT COMMENT "L4GR200|Graduation rate - degree/certificate within 200% of normal time";