ALTER TABLE institution_aid_benefit 
  ADD COLUMN num_post911_gi_bill_benefits_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGPO9_N|Number receiving Post-9/11 GI Bill Benefits - undergraduate students",
    ADD COLUMN num_post911_gi_bill_benefits_undergrad MEDIUMINT COMMENT "UGPO9_N|Number receiving Post-9/11 GI Bill Benefits - undergraduate students",
  ADD COLUMN total_post911_gi_bill_benefits_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGPO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - undergraduate students",
    ADD COLUMN total_post911_gi_bill_benefits_undergrad BIGINT COMMENT "UGPO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - undergraduate students",
  ADD COLUMN avg_post911_gi_bill_benefits_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGPO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - undergraduate students",
    ADD COLUMN avg_post911_gi_bill_benefits_undergrad FLOAT COMMENT "UGPO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - undergraduate students",
  ADD COLUMN num_post911_gi_bill_benefits_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GPO9_N|Number receiving Post-9/11 GI Bill Benefits - graduate students",
    ADD COLUMN num_post911_gi_bill_benefits_grad FLOAT COMMENT "GPO9_N|Number receiving Post-9/11 GI Bill Benefits - graduate students",
  ADD COLUMN total_post911_gi_bill_benefits_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GPO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - graduate students",
    ADD COLUMN total_post911_gi_bill_benefits_grad DOUBLE COMMENT "GPO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - graduate students",
  ADD COLUMN avg_post911_gi_bill_benefits_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GPO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - graduate students",
    ADD COLUMN avg_post911_gi_bill_benefits_grad FLOAT COMMENT "GPO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - graduate students",
  ADD COLUMN num_post911_gi_bill_benefits_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PO9_N|Number receiving Post-9/11 GI Bill Benefits - all students",
    ADD COLUMN num_post911_gi_bill_benefits_all MEDIUMINT COMMENT "PO9_N|Number receiving Post-9/11 GI Bill Benefits - all students",
  ADD COLUMN total_post911_gi_bill_benefits_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - all students",
    ADD COLUMN total_post911_gi_bill_benefits_all BIGINT COMMENT "PO9_T|Total amount of Post-9/11 GI Bill Benefits awarded - all students",
  ADD COLUMN avg_post911_gi_bill_benefits_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - all students",
    ADD COLUMN avg_post911_gi_bill_benefits_all FLOAT COMMENT "PO9_A|Average amount of Post-9/11 GI Bill Benefits awarded - all students",
  ADD COLUMN num_dod_tuition_assistance_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGDOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - undergraduate students",
    ADD COLUMN num_dod_tuition_assistance_undergrad MEDIUMINT COMMENT "UGDOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - undergraduate students",
  ADD COLUMN total_dod_tuition_assistance_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGDOD_T|Total amount of Department of Defense Tuition Assistance Program benefits  awarded - undergraduate students",
    ADD COLUMN total_dod_tuition_assistance_undergrad BIGINT COMMENT "UGDOD_T|Total amount of Department of Defense Tuition Assistance Program benefits  awarded - undergraduate students",
  ADD COLUMN avg_dod_tuition_assistance_undergrad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "UGDOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded- undergraduate students",
    ADD COLUMN avg_dod_tuition_assistance_undergrad FLOAT COMMENT "UGDOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded- undergraduate students",
  ADD COLUMN num_dod_tuition_assistance_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GDOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - graduate students",
    ADD COLUMN num_dod_tuition_assistance_grad FLOAT COMMENT "GDOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - graduate students",
  ADD COLUMN total_dod_tuition_assistance_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GDOD_T|Total amount of Department of Defense Tuition Assistance Program benefits awarded - graduate students",
    ADD COLUMN total_dod_tuition_assistance_grad DOUBLE COMMENT "GDOD_T|Total amount of Department of Defense Tuition Assistance Program benefits awarded - graduate students",
  ADD COLUMN avg_dod_tuition_assistance_grad_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GDOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded - graduate students",
    ADD COLUMN avg_dod_tuition_assistance_grad FLOAT COMMENT "GDOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded - graduate students",
  ADD COLUMN num_dod_tuition_assistance_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "DOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - all students",
    ADD COLUMN num_dod_tuition_assistance_all MEDIUMINT COMMENT "DOD_N|Number receiving Department of Defense Tuition Assistance Program benefits - all students",
  ADD COLUMN total_dod_tuition_assistance_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "DOD_T|Total amount of Department of Defense Tuition Assistance Program benefits awarded - all students",
    ADD COLUMN total_dod_tuition_assistance_all BIGINT COMMENT "DOD_T|Total amount of Department of Defense Tuition Assistance Program benefits awarded - all students",
  ADD COLUMN avg_dod_tuition_assistance_all_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "DOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded - all students",
    ADD COLUMN avg_dod_tuition_assistance_all FLOAT COMMENT "DOD_A|Average amount of Department of Defense Tuition Assistance Program benefits awarded - all students";