ALTER TABLE institution_ic_campuses 
    ADD COLUMN branch_id TINYINT COMMENT "CAMPUSID|Branch Campus Identifcation number",
    ADD COLUMN branch_name VARCHAR(120) COMMENT "PCINSTNM|Branch Campus Name",
    ADD COLUMN address VARCHAR(100) COMMENT "PCADDR|Street address or post office box",
    ADD COLUMN city VARCHAR(30) COMMENT "PCCITY|City location of institution",
    ADD COLUMN state VARCHAR(2) COMMENT "PCSTABBR|State abbreviation",
    ADD COLUMN zip_code VARCHAR(10) COMMENT "PCZIP|ZIP code",
    ADD COLUMN fips_st_code TINYINT COMMENT "PCFIPS|FIPS state code",
    ADD COLUMN bea_regions TINYINT COMMENT "PCOBEREG|Bureau of Economic Analysis (BEA) regions",
    ADD COLUMN chief_admin_name VARCHAR(50) COMMENT "PCCHFNM|Name of chief administrator",
    ADD COLUMN chief_admin_title VARCHAR(50) COMMENT "PCCHFTITLE|Title of chief administrator",
    ADD COLUMN phone_number VARCHAR(15) COMMENT "PCGENTELE|General information telephone number",
    ADD COLUMN employer_id VARCHAR(9) COMMENT "PCEIN|Employer Identification Number",
    ADD COLUMN dun_bradstreet_numbers VARCHAR(2000) COMMENT "PCDUNS|Dun and Bradstreet numbers",
    ADD COLUMN ope_id VARCHAR(8) COMMENT "PCOPEID|Office of Postsecondary Education (OPE) ID Number",
    ADD COLUMN ope_eligibility_code TINYINT COMMENT "PCOPEFLAG|OPE Title IV eligibility indicator code",
    ADD COLUMN former_unitid MEDIUMINT COMMENT "OLDUNITID|Former unitid if branch location once reported in IPEDS",
    ADD COLUMN inst_website VARCHAR(150) COMMENT "PCWEBADDR|Institution's internet website address",
    ADD COLUMN admissions_url VARCHAR(200) COMMENT "PCADMINURL|Admissions office web address",
    ADD COLUMN financial_aid_url VARCHAR(200) COMMENT "PCFAIDURL|Financial aid office web address",
    ADD COLUMN online_app_url VARCHAR(200) COMMENT "PCAPPLURL|Online application web address",
    ADD COLUMN net_price_calc_url VARCHAR(200) COMMENT "PCNPRICURL|Net price calculator web address",
    ADD COLUMN veterans_tuition_url VARCHAR(200) COMMENT "PCVETURL|Veterans and Military Servicemembers tuition policies web address",
    ADD COLUMN student_athlete_grad_rate_url VARCHAR(150) COMMENT "PCATHURL|Student-Right-to-Know student athlete graduation rate web address",
    ADD COLUMN disability_url VARCHAR(200) COMMENT "PCDISAURL|Disability Services Web Address",
    ADD COLUMN sector TINYINT COMMENT "PCSECTOR|Sector of institution",
    ADD COLUMN level TINYINT COMMENT "PCICLEVEL|Level of institution",
    ADD COLUMN control TINYINT COMMENT "PCCONTROL|Control of institution",
    ADD COLUMN highest_level_offering TINYINT COMMENT "PCHLOFFER|Highest level of offering",
    ADD COLUMN undergrad_offering TINYINT COMMENT "PCUGOFFER|Undergraduate offering",
    ADD COLUMN grad_offering TINYINT COMMENT "PCGROFFER|Graduate offering",
    ADD COLUMN highest_degree_offered TINYINT COMMENT "PCHDEGOFR1|Highest degree offered",
    ADD COLUMN degree_granting_status TINYINT COMMENT "PCDEGGRANT|Degree-granting status",
    ADD COLUMN hbcu TINYINT COMMENT "PCHBCU|Historically Black College or University",
    ADD COLUMN tribal_college TINYINT COMMENT "PCTRIBAL|Tribal college",
    ADD COLUMN urban_locale TINYINT COMMENT "PCLOCALE|Degree of urbanization (Urban-centric locale)",
    ADD COLUMN open_to_public TINYINT COMMENT "PCOPENPUBL|Institution open to the general public",
    ADD COLUMN institution_status VARCHAR(1) COMMENT "PCACT|Status of institution",
    ADD COLUMN active_in_current_year TINYINT COMMENT "PCCYACTIVE|Institution is active in current year",
    ADD COLUMN primarily_postsecondary TINYINT COMMENT "PCPOSTSEC|Primarily postsecondary indicator",
    ADD COLUMN inst_indicator TINYINT COMMENT "PCPSEFLAG|Postsecondary institution indicator",
    ADD COLUMN title_iv_indicator TINYINT COMMENT "PCPSET4FLG|Postsecondary and Title IV institution indicator",
    ADD COLUMN cbsa MEDIUMINT COMMENT "PCCBSA|Core Based Statistical Area (CBSA)",
    ADD COLUMN cbsa_type TINYINT COMMENT "PCCBSATYPE|CBSA Type Metropolitan or Micropolitan",
    ADD COLUMN csa SMALLINT COMMENT "PCCSA|Combined Statistical Area (CSA)",
    ADD COLUMN necta MEDIUMINT COMMENT "PCNECTA|New England City and Town Area (NECTA)",
    ADD COLUMN fips_county_code MEDIUMINT COMMENT "PCCOUNTYCD|Fips County code",
    ADD COLUMN county_name VARCHAR(30) COMMENT "PCCOUNTYNM|County name",
    ADD COLUMN state_congressional_dist_id SMALLINT COMMENT "PCCNGDSTCD|State and 116TH Congressional District ID",
    ADD COLUMN longitude DOUBLE COMMENT "PCLONGITUD|Longitude location of institution",
    ADD COLUMN latitude DOUBLE COMMENT "PCLATITUDE|Latitude location of institution",
    ADD COLUMN cert_lt_1yr TINYINT COMMENT "PCLEVEL1|Certificate of less than 1 year",
    ADD COLUMN cert_lt_12wks TINYINT COMMENT "PCLEVEL1A|Certificate of less than 12 weeks",
    ADD COLUMN cert_12wks_lt_1yr TINYINT COMMENT "PCLEVEL1B|Certificate of at least 12 weeks, but less than 1 year",
    ADD COLUMN cert_1yr_lt_2yr TINYINT COMMENT "PCLEVEL2|Certifiicate of at least 1 year, but less than 2 years",
    ADD COLUMN associates_degree TINYINT COMMENT "PCLEVEL3|Associate's degree",
    ADD COLUMN cert_2yr_lt_4yr TINYINT COMMENT "PCLEVEL4|Certificate of at least 2 years, but less than 4 years",
    ADD COLUMN bachelors_degree TINYINT COMMENT "PCLEVEL5|Bachelor's degree",
    ADD COLUMN postbacc_cert TINYINT COMMENT "PCLEVEL6|Postbaccalaureate certificate",
    ADD COLUMN masters_degree TINYINT COMMENT "PCLEVEL7|Master's degree",
    ADD COLUMN post_masters_cert TINYINT COMMENT "PCLEVEL8|Post-master's certificate",
    ADD COLUMN doctors_degree_research TINYINT COMMENT "PCLEVEL17|Doctor's degree - research/scholarship",
    ADD COLUMN doctors_degree_prof_practice TINYINT COMMENT "PCLEVEL18|Doctor's degree - professional practice",
    ADD COLUMN doctors_degree_other TINYINT COMMENT "PCLEVEL19|Doctor's degree - other",
    ADD COLUMN fulltime_undergrad_enrolled TINYINT COMMENT "PCFT_FTUG|Full time first-time degree/certificate-seeking undergraduate students enrolled",
    ADD COLUMN fulltime_undergrad_live_on_cmps TINYINT COMMENT "PCALLONCAM|Full-time, first-time degree/certificate-seeking students required to live on campus",
  ADD COLUMN undergrad_app_fee_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCAPPLFEEU|Undergraduate application fee",
    ADD COLUMN undergrad_app_fee FLOAT COMMENT "PCAPPLFEEU|Undergraduate application fee",
    ADD COLUMN oncampus_housing TINYINT COMMENT "PCROOM|Institution provide on-campus housing",
  ADD COLUMN in_dist_tuition_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AT0|Published in-district tuition 2018-19",
    ADD COLUMN in_dist_tuition_2018_19 FLOAT COMMENT "PCCHG1AT0|Published in-district tuition 2018-19",
  ADD COLUMN in_dist_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AF0|Published in-district fees 2018-19",
    ADD COLUMN in_dist_fees_2018_19 FLOAT COMMENT "PCCHG1AF0|Published in-district fees 2018-19",
  ADD COLUMN in_dist_tuition_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AY0|Published in-district tuition and fees 2018-19",
    ADD COLUMN in_dist_tuition_fees_2018_19 FLOAT COMMENT "PCCHG1AY0|Published in-district tuition and fees 2018-19",
  ADD COLUMN in_dist_tuition_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AT1|Published in-district tuition 2019-20",
    ADD COLUMN in_dist_tuition_2019_20 FLOAT COMMENT "PCCHG1AT1|Published in-district tuition 2019-20",
  ADD COLUMN in_dist_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AF1|Published in-district fees 2019-20",
    ADD COLUMN in_dist_fees_2019_20 FLOAT COMMENT "PCCHG1AF1|Published in-district fees 2019-20",
  ADD COLUMN in_dist_tuition_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AY1|Published in-district tuition and fees 2019-20",
    ADD COLUMN in_dist_tuition_fees_2019_20 FLOAT COMMENT "PCCHG1AY1|Published in-district tuition and fees 2019-20",
  ADD COLUMN in_dist_tuition_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AT2|Published in-district tuition 2020-21",
    ADD COLUMN in_dist_tuition_2020_21 FLOAT COMMENT "PCCHG1AT2|Published in-district tuition 2020-21",
  ADD COLUMN in_dist_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AF2|Published in-district fees 2020-21",
    ADD COLUMN in_dist_fees_2020_21 FLOAT COMMENT "PCCHG1AF2|Published in-district fees 2020-21",
  ADD COLUMN in_dist_tuition_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AY2|Published in-district tuition and fees 2020-21",
    ADD COLUMN in_dist_tuition_fees_2020_21 FLOAT COMMENT "PCCHG1AY2|Published in-district tuition and fees 2020-21",
  ADD COLUMN in_dist_tuition_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AT3|Published in-district tuition 2021-22",
    ADD COLUMN in_dist_tuition_2021_22 FLOAT COMMENT "PCCHG1AT3|Published in-district tuition 2021-22",
  ADD COLUMN in_dist_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AF3|Published in-district fees 2021-22",
    ADD COLUMN in_dist_fees_2021_22 FLOAT COMMENT "PCCHG1AF3|Published in-district fees 2021-22",
  ADD COLUMN in_dist_tuition_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1AY3|Published in-district tuition and fees 2021-22",
    ADD COLUMN in_dist_tuition_fees_2021_22 FLOAT COMMENT "PCCHG1AY3|Published in-district tuition and fees 2021-22",
    ADD COLUMN publsd_in_dist_tuition_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG1TGTD|Published in-district tuition 2021-22 guaranteed percent increase (if applicable)",
    ADD COLUMN publsd_in_dist_fees_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG1FGTD|Published in-district fees 2021-22 guaranteed percent increase (if applicable)",
  ADD COLUMN publsd_in_st_tuition_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AT0|Published in-state tuition 2018-19",
    ADD COLUMN publsd_in_st_tuition_2018_19 FLOAT COMMENT "PCCHG2AT0|Published in-state tuition 2018-19",
  ADD COLUMN publsd_in_st_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AF0|Published in-state fees 2018-19",
    ADD COLUMN publsd_in_st_fees_2018_19 FLOAT COMMENT "PCCHG2AF0|Published in-state fees 2018-19",
  ADD COLUMN publsd_in_st_tuition_and_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AY0|Published in-state tuition and fees 2018-19",
    ADD COLUMN publsd_in_st_tuition_and_fees_2018_19 FLOAT COMMENT "PCCHG2AY0|Published in-state tuition and fees 2018-19",
  ADD COLUMN publsd_in_st_tuition_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AT1|Published in-state tuition 2019-20",
    ADD COLUMN publsd_in_st_tuition_2019_20 FLOAT COMMENT "PCCHG2AT1|Published in-state tuition 2019-20",
  ADD COLUMN publsd_in_st_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AF1|Published in-state fees 2019-20",
    ADD COLUMN publsd_in_st_fees_2019_20 FLOAT COMMENT "PCCHG2AF1|Published in-state fees 2019-20",
  ADD COLUMN publsd_in_st_tuition_and_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AY1|Published in-state tuition and fees 2019-20",
    ADD COLUMN publsd_in_st_tuition_and_fees_2019_20 FLOAT COMMENT "PCCHG2AY1|Published in-state tuition and fees 2019-20",
  ADD COLUMN publsd_in_st_tuition_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AT2|Published in-state tuition 2020-21",
    ADD COLUMN publsd_in_st_tuition_2020_21 FLOAT COMMENT "PCCHG2AT2|Published in-state tuition 2020-21",
  ADD COLUMN publsd_in_st_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AF2|Published in-state fees 2020-21",
    ADD COLUMN publsd_in_st_fees_2020_21 FLOAT COMMENT "PCCHG2AF2|Published in-state fees 2020-21",
  ADD COLUMN publsd_in_st_tuition_and_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AY2|Published in-state tuition and fees 2020-21",
    ADD COLUMN publsd_in_st_tuition_and_fees_2020_21 FLOAT COMMENT "PCCHG2AY2|Published in-state tuition and fees 2020-21",
  ADD COLUMN publsd_in_st_tuition_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AT3|Published in-state tuition 2021-22",
    ADD COLUMN publsd_in_st_tuition_2021_22 FLOAT COMMENT "PCCHG2AT3|Published in-state tuition 2021-22",
  ADD COLUMN publsd_in_st_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AF3|Published in-state fees 2021-22",
    ADD COLUMN publsd_in_st_fees_2021_22 FLOAT COMMENT "PCCHG2AF3|Published in-state fees 2021-22",
  ADD COLUMN publsd_in_st_tuition_and_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG2AY3|Published in-state tuition and fees 2021-22",
    ADD COLUMN publsd_in_st_tuition_and_fees_2021_22 FLOAT COMMENT "PCCHG2AY3|Published in-state tuition and fees 2021-22",
    ADD COLUMN publsd_in_st_tuition_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG2TGTD|Published in-state tuition 2021-22 guaranteed percent increase (if applicable)",
    ADD COLUMN publsd_in_st_fees_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG2FGTD|Published in-state fees 2021-22 guaranteed percent increase (if applicable)",
  ADD COLUMN publsd_out_of_st_tuition_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AT0|Published out-of-state tuition 2018-19",
    ADD COLUMN publsd_out_of_st_tuition_2018_19 FLOAT COMMENT "PCCHG3AT0|Published out-of-state tuition 2018-19",
  ADD COLUMN publsd_out_of_st_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AF0|Published out-of-state fees 2018-19",
    ADD COLUMN publsd_out_of_st_fees_2018_19 FLOAT COMMENT "PCCHG3AF0|Published out-of-state fees 2018-19",
  ADD COLUMN publsd_out_of_st_tuition_and_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AY0|Published out-of-state tuition and fees 2018-19",
    ADD COLUMN publsd_out_of_st_tuition_and_fees_2018_19 FLOAT COMMENT "PCCHG3AY0|Published out-of-state tuition and fees 2018-19",
  ADD COLUMN publsd_out_of_st_tuition_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AT1|Published out-of-state tuition 2019-20",
    ADD COLUMN publsd_out_of_st_tuition_2019_20 FLOAT COMMENT "PCCHG3AT1|Published out-of-state tuition 2019-20",
  ADD COLUMN publsd_out_st_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AF1|Published out-of-state fees 2019-20",
    ADD COLUMN publsd_out_st_fees_2019_20 FLOAT COMMENT "PCCHG3AF1|Published out-of-state fees 2019-20",
  ADD COLUMN publsd_out_st_tuition_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AY1|Published out-of-state tuition and fees 2019-20",
    ADD COLUMN publsd_out_st_tuition_fees_2019_20 FLOAT COMMENT "PCCHG3AY1|Published out-of-state tuition and fees 2019-20",
  ADD COLUMN publsd_out_st_tuition_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AT2|Published out-of-state tuition 2020-21",
    ADD COLUMN publsd_out_st_tuition_2020_21 FLOAT COMMENT "PCCHG3AT2|Published out-of-state tuition 2020-21",
  ADD COLUMN publsd_out_st_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AF2|Published out-of-state fees 2020-21",
    ADD COLUMN publsd_out_st_fees_2020_21 FLOAT COMMENT "PCCHG3AF2|Published out-of-state fees 2020-21",
  ADD COLUMN publsd_out_st_tuition_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AY2|Published out-of-state tuition and fees 2020-21",
    ADD COLUMN publsd_out_st_tuition_fees_2020_21 FLOAT COMMENT "PCCHG3AY2|Published out-of-state tuition and fees 2020-21",
  ADD COLUMN publsd_out_st_tuition_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AT3|Published out-of-state tuition 2021-22",
    ADD COLUMN publsd_out_st_tuition_2021_22 FLOAT COMMENT "PCCHG3AT3|Published out-of-state tuition 2021-22",
  ADD COLUMN publsd_out_st_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AF3|Published out-of-state fees 2021-22",
    ADD COLUMN publsd_out_st_fees_2021_22 FLOAT COMMENT "PCCHG3AF3|Published out-of-state fees 2021-22",
  ADD COLUMN publsd_out_st_tuition_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG3AY3|Published out-of-state tuition and fees 2021-22",
    ADD COLUMN publsd_out_st_tuition_fees_2021_22 FLOAT COMMENT "PCCHG3AY3|Published out-of-state tuition and fees 2021-22",
    ADD COLUMN publsd_out_st_tuition_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG3TGTD|Published out-of-state tuition 2021-22 guaranteed percent increase (if applicable)",
    ADD COLUMN publsd_out_st_fees_2021_22_gurntd_pct_inc FLOAT COMMENT "PCCHG3FGTD|Published out-of-state fees 2021-22 guaranteed percent increase (if applicable)",
  ADD COLUMN books_supplies_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4AY0|Books and supplies 2018-19",
    ADD COLUMN books_supplies_2018_19_ay FLOAT COMMENT "PCCHG4AY0|Books and supplies 2018-19",
  ADD COLUMN books_supplies_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4AY1|Books and supplies 2019-20",
    ADD COLUMN books_supplies_2019_20_ay FLOAT COMMENT "PCCHG4AY1|Books and supplies 2019-20",
  ADD COLUMN books_supplies_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4AY2|Books and supplies 2020-21",
    ADD COLUMN books_supplies_2020_21_ay FLOAT COMMENT "PCCHG4AY2|Books and supplies 2020-21",
  ADD COLUMN books_supplies_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4AY3|Books and supplies 2021-22",
    ADD COLUMN books_supplies_2021_22_ay FLOAT COMMENT "PCCHG4AY3|Books and supplies 2021-22",
  ADD COLUMN on_cmps_room_board_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5AY0|On campus, room and board 2018-19",
    ADD COLUMN on_cmps_room_board_2018_19_ay FLOAT COMMENT "PCCHG5AY0|On campus, room and board 2018-19",
  ADD COLUMN on_cmps_room_board_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5AY1|On campus, room and board 2019-20",
    ADD COLUMN on_cmps_room_board_2019_20_ay FLOAT COMMENT "PCCHG5AY1|On campus, room and board 2019-20",
  ADD COLUMN on_cmps_room_board_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5AY2|On campus, room and board 2020-21",
    ADD COLUMN on_cmps_room_board_2020_21_ay FLOAT COMMENT "PCCHG5AY2|On campus, room and board 2020-21",
  ADD COLUMN on_cmps_room_board_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5AY3|On campus, room and board 2021-22",
    ADD COLUMN on_cmps_room_board_2021_22_ay FLOAT COMMENT "PCCHG5AY3|On campus, room and board 2021-22",
  ADD COLUMN on_cmps_other_exp_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6AY0|On campus, other expenses 2018-19",
    ADD COLUMN on_cmps_other_exp_2018_19_ay FLOAT COMMENT "PCCHG6AY0|On campus, other expenses 2018-19",
  ADD COLUMN on_cmps_other_exp_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6AY1|On campus, other expenses 2019-20",
    ADD COLUMN on_cmps_other_exp_2019_20_ay FLOAT COMMENT "PCCHG6AY1|On campus, other expenses 2019-20",
  ADD COLUMN on_cmps_other_exp_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6AY2|On campus, other expenses 2020-21",
    ADD COLUMN on_cmps_other_exp_2020_21_ay FLOAT COMMENT "PCCHG6AY2|On campus, other expenses 2020-21",
  ADD COLUMN on_cmps_other_exp_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6AY3|On campus, other expenses 2021-22",
    ADD COLUMN on_cmps_other_exp_2021_22_ay FLOAT COMMENT "PCCHG6AY3|On campus, other expenses 2021-22",
  ADD COLUMN off_cmps_room_board_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7AY0|Off campus (not with family), room and board 2018-19",
    ADD COLUMN off_cmps_room_board_2018_19_ay FLOAT COMMENT "PCCHG7AY0|Off campus (not with family), room and board 2018-19",
  ADD COLUMN off_cmps_room_board_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7AY1|Off campus (not with family), room and board 2019-20",
    ADD COLUMN off_cmps_room_board_2019_20_ay FLOAT COMMENT "PCCHG7AY1|Off campus (not with family), room and board 2019-20",
  ADD COLUMN off_cmps_room_board_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7AY2|Off campus (not with family), room and board 2020-21",
    ADD COLUMN off_cmps_room_board_2020_21_ay FLOAT COMMENT "PCCHG7AY2|Off campus (not with family), room and board 2020-21",
  ADD COLUMN off_cmps_room_board_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7AY3|Off campus (not with family), room and board 2021-22",
    ADD COLUMN off_cmps_room_board_2021_22_ay FLOAT COMMENT "PCCHG7AY3|Off campus (not with family), room and board 2021-22",
  ADD COLUMN off_cmps_other_exp_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8AY0|Off campus (not with family), other expenses 2018-19",
    ADD COLUMN off_cmps_other_exp_2018_19_ay FLOAT COMMENT "PCCHG8AY0|Off campus (not with family), other expenses 2018-19",
  ADD COLUMN off_cmps_other_exp_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8AY1|Off campus (not with family), other expenses 2019-20",
    ADD COLUMN off_cmps_other_exp_2019_20_ay FLOAT COMMENT "PCCHG8AY1|Off campus (not with family), other expenses 2019-20",
  ADD COLUMN off_cmps_other_exp_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8AY2|Off campus (not with family), other expenses 2020-21",
    ADD COLUMN off_cmps_other_exp_2020_21_ay FLOAT COMMENT "PCCHG8AY2|Off campus (not with family), other expenses 2020-21",
  ADD COLUMN off_cmps_other_exp_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8AY3|Off campus (not with family), other expenses 2021-22",
    ADD COLUMN off_cmps_other_exp_2021_22_ay FLOAT COMMENT "PCCHG8AY3|Off campus (not with family), other expenses 2021-22",
  ADD COLUMN off_cmps_with_fam_other_exp_2018_19_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9AY0|Off campus (with family), other expenses 2018-19",
    ADD COLUMN off_cmps_with_fam_other_exp_2018_19_ay FLOAT COMMENT "PCCHG9AY0|Off campus (with family), other expenses 2018-19",
  ADD COLUMN off_cmps_with_fam_other_exp_2019_20_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9AY1|Off campus (with family), other expenses 2019-20",
    ADD COLUMN off_cmps_with_fam_other_exp_2019_20_ay FLOAT COMMENT "PCCHG9AY1|Off campus (with family), other expenses 2019-20",
  ADD COLUMN off_cmps_with_fam_other_exp_2020_21_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9AY2|Off campus (with family), other expenses 2020-21",
    ADD COLUMN off_cmps_with_fam_other_exp_2020_21_ay FLOAT COMMENT "PCCHG9AY2|Off campus (with family), other expenses 2020-21",
  ADD COLUMN off_cmps_with_fam_other_exp_2021_22_ay_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9AY3|Off campus (with family), other expenses 2021-22",
    ADD COLUMN off_cmps_with_fam_other_exp_2021_22_ay FLOAT COMMENT "PCCHG9AY3|Off campus (with family), other expenses 2021-22",
    ADD COLUMN cip_code_largest_program VARCHAR(7) COMMENT "PCCIPCODE1|CIP code of largest program",
  ADD COLUMN total_length_largest_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCIPLGTH1|Total length of largest program",
    ADD COLUMN total_length_largest_program FLOAT COMMENT "PCCIPLGTH1|Total length of largest program",
    ADD COLUMN largest_program_length_credit_clock SMALLINT COMMENT "PCPRGMSR1|Largest program measured in credit or clock hours",
  ADD COLUMN avg_months_complete_largest_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCMTHCMP1|Average number of months to complete largest program",
    ADD COLUMN avg_months_complete_largest_program FLOAT COMMENT "PCMTHCMP1|Average number of months to complete largest program",
  ADD COLUMN total_length_program_weeks_full_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCWKCMP1|Total length of program in weeks, as completed by a student attending full-time",
    ADD COLUMN total_length_program_weeks_full_time FLOAT COMMENT "PCWKCMP1|Total length of program in weeks, as completed by a student attending full-time",
  ADD COLUMN total_length_academic_year_credit_clock_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCLNAYHR1|Total length of academic year (as used to calculate your Pell budget) in clock or credit hours",
    ADD COLUMN total_length_academic_year_credit_clock FLOAT COMMENT "PCLNAYHR1|Total length of academic year (as used to calculate your Pell budget) in clock or credit hours",
  ADD COLUMN academic_year_length_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCLNAYWK1|Total length of academic year (as used to calculate your Pell budget) in weeks",
    ADD COLUMN academic_year_length FLOAT COMMENT "PCLNAYWK1|Total length of academic year (as used to calculate your Pell budget) in weeks",
  ADD COLUMN tuition_fees_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1PY0|Published tuition and fees 2018-19",
    ADD COLUMN tuition_fees_2018_19_py FLOAT COMMENT "PCCHG1PY0|Published tuition and fees 2018-19",
  ADD COLUMN tuition_fees_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1PY1|Published tuition and fees 2019-20",
    ADD COLUMN tuition_fees_2019_20_py FLOAT COMMENT "PCCHG1PY1|Published tuition and fees 2019-20",
  ADD COLUMN tuition_fees_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1PY2|Published tuition and fees 2020-21",
    ADD COLUMN tuition_fees_2020_21_py FLOAT COMMENT "PCCHG1PY2|Published tuition and fees 2020-21",
  ADD COLUMN tuition_fees_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG1PY3|Published tuition and fees 2021-22",
    ADD COLUMN tuition_fees_2021_22_py FLOAT COMMENT "PCCHG1PY3|Published tuition and fees 2021-22",
  ADD COLUMN books_supplies_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4PY0|Books and supplies 2018-19",
    ADD COLUMN books_supplies_2018_19_py FLOAT COMMENT "PCCHG4PY0|Books and supplies 2018-19",
  ADD COLUMN books_supplies_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4PY1|Books and supplies 2019-20",
    ADD COLUMN books_supplies_2019_20_py FLOAT COMMENT "PCCHG4PY1|Books and supplies 2019-20",
  ADD COLUMN books_supplies_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4PY2|Books and supplies 2020-21",
    ADD COLUMN books_supplies_2020_21_py FLOAT COMMENT "PCCHG4PY2|Books and supplies 2020-21",
  ADD COLUMN books_supplies_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG4PY3|Books and supplies 2021-22",
    ADD COLUMN books_supplies_2021_22_py FLOAT COMMENT "PCCHG4PY3|Books and supplies 2021-22",
  ADD COLUMN room_board_on_cmps_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5PY0|On campus, room and board 2018-19",
    ADD COLUMN room_board_on_cmps_2018_19_py FLOAT COMMENT "PCCHG5PY0|On campus, room and board 2018-19",
  ADD COLUMN room_board_on_cmps_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5PY1|On campus, room and board 2019-20",
    ADD COLUMN room_board_on_cmps_2019_20_py FLOAT COMMENT "PCCHG5PY1|On campus, room and board 2019-20",
  ADD COLUMN room_board_on_cmps_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5PY2|On campus, room and board 2020-21",
    ADD COLUMN room_board_on_cmps_2020_21_py FLOAT COMMENT "PCCHG5PY2|On campus, room and board 2020-21",
  ADD COLUMN room_board_on_cmps_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG5PY3|On campus, room and board 2021-22",
    ADD COLUMN room_board_on_cmps_2021_22_py FLOAT COMMENT "PCCHG5PY3|On campus, room and board 2021-22",
  ADD COLUMN other_exp_on_cmps_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6PY0|On campus, other expenses 2018-19",
    ADD COLUMN other_exp_on_cmps_2018_19_py FLOAT COMMENT "PCCHG6PY0|On campus, other expenses 2018-19",
  ADD COLUMN other_exp_on_cmps_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6PY1|On campus, other expenses 2019-20",
    ADD COLUMN other_exp_on_cmps_2019_20_py FLOAT COMMENT "PCCHG6PY1|On campus, other expenses 2019-20",
  ADD COLUMN other_exp_on_cmps_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6PY2|On campus, other expenses 2020-21",
    ADD COLUMN other_exp_on_cmps_2020_21_py FLOAT COMMENT "PCCHG6PY2|On campus, other expenses 2020-21",
  ADD COLUMN other_exp_on_cmps_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG6PY3|On campus, other expenses 2021-22",
    ADD COLUMN other_exp_on_cmps_2021_22_py FLOAT COMMENT "PCCHG6PY3|On campus, other expenses 2021-22",
  ADD COLUMN room_board_off_cmps_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7PY0|Off campus (not with family), room and board 2018-19",
    ADD COLUMN room_board_off_cmps_2018_19_py FLOAT COMMENT "PCCHG7PY0|Off campus (not with family), room and board 2018-19",
  ADD COLUMN room_board_off_cmps_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7PY1|Off campus (not with family), room and board 2019-20",
    ADD COLUMN room_board_off_cmps_2019_20_py FLOAT COMMENT "PCCHG7PY1|Off campus (not with family), room and board 2019-20",
  ADD COLUMN room_board_off_cmps_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7PY2|Off campus (not with family), room and board 2020-21",
    ADD COLUMN room_board_off_cmps_2020_21_py FLOAT COMMENT "PCCHG7PY2|Off campus (not with family), room and board 2020-21",
  ADD COLUMN off_cmps_room_board_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG7PY3|Off campus (not with family), room and board 2021-22",
    ADD COLUMN off_cmps_room_board_2021_22_py FLOAT COMMENT "PCCHG7PY3|Off campus (not with family), room and board 2021-22",
  ADD COLUMN off_cmps_other_exp_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8PY0|Off campus (not with family), other expenses 2018-19",
    ADD COLUMN off_cmps_other_exp_2018_19_py FLOAT COMMENT "PCCHG8PY0|Off campus (not with family), other expenses 2018-19",
  ADD COLUMN off_cmps_other_exp_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8PY1|Off campus (not with family), other expenses 2019-20",
    ADD COLUMN off_cmps_other_exp_2019_20_py FLOAT COMMENT "PCCHG8PY1|Off campus (not with family), other expenses 2019-20",
  ADD COLUMN off_cmps_other_exp_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8PY2|Off campus (not with family), other expenses 2020-21",
    ADD COLUMN off_cmps_other_exp_2020_21_py FLOAT COMMENT "PCCHG8PY2|Off campus (not with family), other expenses 2020-21",
  ADD COLUMN off_cmps_other_exp_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG8PY3|Off campus (not with family), other expenses 2021-22",
    ADD COLUMN off_cmps_other_exp_2021_22_py FLOAT COMMENT "PCCHG8PY3|Off campus (not with family), other expenses 2021-22",
  ADD COLUMN off_cmps_with_fam_other_exp_2018_19_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9PY0|Off campus (with family), other expenses 2018-19",
    ADD COLUMN off_cmps_with_fam_other_exp_2018_19_py FLOAT COMMENT "PCCHG9PY0|Off campus (with family), other expenses 2018-19",
  ADD COLUMN off_cmps_with_fam_other_exp_2019_20_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9PY1|Off campus (with family), other expenses 2019-20",
    ADD COLUMN off_cmps_with_fam_other_exp_2019_20_py FLOAT COMMENT "PCCHG9PY1|Off campus (with family), other expenses 2019-20",
  ADD COLUMN off_cmps_with_fam_other_exp_2020_21_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9PY2|Off campus (with family), other expenses 2020-21",
    ADD COLUMN off_cmps_with_fam_other_exp_2020_21_py FLOAT COMMENT "PCCHG9PY2|Off campus (with family), other expenses 2020-21",
  ADD COLUMN off_cmps_with_fam_other_exp_2021_22_py_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PCCHG9PY3|Off campus (with family), other expenses 2021-22",
    ADD COLUMN off_cmps_with_fam_other_exp_2021_22_py FLOAT COMMENT "PCCHG9PY3|Off campus (with family), other expenses 2021-22";