ALTER TABLE institution_ic_vocational_charge 
    ADD COLUMN num_programs SMALLINT COMMENT "PRGMOFR|Number of programs offered",
    ADD COLUMN cip_code_1st_program FLOAT COMMENT "CIPCODE1|CIP code of largest program",
  ADD COLUMN tuition_fees_1st_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT1|Tuition and fees 2021-22 (institutions with no full-time, first-time, undergraduate students)",
    ADD COLUMN tuition_fees_1st_program FLOAT COMMENT "CIPTUIT1|Tuition and fees 2021-22 (institutions with no full-time, first-time, undergraduate students)",
  ADD COLUMN books_supplies_1st_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP1|Books and supplies 2021-22 (institutions with no full-time, first-time, undergraduate students)",
    ADD COLUMN books_supplies_1st_program FLOAT COMMENT "CIPSUPP1|Books and supplies 2021-22 (institutions with no full-time, first-time, undergraduate students)",
  ADD COLUMN length_1st_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH1|Total length of largest program",
    ADD COLUMN length_1st_program SMALLINT COMMENT "CIPLGTH1|Total length of largest program",
    ADD COLUMN measure_1st_program SMALLINT COMMENT "PRGMSR1|Largest program measured in credit or clock hours",
  ADD COLUMN months_complete_1st_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP1|Average number of months to complete largest program",
    ADD COLUMN months_complete_1st_program SMALLINT COMMENT "MTHCMP1|Average number of months to complete largest program",
  ADD COLUMN length_program_fulltime_weeks_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "WKCMP1|Total length of program in weeks, as completed by a student attending full-time",
    ADD COLUMN length_program_fulltime_weeks FLOAT COMMENT "WKCMP1|Total length of program in weeks, as completed by a student attending full-time",
  ADD COLUMN length_academic_year_clock_credit_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LNAYHR1|Total length of academic year (as used to calculate your Pell budget) in clock or credit hours",
    ADD COLUMN length_academic_year_clock_credit FLOAT COMMENT "LNAYHR1|Total length of academic year (as used to calculate your Pell budget) in clock or credit hours",
  ADD COLUMN length_academic_year_weeks_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LNAYWK1|Total length of academic year (as used to calculate your Pell budget) in weeks",
    ADD COLUMN length_academic_year_weeks FLOAT COMMENT "LNAYWK1|Total length of academic year (as used to calculate your Pell budget) in weeks",
  ADD COLUMN tuition_fees_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG1PY0|Published tuition and fees 2018-19",
    ADD COLUMN tuition_fees_2018_19 FLOAT COMMENT "CHG1PY0|Published tuition and fees 2018-19",
  ADD COLUMN tuition_fees_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG1PY1|Published tuition and fees 2019-20",
    ADD COLUMN tuition_fees_2019_20 FLOAT COMMENT "CHG1PY1|Published tuition and fees 2019-20",
  ADD COLUMN tuition_fees_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG1PY2|Published tuition and fees 2020-21",
    ADD COLUMN tuition_fees_2020_21 FLOAT COMMENT "CHG1PY2|Published tuition and fees 2020-21",
  ADD COLUMN tuition_fees_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG1PY3|Published tuition and fees 2021-22",
    ADD COLUMN tuition_fees_2021_22 FLOAT COMMENT "CHG1PY3|Published tuition and fees 2021-22",
  ADD COLUMN books_supplies_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG4PY0|Books and supplies 2018-19",
    ADD COLUMN books_supplies_2018_19 FLOAT COMMENT "CHG4PY0|Books and supplies 2018-19",
  ADD COLUMN books_supplies_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG4PY1|Books and supplies 2019-20",
    ADD COLUMN books_supplies_2019_20 FLOAT COMMENT "CHG4PY1|Books and supplies 2019-20",
  ADD COLUMN books_supplies_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG4PY2|Books and supplies 2020-21",
    ADD COLUMN books_supplies_2020_21 FLOAT COMMENT "CHG4PY2|Books and supplies 2020-21",
  ADD COLUMN books_supplies_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG4PY3|Books and supplies 2021-22",
    ADD COLUMN books_supplies_2021_22 FLOAT COMMENT "CHG4PY3|Books and supplies 2021-22",
  ADD COLUMN room_board_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG5PY0|On campus, room and board 2018-19",
    ADD COLUMN room_board_2018_19 FLOAT COMMENT "CHG5PY0|On campus, room and board 2018-19",
  ADD COLUMN on_cmps_room_board_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG5PY1|On campus, room and board 2019-20",
    ADD COLUMN on_cmps_room_board_2019_20 FLOAT COMMENT "CHG5PY1|On campus, room and board 2019-20",
  ADD COLUMN on_cmps_room_board_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG5PY2|On campus, room and board 2020-21",
    ADD COLUMN on_cmps_room_board_2020_21 FLOAT COMMENT "CHG5PY2|On campus, room and board 2020-21",
  ADD COLUMN on_cmps_room_board_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG5PY3|On campus, room and board 2021-22",
    ADD COLUMN on_cmps_room_board_2021_22 FLOAT COMMENT "CHG5PY3|On campus, room and board 2021-22",
  ADD COLUMN on_cmps_other_exp_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG6PY0|On campus, other expenses 2018-19",
    ADD COLUMN on_cmps_other_exp_2018_19 FLOAT COMMENT "CHG6PY0|On campus, other expenses 2018-19",
  ADD COLUMN on_cmps_other_exp_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG6PY1|On campus, other expenses 2019-20",
    ADD COLUMN on_cmps_other_exp_2019_20 FLOAT COMMENT "CHG6PY1|On campus, other expenses 2019-20",
  ADD COLUMN on_cmps_other_exp_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG6PY2|On campus, other expenses 2020-21",
    ADD COLUMN on_cmps_other_exp_2020_21 FLOAT COMMENT "CHG6PY2|On campus, other expenses 2020-21",
  ADD COLUMN on_cmps_other_exp_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG6PY3|On campus, other expenses 2021-22",
    ADD COLUMN on_cmps_other_exp_2021_22 FLOAT COMMENT "CHG6PY3|On campus, other expenses 2021-22",
  ADD COLUMN off_cmps_room_board_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG7PY0|Off campus (not with family), room and board 2018-19",
    ADD COLUMN off_cmps_room_board_2018_19 FLOAT COMMENT "CHG7PY0|Off campus (not with family), room and board 2018-19",
  ADD COLUMN off_cmps_room_board_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG7PY1|Off campus (not with family), room and board 2019-20",
    ADD COLUMN off_cmps_room_board_2019_20 FLOAT COMMENT "CHG7PY1|Off campus (not with family), room and board 2019-20",
  ADD COLUMN off_cmps_room_board_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG7PY2|Off campus (not with family), room and board 2020-21",
    ADD COLUMN off_cmps_room_board_2020_21 FLOAT COMMENT "CHG7PY2|Off campus (not with family), room and board 2020-21",
  ADD COLUMN off_cmps_room_board_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG7PY3|Off campus (not with family), room and board 2021-22",
    ADD COLUMN off_cmps_room_board_2021_22 FLOAT COMMENT "CHG7PY3|Off campus (not with family), room and board 2021-22",
  ADD COLUMN off_cmps_other_exp_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG8PY0|Off campus (not with family), other expenses 2018-19",
    ADD COLUMN off_cmps_other_exp_2018_19 FLOAT COMMENT "CHG8PY0|Off campus (not with family), other expenses 2018-19",
  ADD COLUMN off_cmps_other_exp_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG8PY1|Off campus (not with family), other expenses 2019-20",
    ADD COLUMN off_cmps_other_exp_2019_20 FLOAT COMMENT "CHG8PY1|Off campus (not with family), other expenses 2019-20",
  ADD COLUMN off_cmps_other_exp_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG8PY2|Off campus (not with family), other expenses 2020-21",
    ADD COLUMN off_cmps_other_exp_2020_21 FLOAT COMMENT "CHG8PY2|Off campus (not with family), other expenses 2020-21",
  ADD COLUMN off_cmps_other_exp_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG8PY3|Off campus (not with family), other expenses 2021-22",
    ADD COLUMN off_cmps_other_exp_2021_22 FLOAT COMMENT "CHG8PY3|Off campus (not with family), other expenses 2021-22",
  ADD COLUMN off_cmps_with_fam_other_exp_2018_19_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG9PY0|Off campus (with family), other expenses 2018-19",
    ADD COLUMN off_cmps_with_fam_other_exp_2018_19 FLOAT COMMENT "CHG9PY0|Off campus (with family), other expenses 2018-19",
  ADD COLUMN off_cmps_with_fam_other_exp_2019_20_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG9PY1|Off campus (with family), other expenses 2019-20",
    ADD COLUMN off_cmps_with_fam_other_exp_2019_20 FLOAT COMMENT "CHG9PY1|Off campus (with family), other expenses 2019-20",
  ADD COLUMN off_cmps_with_fam_other_exp_2020_21_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG9PY2|Off campus (with family), other expenses 2020-21",
    ADD COLUMN off_cmps_with_fam_other_exp_2020_21 FLOAT COMMENT "CHG9PY2|Off campus (with family), other expenses 2020-21",
  ADD COLUMN off_cmps_with_fam_other_exp_2021_22_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CHG9PY3|Off campus (with family), other expenses 2021-22",
    ADD COLUMN off_cmps_with_fam_other_exp_2021_22 FLOAT COMMENT "CHG9PY3|Off campus (with family), other expenses 2021-22",
    ADD COLUMN cip_code_2nd_program FLOAT COMMENT "CIPCODE2|CIP code of 2nd largest program",
  ADD COLUMN tuition_fees_2nd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT2|Tuition and fees of 2nd largest program",
    ADD COLUMN tuition_fees_2nd_program FLOAT COMMENT "CIPTUIT2|Tuition and fees of 2nd largest program",
  ADD COLUMN books_supplies_2nd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP2|Cost of books and supplies of 2nd largest program",
    ADD COLUMN books_supplies_2nd_program FLOAT COMMENT "CIPSUPP2|Cost of books and supplies of 2nd largest program",
  ADD COLUMN length_2nd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH2|Length of 2nd largest program",
    ADD COLUMN length_2nd_program FLOAT COMMENT "CIPLGTH2|Length of 2nd largest program",
    ADD COLUMN measure_2nd_program SMALLINT COMMENT "PRGMSR2|2nd largest program measured in credit or clock hours",
  ADD COLUMN months_to_complete_2nd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP2|Number of months to complete 2nd largest program",
    ADD COLUMN months_to_complete_2nd_program FLOAT COMMENT "MTHCMP2|Number of months to complete 2nd largest program",
    ADD COLUMN cip_code_3rd_program FLOAT COMMENT "CIPCODE3|CIP code of 3rd largest program",
  ADD COLUMN tuition_fees_3rd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT3|Tuition and fees of 3rd largest program",
    ADD COLUMN tuition_fees_3rd_program FLOAT COMMENT "CIPTUIT3|Tuition and fees of 3rd largest program",
  ADD COLUMN books_supplies_3rd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP3|Cost of books and supplies of 3rd largest program",
    ADD COLUMN books_supplies_3rd_program FLOAT COMMENT "CIPSUPP3|Cost of books and supplies of 3rd largest program",
  ADD COLUMN length_3rd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH3|Length of 3rd largest program",
    ADD COLUMN length_3rd_program FLOAT COMMENT "CIPLGTH3|Length of 3rd largest program",
    ADD COLUMN measure_3rd_program SMALLINT COMMENT "PRGMSR3|3rd largest program measured in credit or clock hours",
  ADD COLUMN months_to_complete_3rd_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP3|Number of months to complete 3rd largest program",
    ADD COLUMN months_to_complete_3rd_program FLOAT COMMENT "MTHCMP3|Number of months to complete 3rd largest program",
    ADD COLUMN cip_code_4th_program FLOAT COMMENT "CIPCODE4|CIP code of 4th largest program",
  ADD COLUMN tuition_fees_4th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT4|Tuition and fees of 4th largest program",
    ADD COLUMN tuition_fees_4th_program FLOAT COMMENT "CIPTUIT4|Tuition and fees of 4th largest program",
  ADD COLUMN books_supplies_4th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP4|Cost of books and supplies of 4th largest program",
    ADD COLUMN books_supplies_4th_program FLOAT COMMENT "CIPSUPP4|Cost of books and supplies of 4th largest program",
  ADD COLUMN length_4th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH4|Length of 4th largest program",
    ADD COLUMN length_4th_program FLOAT COMMENT "CIPLGTH4|Length of 4th largest program",
    ADD COLUMN measure_4th_program SMALLINT COMMENT "PRGMSR4|4th largest program measured in credit or clock hours",
  ADD COLUMN months_to_complete_4th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP4|Number of months to complete 4th largest program",
    ADD COLUMN months_to_complete_4th_program FLOAT COMMENT "MTHCMP4|Number of months to complete 4th largest program",
    ADD COLUMN cip_code_5th_program FLOAT COMMENT "CIPCODE5|CIP code of 5th largest program",
  ADD COLUMN tuition_fees_5th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT5|Tuition and fees of 5th largest program",
    ADD COLUMN tuition_fees_5th_program FLOAT COMMENT "CIPTUIT5|Tuition and fees of 5th largest program",
  ADD COLUMN books_supplies_5th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP5|Cost of books and supplies of 5th largest program",
    ADD COLUMN books_supplies_5th_program FLOAT COMMENT "CIPSUPP5|Cost of books and supplies of 5th largest program",
  ADD COLUMN length_5th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH5|Length of 5th largest program",
    ADD COLUMN length_5th_program FLOAT COMMENT "CIPLGTH5|Length of 5th largest program",
    ADD COLUMN measure_5th_program SMALLINT COMMENT "PRGMSR5|5th largest program measured in credit or clock hours",
  ADD COLUMN months_to_complete_5th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP5|Number of months to complete 5th largest program",
    ADD COLUMN months_to_complete_5th_program FLOAT COMMENT "MTHCMP5|Number of months to complete 5th largest program",
    ADD COLUMN cip_code_6th_program FLOAT COMMENT "CIPCODE6|CIP code of 6th largest program",
  ADD COLUMN tuition_fees_6th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPTUIT6|Tuition and fees of 6th largest program",
    ADD COLUMN tuition_fees_6th_program FLOAT COMMENT "CIPTUIT6|Tuition and fees of 6th largest program",
  ADD COLUMN books_supplies_6th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPSUPP6|Cost of books and supplies of 6th largest program",
    ADD COLUMN books_supplies_6th_program FLOAT COMMENT "CIPSUPP6|Cost of books and supplies of 6th largest program",
  ADD COLUMN length_6th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "CIPLGTH6|Length of 6th largest program",
    ADD COLUMN length_6th_program FLOAT COMMENT "CIPLGTH6|Length of 6th largest program",
    ADD COLUMN measure_6th_program SMALLINT COMMENT "PRGMSR6|6th largest program measured in credit or clock hours",
  ADD COLUMN months_to_complete_6th_program_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "MTHCMP6|Number of months to complete 6th largest program",
    ADD COLUMN months_to_complete_6th_program FLOAT COMMENT "MTHCMP6|Number of months to complete 6th largest program";