ALTER TABLE institution_adm_consideration 
    ADD COLUMN secondary_school_gpa TINYINT COMMENT "ADMCON1|Secondary school GPA",
    ADD COLUMN secondary_school_rank TINYINT COMMENT "ADMCON2|Secondary school rank",
    ADD COLUMN secondary_school_record TINYINT COMMENT "ADMCON3|Secondary school record",
    ADD COLUMN completion_college_prep_program TINYINT COMMENT "ADMCON4|Completion of college-preparatory program",
    ADD COLUMN recommendations TINYINT COMMENT "ADMCON5|Recommendations",
    ADD COLUMN formal_demonstration_competencies TINYINT COMMENT "ADMCON6|Formal demonstration of competencies",
    ADD COLUMN admission_test_scores TINYINT COMMENT "ADMCON7|Admission test scores",
    ADD COLUMN toefl TINYINT COMMENT "ADMCON8|TOEFL (Test of English as a Foreign Language",
    ADD COLUMN other_test TINYINT COMMENT "ADMCON9|Other Test (Wonderlic, WISC-III, etc.)",
  ADD COLUMN applicants_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "APPLCN|Applicants total",
    ADD COLUMN applicants_total MEDIUMINT COMMENT "APPLCN|Applicants total",
  ADD COLUMN applicants_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "APPLCNM|Applicants men",
    ADD COLUMN applicants_men MEDIUMINT COMMENT "APPLCNM|Applicants men",
  ADD COLUMN applicants_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "APPLCNW|Applicants women",
    ADD COLUMN applicants_women MEDIUMINT COMMENT "APPLCNW|Applicants women",
  ADD COLUMN admissions_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ADMSSN|Admissions total",
    ADD COLUMN admissions_total FLOAT COMMENT "ADMSSN|Admissions total",
  ADD COLUMN admissions_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ADMSSNM|Admissions men",
    ADD COLUMN admissions_men FLOAT COMMENT "ADMSSNM|Admissions men",
  ADD COLUMN admissions_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ADMSSNW|Admissions women",
    ADD COLUMN admissions_women FLOAT COMMENT "ADMSSNW|Admissions women",
  ADD COLUMN enrolled_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLT|Enrolled total",
    ADD COLUMN enrolled_total FLOAT COMMENT "ENRLT|Enrolled total",
  ADD COLUMN enrolled_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLM|Enrolled  men",
    ADD COLUMN enrolled_men FLOAT COMMENT "ENRLM|Enrolled  men",
  ADD COLUMN enrolled_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLW|Enrolled  women",
    ADD COLUMN enrolled_women FLOAT COMMENT "ENRLW|Enrolled  women",
  ADD COLUMN enrolled_full_time_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLFT|Enrolled full time total",
    ADD COLUMN enrolled_full_time_total FLOAT COMMENT "ENRLFT|Enrolled full time total",
  ADD COLUMN enrolled_fulltime_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLFTM|Enrolled full time men",
    ADD COLUMN enrolled_fulltime_men FLOAT COMMENT "ENRLFTM|Enrolled full time men",
  ADD COLUMN enrolled_fulltime_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLFTW|Enrolled full time women",
    ADD COLUMN enrolled_fulltime_women FLOAT COMMENT "ENRLFTW|Enrolled full time women",
  ADD COLUMN enrolled_parttime_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLPT|Enrolled part time total",
    ADD COLUMN enrolled_parttime_total FLOAT COMMENT "ENRLPT|Enrolled part time total",
  ADD COLUMN enrolled_parttime_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLPTM|Enrolled part time men",
    ADD COLUMN enrolled_parttime_men FLOAT COMMENT "ENRLPTM|Enrolled part time men",
  ADD COLUMN enrolled_parttime_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ENRLPTW|Enrolled part time women",
    ADD COLUMN enrolled_parttime_women FLOAT COMMENT "ENRLPTW|Enrolled part time women",
  ADD COLUMN num_firsttime_sat_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATNUM|Number of first-time degree/certificate-seeking students submitting SAT scores",
    ADD COLUMN num_firsttime_sat FLOAT COMMENT "SATNUM|Number of first-time degree/certificate-seeking students submitting SAT scores",
  ADD COLUMN percent_firsttime_sat_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATPCT|Percent of first-time degree/certificate-seeking students submitting SAT scores",
    ADD COLUMN percent_firsttime_sat FLOAT COMMENT "SATPCT|Percent of first-time degree/certificate-seeking students submitting SAT scores",
  ADD COLUMN num_firsttime_act_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTNUM|Number of first-time degree/certificate-seeking students submitting ACT scores",
    ADD COLUMN num_firsttime_act FLOAT COMMENT "ACTNUM|Number of first-time degree/certificate-seeking students submitting ACT scores",
  ADD COLUMN percent_firsttime_act_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTPCT|Percent of first-time degree/certificate-seeking students submitting ACT scores",
    ADD COLUMN percent_firsttime_act FLOAT COMMENT "ACTPCT|Percent of first-time degree/certificate-seeking students submitting ACT scores",
  ADD COLUMN sat_ebrw_25th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATVR25|SAT Evidence-Based Reading and Writing 25th percentile score",
    ADD COLUMN sat_ebrw_25th FLOAT COMMENT "SATVR25|SAT Evidence-Based Reading and Writing 25th percentile score",
  ADD COLUMN sat_ebrw_75th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATVR75|SAT Evidence-Based Reading and Writing 75th percentile score",
    ADD COLUMN sat_ebrw_75th FLOAT COMMENT "SATVR75|SAT Evidence-Based Reading and Writing 75th percentile score",
  ADD COLUMN sat_math_25th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATMT25|SAT Math 25th percentile score",
    ADD COLUMN sat_math_25th FLOAT COMMENT "SATMT25|SAT Math 25th percentile score",
  ADD COLUMN sat_math_75th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SATMT75|SAT Math 75th percentile score",
    ADD COLUMN sat_math_75th FLOAT COMMENT "SATMT75|SAT Math 75th percentile score",
  ADD COLUMN act_composite_25th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTCM25|ACT Composite 25th percentile score",
    ADD COLUMN act_composite_25th FLOAT COMMENT "ACTCM25|ACT Composite 25th percentile score",
  ADD COLUMN act_composite_75th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTCM75|ACT Composite 75th percentile score",
    ADD COLUMN act_composite_75th FLOAT COMMENT "ACTCM75|ACT Composite 75th percentile score",
  ADD COLUMN act_english_25th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTEN25|ACT English 25th percentile score",
    ADD COLUMN act_english_25th FLOAT COMMENT "ACTEN25|ACT English 25th percentile score",
  ADD COLUMN act_english_75th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTEN75|ACT English 75th percentile score",
    ADD COLUMN act_english_75th FLOAT COMMENT "ACTEN75|ACT English 75th percentile score",
  ADD COLUMN act_math_25th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTMT25|ACT Math 25th percentile score",
    ADD COLUMN act_math_25th FLOAT COMMENT "ACTMT25|ACT Math 25th percentile score",
  ADD COLUMN act_math_75th_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "ACTMT75|ACT Math 75th percentile score",
    ADD COLUMN act_math_75th FLOAT COMMENT "ACTMT75|ACT Math 75th percentile score";