
        ALTER TABLE institution_ic_offerings 
            ADD FOREIGN KEY (inst_id) REFERENCES institution(inst_id), 
            ADD CHECK (occupational IN (1, 0, -1)), 
            ADD CHECK (academic IN (1, 0, -1)), 
            ADD CHECK (continuing_professional IN (1, 0, -1, -2)), 
            ADD CHECK (recreational_or_avocational IN (1, 0, -1)), 
            ADD CHECK (adult_basic_remedial_or_high_school_equivalent IN (1, 0, -1)), 
            ADD CHECK (secondary IN (1, 0, -1)), 
            ADD CHECK (inst_control_affiliation IN (1, 2, 3, 4, -1)), 
            ADD FOREIGN KEY (primary_public_control) REFERENCES institution_xref_primary_public_control(Codevalue), 
            ADD FOREIGN KEY (secondary_public_control) REFERENCES institution_xref_secondary_public_control(Codevalue), 
            ADD FOREIGN KEY (religious_affiliation) REFERENCES institution_xref_religious_affiliation(Codevalue), 
            ADD CHECK (cert_lt_1yr IN (1, 0, -1)), 
            ADD CHECK (cert_lt_12wks IN (1, 0, -1)), 
            ADD CHECK (cert_12wks_lt_1yr IN (1, 0, -1)), 
            ADD CHECK (cert_1yr_lt_2yr IN (1, 0, -1)), 
            ADD CHECK (associates_degree IN (1, 0, -1)), 
            ADD CHECK (cert_2yr_lt_4yr IN (1, 0, -1)), 
            ADD CHECK (bachelors_degree IN (1, 0, -1, -2)), 
            ADD CHECK (postbacc_cert IN (1, 0, -1, -2)), 
            ADD CHECK (masters_degree IN (1, 0, -1, -2)), 
            ADD CHECK (post_masters_cert IN (1, 0, -1, -2)), 
            ADD CHECK (other_degree IN (1, 0, -1)), 
            ADD CHECK (doctors_research_scholarship IN (1, 0, -1, -2)), 
            ADD CHECK (doctors_professional_practice IN (1, 0, -1, -2)), 
            ADD CHECK (doctors_other IN (1, 0, -1, -2)), 
            ADD CHECK (calendar_system IN (1, 2, 3, 4, 5, 6, 7, -2)), 
            ADD CHECK (fulltime_undergrad_enrolled IN (1, 2, -2)), 
            ADD CHECK (fulltime_firsttime_undergrad_enrolled IN (1, 2, -2)), 
            ADD CHECK (fulltime_grad_enrolled IN (1, 2, -2, -1)), 
            ADD CHECK (parttime_undergrad_enrolled IN (1, 2, -2)), 
            ADD CHECK (part_time_deg_cert_undergrad_enrolled IN (1, 2, -2)), 
            ADD CHECK (part_time_grad_enrolled IN (1, 2, -2, -1)), 
            ADD CHECK (doctors_prof_practice_enrolled IN (1, 2, -2, -1)), 
            ADD CHECK (doctors_prof_practice_enrolled_first_prof IN (1, 2, -2, -1)), 
            ADD CHECK (open_admission_policy IN (1, 2, -1, -2)), 
            ADD CHECK (yellow_ribbon_program IN (1, 0, -1, -2)), 
            ADD CHECK (credit_military_training IN (1, 0, -1, -2)), 
            ADD CHECK (veteran_support_contact IN (1, 0, -1, -2)), 
            ADD CHECK (student_veteran_org IN (1, 0, -1, -2)), 
            ADD CHECK (servicemembers_opportunity_colleges IN (1, 0, -1, -2)), 
            ADD CHECK (services_not_available_veterans IN (1, 0, -1, -2)), 
            ADD CHECK (dual_enrollment IN (1, 0, -1, -2)), 
            ADD CHECK (credit_life_experiences IN (1, 0, -1, -2)), 
            ADD CHECK (ap_credits IN (1, 0, -1, -2)), 
            ADD CHECK (no_dual_credit_ap_life_credits IN (1, 0, -1, -2)), 
            ADD CHECK (rotc IN (1, 0, -1, -2)), 
            ADD CHECK (rotc_army IN (1, 0, -1, -2)), 
            ADD CHECK (rotc_navy IN (1, 0, -1, -2)), 
            ADD CHECK (rotc_air_force IN (1, 0, -1, -2)), 
            ADD CHECK (study_abroad IN (1, 0, -1, -2)), 
            ADD CHECK (weekend_evening_college IN (1, 0, -1, -2)), 
            ADD CHECK (teacher_cert_below_postsecondary IN (1, 0, -1, -2)), 
            ADD CHECK (teacher_cert_specialization IN (1, 0, -1, -2)), 
            ADD CHECK (teacher_cert_prep_another_inst IN (1, 0, -1, -2)), 
            ADD CHECK (teacher_cert_approved_state IN (1, 0, -1, -2)), 
            ADD CHECK (no_special_learning_opportunities IN (1, 0, -1, -2)), 
            ADD CHECK (college_level_work_required IN (1, 2, 3, 4, 5, 6, 7, 8, -1, -2)), 
            ADD CHECK (remedial_services IN (1, 0, -1, -2)), 
            ADD CHECK (academic_career_counseling IN (1, 0, -1, -2)), 
            ADD CHECK (employment_services_students IN (1, 0, -1, -2)), 
            ADD CHECK (placement_services_completers IN (1, 0, -1, -2)), 
            ADD CHECK (on_campus_daycare IN (1, 0, -1, -2)), 
            ADD CHECK (no_services_offered IN (1, 0, -1, -2)), 
            ADD CHECK (library_physical_facilities IN (1, 0, -1, -2)), 
            ADD CHECK (library_printed_materials IN (1, 0, -1, -2)), 
            ADD CHECK (library_digital_resources IN (1, 0, -1, -2)), 
            ADD CHECK (library_staff_trained IN (1, 0, -1, -2)), 
            ADD CHECK (library_hours IN (1, 0, -1, -2)), 
            ADD CHECK (library_shared_collections IN (1, 0, -1, -2)), 
            ADD CHECK (no_library_services IN (1, 0, -1, -2)), 
            ADD CHECK (alternative_tuition_plans IN (1, 2, -1, -2)), 
            ADD CHECK (tuition_guaranteed_plan IN (1, 0, -1, -2)), 
            ADD CHECK (prepaid_tuition_plan IN (1, 0, -1, -2)), 
            ADD CHECK (tuition_payment_plan IN (1, 0, -1, -2)), 
            ADD CHECK (other_tuition_plan IN (1, 0, -1, -2)), 
            ADD CHECK (undergrad_distance_courses IN (1, 0, -1, -2)), 
            ADD CHECK (undergrad_distance_programs IN (1, 0, -1, -2)), 
            ADD CHECK (no_undergrad_distance IN (1, 0, -1, -2)), 
            ADD CHECK (grad_distance_courses IN (1, 0, -1, -2)), 
            ADD CHECK (grad_distance_programs IN (1, 0, -1, -2)), 
            ADD CHECK (no_grad_distance IN (1, 0, -1, -2)), 
            ADD CHECK (distance_courses IN (1, 0, -1, -2)), 
            ADD CHECK (distance_programs IN (1, 0, -1, -2)), 
            ADD CHECK (undergrad_distance_offered IN (1, 0, -1, -2)), 
            ADD CHECK (grad_distance_offered IN (1, 0, -1, -2)), 
            ADD CHECK (no_distance_opportunities IN (1, 0, -1, -2)), 
            ADD CHECK (all_distance_programs IN (1, 2, -1, -2)), 
            ADD CHECK (percent_students_disabilities IN (1, 2, -1, -2)), 
            ADD CHECK (required_on_campus_residence IN (1, 2, -1, -2)), 
            ADD CHECK (tuition_charge_varies IN (1, 2, -1, -2)), 
            ADD CHECK (on_campus_housing IN (1, 2, -1, -2)), 
            ADD CHECK (meal_plan IN (1, 2, 3, -1, -2)), 
            ADD CHECK (nat_ath_assoc IN (1, 2, -1, -2)), 
            ADD CHECK (ncaa_member IN (1, 0, -1, -2)), 
            ADD CHECK (naia_member IN (1, 0, -1, -2)), 
            ADD CHECK (njcaa_member IN (1, 0, -1, -2)), 
            ADD CHECK (nscaa_member IN (1, 0, -1, -2)), 
            ADD CHECK (nccaa_member IN (1, 0, -1, -2)), 
            ADD CHECK (other_nat_ath_assoc IN (1, 0, -1, -2)), 
            ADD CHECK (ncaa_football_member IN (1, 2, -1, -2)), 
            ADD FOREIGN KEY (ncaa_football_conf_num) REFERENCES institution_xref_ncaa_football_conf_num(Codevalue), 
            ADD CHECK (ncaa_basketball_member IN (1, 2, -1, -2)), 
            ADD FOREIGN KEY (ncaa_basketball_conf_num) REFERENCES institution_xref_ncaa_basketball_conf_num(Codevalue), 
            ADD CHECK (ncaa_baseball_member IN (1, 2, -1, -2)), 
            ADD FOREIGN KEY (ncaa_baseball_conf_num) REFERENCES institution_xref_ncaa_baseball_conf_num(Codevalue), 
            ADD CHECK (ncaa_track_member IN (1, 2, -1, -2)), 
            ADD FOREIGN KEY (ncaa_track_conf_num) REFERENCES institution_xref_ncaa_track_conf_num(Codevalue);