ALTER TABLE institution 
    ADD COLUMN inst_name VARCHAR(120) COMMENT "INSTNM|Institution (entity) name",
    ADD COLUMN inst_alias VARCHAR(2000) COMMENT "IALIAS|Institution name alias",
    ADD COLUMN address VARCHAR(100) COMMENT "ADDR|Street address or post office box",
    ADD COLUMN city VARCHAR(30) COMMENT "CITY|City location of institution",
    ADD COLUMN state VARCHAR(2) COMMENT "STABBR|State abbreviation",
    ADD COLUMN zip_code VARCHAR(10) COMMENT "ZIP|ZIP code",
    ADD COLUMN fips_state_code TINYINT COMMENT "FIPS|FIPS state code",
    ADD COLUMN bea_regions TINYINT COMMENT "OBEREG|Bureau of Economic Analysis (BEA) regions",
    ADD COLUMN chief_admin_name VARCHAR(50) COMMENT "CHFNM|Name of chief administrator",
    ADD COLUMN chief_admin_title VARCHAR(50) COMMENT "CHFTITLE|Title of chief administrator",
    ADD COLUMN phone_number VARCHAR(15) COMMENT "GENTELE|General information telephone number",
    ADD COLUMN employer_id VARCHAR(9) COMMENT "EIN|Employer Identification Number",
    ADD COLUMN dun_bradstreet_numbers VARCHAR(2000) COMMENT "DUNS|Dun and Bradstreet numbers",
    ADD COLUMN ope_id VARCHAR(8) COMMENT "OPEID|Office of Postsecondary Education (OPE) ID Number",
    ADD COLUMN ope_eligibility_code TINYINT COMMENT "OPEFLAG|OPE Title IV eligibility indicator code",
    ADD COLUMN inst_url VARCHAR(150) COMMENT "WEBADDR|Institution's internet website address",
    ADD COLUMN admissions_url VARCHAR(200) COMMENT "ADMINURL|Admissions office web address",
    ADD COLUMN financial_aid_url VARCHAR(200) COMMENT "FAIDURL|Financial aid office web address",
    ADD COLUMN online_app_url VARCHAR(200) COMMENT "APPLURL|Online application web address",
    ADD COLUMN net_price_calculator_url VARCHAR(200) COMMENT "NPRICURL|Net price calculator web address",
    ADD COLUMN veterans_tuition_url VARCHAR(200) COMMENT "VETURL|Veterans and Military Servicemembers tuition policies web address",
    ADD COLUMN athlete_graduation_url VARCHAR(150) COMMENT "ATHURL|Student-Right-to-Know student athlete graduation rate web address",
    ADD COLUMN disability_url VARCHAR(200) COMMENT "DISAURL|Disability Services Web Address",
    ADD COLUMN sector TINYINT COMMENT "SECTOR|Sector of institution",
    ADD COLUMN level TINYINT COMMENT "ICLEVEL|Level of institution",
    ADD COLUMN control TINYINT COMMENT "CONTROL|Control of institution",
    ADD COLUMN highest_level TINYINT COMMENT "HLOFFER|Highest level of offering",
    ADD COLUMN undergraduate_offering TINYINT COMMENT "UGOFFER|Undergraduate offering",
    ADD COLUMN graduate_offering TINYINT COMMENT "GROFFER|Graduate offering",
    ADD COLUMN highest_degree_offered TINYINT COMMENT "HDEGOFR1|Highest degree offered",
    ADD COLUMN degree_granting_status TINYINT COMMENT "DEGGRANT|Degree-granting status",
    ADD COLUMN hbcu TINYINT COMMENT "HBCU|Historically Black College or University",
    ADD COLUMN has_hospital TINYINT COMMENT "HOSPITAL|Institution has hospital",
    ADD COLUMN grants_medical_degree TINYINT COMMENT "MEDICAL|Institution grants a medical degree",
    ADD COLUMN tribal_college TINYINT COMMENT "TRIBAL|Tribal college",
    ADD COLUMN urbanization_degree TINYINT COMMENT "LOCALE|Degree of urbanization (Urban-centric locale)",
    ADD COLUMN open_to_public TINYINT COMMENT "OPENPUBL|Institution open to the general public",
    ADD COLUMN institution_status VARCHAR(1) COMMENT "ACT|Status of institution",
    ADD COLUMN unitid_merged_schools MEDIUMINT COMMENT "NEWID|UNITID for merged schools",
    ADD COLUMN year_deleted_ipeds SMALLINT COMMENT "DEATHYR|Year institution was deleted from IPEDS",
    ADD COLUMN date_closed VARCHAR(10) COMMENT "CLOSEDAT|Date institution closed",
    ADD COLUMN active_in_current_year TINYINT COMMENT "CYACTIVE|Institution is active in current year",
    ADD COLUMN postsecondary_indicator TINYINT COMMENT "POSTSEC|Primarily postsecondary indicator",
    ADD COLUMN title_iv_indicator TINYINT COMMENT "PSEFLAG|Postsecondary institution indicator",
    ADD COLUMN postsecondary_title_iv_indicator TINYINT COMMENT "PSET4FLG|Postsecondary and Title IV institution indicator",
    ADD COLUMN rpt_charges_grad_retention_fin_aid TINYINT COMMENT "RPTMTH|Reporting method for student charges, graduation rates, retention rates and student financial aid",
    ADD COLUMN institutional_category TINYINT COMMENT "INSTCAT|Institutional category",
    ADD COLUMN carnegie_classification_2021_basic TINYINT COMMENT "C21BASIC|Carnegie Classification 2021: Basic",
    ADD COLUMN carnegie_classification_2021_ugrad_pgm TINYINT COMMENT "C21IPUG|Carnegie Classification 2021: Undergraduate Instructional Program",
    ADD COLUMN carnegie_classification_2021_grad_pgm TINYINT COMMENT "C21IPGRD|Carnegie Classification 2021: Graduate Instructional Program",
    ADD COLUMN carnegie_classification_2021_ugrad_profile TINYINT COMMENT "C21UGPRF|Carnegie Classification 2021: Undergraduate Profile",
    ADD COLUMN carnegie_classification_2021_enrollment_prf TINYINT COMMENT "C21ENPRF|Carnegie Classification 2021: Enrollment Profile",
    ADD COLUMN carnegie_classification_2021_size_setting TINYINT COMMENT "C21SZSET|Carnegie Classification 2021: Size and Setting",
    ADD COLUMN carnegie_classification_2018_basic TINYINT COMMENT "C18BASIC|Carnegie Classification 2018: Basic",
    ADD COLUMN carnegie_classification_2015_basic TINYINT COMMENT "C15BASIC|Carnegie Classification 2015: Basic",
    ADD COLUMN carnegie_classification_2005_2010_basic TINYINT COMMENT "CCBASIC|Carnegie Classification 2005/2010: Basic",
    ADD COLUMN carnegie_classification_2000 TINYINT COMMENT "CARNEGIE|Carnegie Classification 2000",
    ADD COLUMN land_grant_institution TINYINT COMMENT "LANDGRNT|Land Grant Institution",
    ADD COLUMN institution_size_cat TINYINT COMMENT "INSTSIZE|Institution size category",
    ADD COLUMN multi_inst_org TINYINT COMMENT "F1SYSTYP|Multi-institution or multi-campus organization",
    ADD COLUMN multi_inst_name VARCHAR(80) COMMENT "F1SYSNAM|Name of multi-institution or multi-campus organization",
    ADD COLUMN multi_inst_id VARCHAR(6) COMMENT "F1SYSCOD|Identification number of multi-institution or multi-campus organization",
    ADD COLUMN cbsa MEDIUMINT COMMENT "CBSA|Core Based Statistical Area (CBSA)",
    ADD COLUMN cbsa_type TINYINT COMMENT "CBSATYPE|CBSA Type Metropolitan or Micropolitan",
    ADD COLUMN csa SMALLINT COMMENT "CSA|Combined Statistical Area (CSA)",
    ADD COLUMN necta MEDIUMINT COMMENT "NECTA|New England City and Town Area (NECTA)",
    ADD COLUMN fips_county_code MEDIUMINT COMMENT "COUNTYCD|Fips County code",
    ADD COLUMN county_name VARCHAR(30) COMMENT "COUNTYNM|County name",
    ADD COLUMN congressional_district_id SMALLINT COMMENT "CNGDSTCD|State and 114TH Congressional District ID",
    ADD COLUMN longitude DOUBLE COMMENT "LONGITUD|Longitude location of institution",
    ADD COLUMN latitude DOUBLE COMMENT "LATITUDE|Latitude location of institution",
    ADD COLUMN nces_comparison_group SMALLINT COMMENT "DFRCGID|Data Feedback Report comparison group created by NCES",
    ADD COLUMN custom_comparison_group SMALLINT COMMENT "DFRCUSCG|Data Feedback Report - Institution submitted a custom comparison group";