ALTER TABLE institution
                ADD FOREIGN KEY (state) REFERENCES institution_xref_state(Codevalue),
                ADD FOREIGN KEY (fips_state_code) REFERENCES institution_xref_fips_state_code(Codevalue),
                ADD FOREIGN KEY (bea_regions) REFERENCES institution_xref_bea_regions(Codevalue),
                ADD FOREIGN KEY (ope_eligibility_code) REFERENCES institution_xref_ope_eligibility_code(Codevalue),
                ADD FOREIGN KEY (sector) REFERENCES institution_xref_sector(Codevalue),
                ADD CHECK (level IN (1, 2, 3, -3)),
                ADD CHECK (control IN (1, 2, 3, -3)),
                ADD FOREIGN KEY (highest_level) REFERENCES institution_xref_highest_level(Codevalue),
                ADD CHECK (undergraduate_offering IN (1, 2, -3)),
                ADD CHECK (graduate_offering IN (1, 2, -3)),
                ADD FOREIGN KEY (highest_degree_offered) REFERENCES institution_xref_highest_degree_offered(Codevalue),
                ADD CHECK (degree_granting_status IN (1, 2, -3)),
                ADD CHECK (hbcu IN (1, 2)),
                ADD CHECK (has_hospital IN (1, 2, -1, -2)),
                ADD CHECK (grants_medical_degree IN (1, 2, -1, -2)),
                ADD CHECK (tribal_college IN (1, 2)),
                ADD FOREIGN KEY (urbanization_degree) REFERENCES institution_xref_urbanization_degree(Codevalue),
                ADD CHECK (open_to_public IN (1, 0)),
                ADD FOREIGN KEY (institution_status) REFERENCES institution_xref_institution_status(Codevalue),
                ADD CHECK (year_deleted_ipeds IN (2021, -2)),
                ADD CHECK (active_in_current_year IN (1, 2, 3)),
                ADD CHECK (postsecondary_indicator IN (1, 2, 3)),
                ADD CHECK (title_iv_indicator IN (1, 2, 3)),
                ADD CHECK (postsecondary_title_iv_indicator IN (1, 2, 3, 4, 5, 6, 9)),
                ADD CHECK (rpt_charges_grad_retention_fin_aid IN (1, 3, 2, -1, -2)),
                ADD FOREIGN KEY (institutional_category) REFERENCES institution_xref_institutional_category(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_basic) REFERENCES institution_xref_carnegie_classification_2021_basic(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_ugrad_pgm) REFERENCES institution_xref_carnegie_classification_2021_ugrad_pgm(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_grad_pgm) REFERENCES institution_xref_carnegie_classification_2021_grad_pgm(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_ugrad_profile) REFERENCES institution_xref_carnegie_classification_2021_ugrad_profile(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_enrollment_prf) REFERENCES institution_xref_carnegie_classification_2021_enrollment_prf(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2021_size_setting) REFERENCES institution_xref_carnegie_classification_2021_size_setting(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2018_basic) REFERENCES institution_xref_carnegie_classification_2018_basic(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2015_basic) REFERENCES institution_xref_carnegie_classification_2015_basic(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2005_2010_basic) REFERENCES institution_xref_carnegie_classification_2005_2010_basic(Codevalue),
                ADD FOREIGN KEY (carnegie_classification_2000) REFERENCES institution_xref_carnegie_classification_2000(Codevalue),
                ADD CHECK (land_grant_institution IN (1, 2)),
                ADD CHECK (institution_size_cat IN (1, 2, 3, 4, 5, -1, -2)),
                ADD CHECK (multi_inst_org IN (1, 2, -1, -2)),
                ADD FOREIGN KEY (multi_inst_id) REFERENCES institution_xref_multi_inst_id(Codevalue),
                ADD FOREIGN KEY (cbsa) REFERENCES institution_xref_cbsa(Codevalue),
                ADD CHECK (cbsa_type IN (1, 2, -2, -3)),
                ADD FOREIGN KEY (csa) REFERENCES institution_xref_csa(Codevalue),
                ADD FOREIGN KEY (necta) REFERENCES institution_xref_necta(Codevalue),
                ADD FOREIGN KEY (fips_county_code) REFERENCES institution_xref_fips_county_code(Codevalue),
                ADD FOREIGN KEY (congressional_district_id) REFERENCES institution_xref_congressional_district_id(Codevalue),
                ADD FOREIGN KEY (nces_comparison_group) REFERENCES institution_xref_nces_comparison_group(Codevalue),
                ADD CHECK (custom_comparison_group IN (1, 2, -1, -2));