ALTER TABLE institution_f21_distance 
    ADD COLUMN student_level_dist SMALLINT COMMENT "EFDELEV|Level of student",
  ADD COLUMN total_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDETOT|All students enrolled",
    ADD COLUMN total_enrollment MEDIUMINT COMMENT "EFDETOT|All students enrolled",
  ADD COLUMN distance_exclusive_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEXC|Students enrolled exclusively in distance education courses",
    ADD COLUMN distance_exclusive_enrollment FLOAT COMMENT "EFDEEXC|Students enrolled exclusively in distance education courses",
  ADD COLUMN distance_partial_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDESOM|Students enrolled in some but not all distance education courses",
    ADD COLUMN distance_partial_enrollment FLOAT COMMENT "EFDESOM|Students enrolled in some but not all distance education courses",
  ADD COLUMN non_distance_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDENON|Student not enrolled in any distance education courses",
    ADD COLUMN non_distance_enrollment FLOAT COMMENT "EFDENON|Student not enrolled in any distance education courses",
  ADD COLUMN distance_same_state_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEX1|Students enrolled exclusively in distance education courses and are located in same state/jurisdiction as institution",
    ADD COLUMN distance_same_state_enrollment FLOAT COMMENT "EFDEEX1|Students enrolled exclusively in distance education courses and are located in same state/jurisdiction as institution",
  ADD COLUMN distance_out_of_state_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEX2|Students enrolled exclusively in distance education courses and are located in U.S., not in same state/jurisdiction as institution",
    ADD COLUMN distance_out_of_state_enrollment FLOAT COMMENT "EFDEEX2|Students enrolled exclusively in distance education courses and are located in U.S., not in same state/jurisdiction as institution",
  ADD COLUMN distance_unknown_state_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEX3|Students enrolled exclusively in distance education courses and are located in U.S., state/jurisdiction unknown",
    ADD COLUMN distance_unknown_state_enrollment FLOAT COMMENT "EFDEEX3|Students enrolled exclusively in distance education courses and are located in U.S., state/jurisdiction unknown",
  ADD COLUMN distance_international_enrollment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEX4|Students enrolled exclusively in distance education courses and are located outside U.S.",
    ADD COLUMN distance_international_enrollment FLOAT COMMENT "EFDEEX4|Students enrolled exclusively in distance education courses and are located outside U.S.",
  ADD COLUMN distance_location_unknown_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFDEEX5|Students enrolled exclusively in distance education courses and location of student unknown/not reported",
    ADD COLUMN distance_location_unknown FLOAT COMMENT "EFDEEX5|Students enrolled exclusively in distance education courses and location of student unknown/not reported";