ALTER TABLE institution_f21_enroll_age_gender 
    ADD COLUMN age_cat TINYINT COMMENT "EFBAGE|Age category",
    ADD COLUMN line_num_b SMALLINT COMMENT "LINEB|Original line number on survey form",
    ADD COLUMN study_level_b TINYINT COMMENT "LSTUDYB|Level of student",
  ADD COLUMN ft_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE01|Full time men",
    ADD COLUMN ft_men MEDIUMINT COMMENT "EFAGE01|Full time men",
  ADD COLUMN ft_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE02|Full time women",
    ADD COLUMN ft_women MEDIUMINT COMMENT "EFAGE02|Full time women",
  ADD COLUMN pt_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE03|Part time men",
    ADD COLUMN pt_men MEDIUMINT COMMENT "EFAGE03|Part time men",
  ADD COLUMN pt_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE04|Part time women",
    ADD COLUMN pt_women MEDIUMINT COMMENT "EFAGE04|Part time women",
  ADD COLUMN ft_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE05|Full time total",
    ADD COLUMN ft_total MEDIUMINT COMMENT "EFAGE05|Full time total",
  ADD COLUMN pt_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE06|Part time total",
    ADD COLUMN pt_total MEDIUMINT COMMENT "EFAGE06|Part time total",
  ADD COLUMN total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE07|Total men",
    ADD COLUMN total_men MEDIUMINT COMMENT "EFAGE07|Total men",
  ADD COLUMN total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE08|Total women",
    ADD COLUMN total_women MEDIUMINT COMMENT "EFAGE08|Total women",
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "EFAGE09|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "EFAGE09|Grand total";