ALTER TABLE institution_hr_occupation_race_gender 
    ADD COLUMN occupation_status SMALLINT COMMENT "STAFFCAT|Occupation and full- and part-time status",
    ADD COLUMN status TINYINT COMMENT "FTPT|Full-time or part-time status",
    ADD COLUMN occupation_cat SMALLINT COMMENT "OCCUPCAT|Occupation category",
    ADD COLUMN identifies_occupations SMALLINT COMMENT "SABDTYPE|Identifies occupations consistent with previous codes",
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRTOTLT|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "HRTOTLT|Grand total",
  ADD COLUMN grand_total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRTOTLM|Grand total men",
    ADD COLUMN grand_total_men MEDIUMINT COMMENT "HRTOTLM|Grand total men",
  ADD COLUMN grand_total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRTOTLW|Grand total women",
    ADD COLUMN grand_total_women MEDIUMINT COMMENT "HRTOTLW|Grand total women",
  ADD COLUMN ai_an_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRAIANT|American Indian or Alaska Native total",
    ADD COLUMN ai_an_total MEDIUMINT COMMENT "HRAIANT|American Indian or Alaska Native total",
  ADD COLUMN ai_an_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRAIANM|American Indian or Alaska Native men",
    ADD COLUMN ai_an_men MEDIUMINT COMMENT "HRAIANM|American Indian or Alaska Native men",
  ADD COLUMN ai_an_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRAIANW|American Indian or Alaska Native women",
    ADD COLUMN ai_an_women MEDIUMINT COMMENT "HRAIANW|American Indian or Alaska Native women",
  ADD COLUMN asian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRASIAT|Asian total",
    ADD COLUMN asian_total MEDIUMINT COMMENT "HRASIAT|Asian total",
  ADD COLUMN asian_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRASIAM|Asian men",
    ADD COLUMN asian_men MEDIUMINT COMMENT "HRASIAM|Asian men",
  ADD COLUMN asian_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRASIAW|Asian women",
    ADD COLUMN asian_women MEDIUMINT COMMENT "HRASIAW|Asian women",
  ADD COLUMN black_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRBKAAT|Black or African American total",
    ADD COLUMN black_total MEDIUMINT COMMENT "HRBKAAT|Black or African American total",
  ADD COLUMN black_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRBKAAM|Black or African American men",
    ADD COLUMN black_men MEDIUMINT COMMENT "HRBKAAM|Black or African American men",
  ADD COLUMN black_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRBKAAW|Black or African American women",
    ADD COLUMN black_women MEDIUMINT COMMENT "HRBKAAW|Black or African American women",
  ADD COLUMN hispanic_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRHISPT|Hispanic or Latino total",
    ADD COLUMN hispanic_total MEDIUMINT COMMENT "HRHISPT|Hispanic or Latino total",
  ADD COLUMN hispanic_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRHISPM|Hispanic or Latino men",
    ADD COLUMN hispanic_men MEDIUMINT COMMENT "HRHISPM|Hispanic or Latino men",
  ADD COLUMN hispanic_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRHISPW|Hispanic or Latino women",
    ADD COLUMN hispanic_women MEDIUMINT COMMENT "HRHISPW|Hispanic or Latino women",
  ADD COLUMN native_hawaiian_pacific_islander_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNHPIT|Native Hawaiian or Other Pacific Islander total",
    ADD COLUMN native_hawaiian_pacific_islander_total MEDIUMINT COMMENT "HRNHPIT|Native Hawaiian or Other Pacific Islander total",
  ADD COLUMN native_hawaiian_pacific_islander_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNHPIM|Native Hawaiian or Other Pacific Islander men",
    ADD COLUMN native_hawaiian_pacific_islander_men MEDIUMINT COMMENT "HRNHPIM|Native Hawaiian or Other Pacific Islander men",
  ADD COLUMN native_hawaiian_pacific_islander_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNHPIW|Native Hawaiian or Other Pacific Islander women",
    ADD COLUMN native_hawaiian_pacific_islander_women MEDIUMINT COMMENT "HRNHPIW|Native Hawaiian or Other Pacific Islander women",
  ADD COLUMN white_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRWHITT|White total",
    ADD COLUMN white_total MEDIUMINT COMMENT "HRWHITT|White total",
  ADD COLUMN white_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRWHITM|White men",
    ADD COLUMN white_men MEDIUMINT COMMENT "HRWHITM|White men",
  ADD COLUMN white_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRWHITW|White women",
    ADD COLUMN white_women MEDIUMINT COMMENT "HRWHITW|White women",
  ADD COLUMN two_or_more_races_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HR2MORT|Two or more races total",
    ADD COLUMN two_or_more_races_total MEDIUMINT COMMENT "HR2MORT|Two or more races total",
  ADD COLUMN two_or_more_races_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HR2MORM|Two or more races men",
    ADD COLUMN two_or_more_races_men MEDIUMINT COMMENT "HR2MORM|Two or more races men",
  ADD COLUMN two_or_more_races_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HR2MORW|Two or more races women",
    ADD COLUMN two_or_more_races_women MEDIUMINT COMMENT "HR2MORW|Two or more races women",
  ADD COLUMN race_ethnicity_unknown_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRUNKNT|Race/ethnicity unknown total",
    ADD COLUMN race_ethnicity_unknown_total MEDIUMINT COMMENT "HRUNKNT|Race/ethnicity unknown total",
  ADD COLUMN race_ethnicity_unknown_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRUNKNM|Race/ethnicity unknown men",
    ADD COLUMN race_ethnicity_unknown_men MEDIUMINT COMMENT "HRUNKNM|Race/ethnicity unknown men",
  ADD COLUMN race_ethnicity_unknown_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRUNKNW|Race/ethnicity unknown women",
    ADD COLUMN race_ethnicity_unknown_women MEDIUMINT COMMENT "HRUNKNW|Race/ethnicity unknown women",
  ADD COLUMN nonresident_alien_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNRALT|Nonresident alien total",
    ADD COLUMN nonresident_alien_total MEDIUMINT COMMENT "HRNRALT|Nonresident alien total",
  ADD COLUMN nonresident_alien_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNRALM|Nonresident alien men",
    ADD COLUMN nonresident_alien_men MEDIUMINT COMMENT "HRNRALM|Nonresident alien men",
  ADD COLUMN nonresident_alien_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "HRNRALW|Nonresident alien women",
    ADD COLUMN nonresident_alien_women MEDIUMINT COMMENT "HRNRALW|Nonresident alien women";