ALTER TABLE institution_ic_response_flags 
    ADD COLUMN ic_status TINYINT COMMENT "STAT_IC|Response status -  Institutional characteristics component",
    ADD COLUMN ic_migration_status TINYINT COMMENT "LOCK_IC|Status of IC component when institution was migrated",
    ADD COLUMN ic_imputation_method TINYINT COMMENT "IMP_IC|Type of imputation method Institutional Characteristics",
    ADD COLUMN completions_status TINYINT COMMENT "STAT_C|Response status -  Completions component",
    ADD COLUMN completions_migration_status TINYINT COMMENT "LOCK_C|Status of completions component when institution was migrated",
    ADD COLUMN completions_parent_child_indicator TINYINT COMMENT "PRCH_C|Parent/child indicator for completions",
    ADD COLUMN completions_parent_unitid MEDIUMINT COMMENT "IDX_C|UnitID of Parent institution",
    ADD COLUMN completions_allocation_factor FLOAT COMMENT "PCC_F|Parent/child allocation factor - Completions",
    ADD COLUMN completions_imputation_method TINYINT COMMENT "IMP_C|Type of imputation method Completions",
    ADD COLUMN enrollment_status TINYINT COMMENT "STAT_E12|Response status of institution - 12-month enrollment",
    ADD COLUMN enrollment_migration_status TINYINT COMMENT "LOCK_E12|Status of 12-month enrollment component whe data collection closed",
    ADD COLUMN enrollment_parent_child_indicator TINYINT COMMENT "PRCH_E12|Parent/child indicator for 12-month enrollment",
    ADD COLUMN enrollment_parent_unitid MEDIUMINT COMMENT "IDX_E12|ID number of parent institution - 12-month enrollment",
    ADD COLUMN enrollment_allocation_factor FLOAT COMMENT "PCE12_F|Parent/child allocation factor - 12-month enrollment",
    ADD COLUMN enrollment_imputation_method TINYINT COMMENT "IMP_E12|Type of imputation method - 12 month enrollment",
    ADD COLUMN aid_status TINYINT COMMENT "STAT_SFA|Response status for Student Financial Aid survey",
    ADD COLUMN aid_migration_status TINYINT COMMENT "LOCK_SFA|Status of Student Financial Aid Survey when data collection closed",
    ADD COLUMN aid_parent_child_indicator TINYINT COMMENT "PRCH_SFA|Parent/child indicator Student Financial Aid survey",
    ADD COLUMN aid_parent_unitid MEDIUMINT COMMENT "IDX_SFA|ID number of parent institution Student Financial Aid",
    ADD COLUMN aid_allocation_factor FLOAT COMMENT "PCSFA_F|Parent/child allocation factor - Student Financial Aid",
    ADD COLUMN aid_imputation_method TINYINT COMMENT "IMP_SFA|Type of imputation method Student Financial Aid",
    ADD COLUMN aid_collection_form_type TINYINT COMMENT "SFAFORM|SFA collection form type",
    ADD COLUMN graduation_status TINYINT COMMENT "STAT_GR|Response status - Graduation Rates",
    ADD COLUMN graduation_migration_status TINYINT COMMENT "LOCK_GR|Status of Graduation rate survey when data collection closed",
    ADD COLUMN graduation_parent_child_indicator TINYINT COMMENT "PRCH_GR|Parent/child indicator - Graduation Rates",
    ADD COLUMN graduation_parent_unitid MEDIUMINT COMMENT "IDX_GR|UNITID of parent institution reporting Graduation Rates",
    ADD COLUMN graduation_allocation_factor FLOAT COMMENT "PCGR_F|Parent/child allocation factor - Graduation Rates",
    ADD COLUMN graduation_imputation_method TINYINT COMMENT "IMP_GR|Imputation method - Graduation Rates",
    ADD COLUMN enrolled_fulltime_firsttime_students TINYINT COMMENT "COHRTSTU|Enrolled any full-time first-time students",
    ADD COLUMN response_status_graduation_rates_200 TINYINT COMMENT "STAT_GR2|Response status - Graduation Rates 200",
    ADD COLUMN status_graduation_rate_200_survey TINYINT COMMENT "LOCK_GR2|Status of Graduation rate 200 survey when data collection closed",
    ADD COLUMN parent_child_indicator_graduation_rates_200 TINYINT COMMENT "PRCH_GR2|Parent/child indicator - Graduation Rates 200",
    ADD COLUMN unitid_parent_institution_graduation_rates_200 MEDIUMINT COMMENT "IDX_GR2|UNITID of parent institution reporting Graduation Rates 200",
    ADD COLUMN parent_child_allocation_factor_graduation_rates_200 FLOAT COMMENT "PCGR2_F|Parent/child allocation factor - Graduation Rates 200",
    ADD COLUMN imputation_method_graduation_rates_200 TINYINT COMMENT "IMP_GR2|Imputation method - Graduation Rates 200",
    ADD COLUMN response_status_outcome_measures TINYINT COMMENT "STAT_OM|Response status - Outcome Measures",
    ADD COLUMN status_outcome_measures_component TINYINT COMMENT "LOCK_OM|Status of Outcome Measures component when data collection closed",
    ADD COLUMN parent_child_indicator_outcome_measures TINYINT COMMENT "PRCH_OM|Parent/child indicator - Outcome Measures",
    ADD COLUMN unitid_parent_institution_outcome_measures MEDIUMINT COMMENT "IDX_OM|UNITID of parent institution reporting Outcome Measures",
    ADD COLUMN parent_child_allocation_factor_outcome_measures FLOAT COMMENT "PCOM_F|Parent/child allocation factor - Outcome Measures",
    ADD COLUMN imputations_method_outcome_measures TINYINT COMMENT "IMP_OM|Imputations method - Outcome Measures",
    ADD COLUMN response_status_admissions_component TINYINT COMMENT "STAT_ADM|Response status - Admissions component",
    ADD COLUMN status_admissions_component_migration TINYINT COMMENT "LOCK_ADM|Status of admissions component when institution was migrated",
    ADD COLUMN parent_child_indicator_admissions TINYINT COMMENT "PRCH_ADM|Parent/child indicator for Admissions",
    ADD COLUMN id_parent_institution_admissions MEDIUMINT COMMENT "IDX_ADM|ID number of parent institution - Admissions",
    ADD COLUMN parent_child_allocation_factor_admissions FLOAT COMMENT "PCADM_F|Parent/child allocation factor - Admissions",
    ADD COLUMN type_imputation_method_admissions_component TINYINT COMMENT "IMP_ADM|Type of imputation method - Admissions component",
    ADD COLUMN response_status_hr_component TINYINT COMMENT "STAT_HR|Response status of institution for Human Resources (HR) component",
    ADD COLUMN status_hr_component_data_collection TINYINT COMMENT "LOCK_HR|Status of Human Resources (HR) component when data collection closed",
    ADD COLUMN parent_child_indicator_hr_component TINYINT COMMENT "PRCH_HR|Parent/child  indicator - Human Resources (HR) component",
    ADD COLUMN id_institution_hr_component MEDIUMINT COMMENT "IDX_HR|ID of institution where data are reported for the Human Resources (HR) component",
    ADD COLUMN parent_child_allocation_factor_hr FLOAT COMMENT "PCHR_F|Parent/child allocation factor - HR",
    ADD COLUMN type_imputation_method_hr_component TINYINT COMMENT "IMP_HR|Type of Imputation method - Human Resources (HR) component",
    ADD COLUMN has_15_or_more_full_time_employees TINYINT COMMENT "FTEMP15|Does institution have 15 or more full-time employees",
    ADD COLUMN has_tenure_system TINYINT COMMENT "TENURSYS|Does institution have a tenure system",
    ADD COLUMN salary_exclusion TINYINT COMMENT "SA_EXCL|Salary exclusion",
    ADD COLUMN response_status_eap TINYINT COMMENT "STAT_EAP|Response status for EAP",
    ADD COLUMN response_status_sa_survey TINYINT COMMENT "STAT_SA|Response status to SA survey",
    ADD COLUMN response_status_fall_staff TINYINT COMMENT "STAT_S|Response status for Fall Staff",
    ADD COLUMN status_fall_enrollment TINYINT COMMENT "STAT_EF|Response status of institution -  Fall enrollment",
    ADD COLUMN status_fall_enrollment_survey TINYINT COMMENT "LOCK_EF|Status of Fall Enrollment survey when data collection closed",
    ADD COLUMN parent_child_indicator_fall_enrollment TINYINT COMMENT "PRCH_EF|Parent/child indicator f- Fall enrollment",
    ADD COLUMN parent_id_fall_enrollment MEDIUMINT COMMENT "IDX_EF|ID number of parent institution - Fall enrollment",
    ADD COLUMN parent_child_allocation_factor_fall_enrollment FLOAT COMMENT "PCEF_F|Parent/child allocation factor - Fall enrollment",
    ADD COLUMN imputation_method_fall_enrollment TINYINT COMMENT "IMP_EF|Type of imputation method - Fall enrollment",
    ADD COLUMN status_enrollment_race_ethnicity TINYINT COMMENT "PTA99_EF|Status enrollment by race/ethnicity (99.0000 CIP)",
    ADD COLUMN status_enrollment_major TINYINT COMMENT "PTACIPEF|Status enrollment by major",
    ADD COLUMN status_enrollment_summary_age TINYINT COMMENT "PTB_EF|Status enrollment summary by age",
    ADD COLUMN status_residence_first_year_students TINYINT COMMENT "PTC_EF|Status residence of first-time first-year students",
    ADD COLUMN status_entering_class_retention_rates TINYINT COMMENT "PTD_EF|Status total entering class and retention rates",
    ADD COLUMN status_finance_survey TINYINT COMMENT "STAT_F|Response status for Finance survey",
    ADD COLUMN status_finance_survey_closed TINYINT COMMENT "LOCK_F|Status of Finance survey when data collection closed",
    ADD COLUMN parent_child_indicator_finance TINYINT COMMENT "PRCH_F|Parent/child indicator - Finance",
    ADD COLUMN parent_id_finance MEDIUMINT COMMENT "IDX_F|ID number of parent institution - Finance",
    ADD COLUMN parent_child_allocation_factor_finance FLOAT COMMENT "PCF_F|Parent/child allocation factor - Finance",
    ADD COLUMN parent_child_system_indicator_finance TINYINT COMMENT "PRCHTP_F|Parent/child system indicator - Finance",
    ADD COLUMN imputation_method_finance TINYINT COMMENT "IMP_F|Type of imputation method  Finance",
    ADD COLUMN reporting_standards_finance TINYINT COMMENT "FORM_F|Identifies reporting standards GASB, FASB, or modified FASB(for-profit institutions) used to report finance data",
    ADD COLUMN fiscal_year_start_finance VARCHAR(6) COMMENT "FYBEG|Beginning date of fiscal year covered (all finance)",
    ADD COLUMN fiscal_year_end_finance VARCHAR(6) COMMENT "FYEND|End date of fiscal year covered  (all finance)",
    ADD COLUMN audit_opinion_finance TINYINT COMMENT "GPFS|Audit Opinion GPFS from auditor (all finance)",
    ADD COLUMN gasb_accounting_model TINYINT COMMENT "F1GASBAL|GASB alternative accounting model",
    ADD COLUMN pell_grants_accounting_fasb TINYINT COMMENT "F2PELL|Account for Pell grants as pass through transactions or as federal grant revenues to the institution (FASB  institutions)?",
    ADD COLUMN pell_grants_accounting_private_for_profit TINYINT COMMENT "F3PELL|Account for Pell grants as pass through transactions or as federal grant revenues to the institution (private-for-profit institutions)?",
    ADD COLUMN athletic_expenses_accounting TINYINT COMMENT "F_ATHLTC|Are intercollegiate athletic expenses accounted for as auxiliary enterprises or treated as student services",
    ADD COLUMN athletic_revenues_sales_educational TINYINT COMMENT "F_ATHRV1|Are intercollegiate athletic revenues included with sales and services of educational activities",
    ADD COLUMN athletic_revenues_sales_auxiliary TINYINT COMMENT "F_ATHRV2|Are intercollegiate athletic revenues included with sales and services of auxiliary enterprises",
    ADD COLUMN no_athletic_revenues TINYINT COMMENT "F_ATHRV3|Does not have intercollegiate athletics revenues",
    ADD COLUMN athletic_revenues_other_source TINYINT COMMENT "F_ATHRV9|Are intercollegiate athletic revenues included with a source other than educational activities or auxiliary enterprises",
    ADD COLUMN business_structure TINYINT COMMENT "F3BIST|Type of business structure for tax purposes (private-for-profit, degree-granting institutions)",
    ADD COLUMN response_status_academic_libraries TINYINT COMMENT "STAT_AL|Response status -  Academic Libraries component",
    ADD COLUMN status_migration_academic_libraries TINYINT COMMENT "LOCK_AL|Status of Academic Library component when institution was migrated",
    ADD COLUMN parent_child_indicator_academic_libraries TINYINT COMMENT "PRCH_AL|Parent/child indicator for Academic Libraries",
    ADD COLUMN parent_unitid_academic_libraries MEDIUMINT COMMENT "IDX_AL|UnitID of Parent institution - Academic Libraries",
    ADD COLUMN parent_child_allocation_factor_academic_libraries FLOAT COMMENT "PCAL_F|Parent/child allocation factor - Academic Libraries",
    ADD COLUMN imputation_method_academic_libraries TINYINT COMMENT "IMP_AL|Type of imputation method - Academic Libraries",
    ADD COLUMN has_academic_library TINYINT COMMENT "HASAL|Has an academic library",
    ADD COLUMN natural_disaster_id TINYINT COMMENT "NTRLDSTR|Natural Disaster identification";