
            ALTER TABLE institution_campus 
                ADD FOREIGN KEY (inst_id) REFERENCES institution(inst_id),
                ADD FOREIGN KEY (state) REFERENCES institution_xref_state(Codevalue),
                ADD FOREIGN KEY (fips_state_code) REFERENCES institution_xref_fips_state_code(Codevalue),
                ADD FOREIGN KEY (bea_regions) REFERENCES institution_xref_bea_regions(Codevalue),
                ADD FOREIGN KEY (ope_eligibility_code) REFERENCES institution_xref_ope_eligibility_code(Codevalue),
                ADD FOREIGN KEY (sector) REFERENCES institution_xref_sector(Codevalue),
                ADD CHECK (level IN (1, 2, 3, -3)),
                ADD CHECK (control IN (1, 2, 3, -3)),
                ADD FOREIGN KEY (highest_level) REFERENCES institution_xref_highest_level(Codevalue),
                ADD CHECK (undergrad_offering IN (1, 2, -3)),
                ADD CHECK (grad_offering IN (1, 2, -3)),
                ADD FOREIGN KEY (highest_degree_offered) REFERENCES institution_xref_highest_degree_offered(Codevalue),
                ADD CHECK (degree_granting_status IN (1, 2, -3)),
                ADD CHECK (hbcu IN (1, 2)),
                ADD CHECK (tribal_college IN (1, 2)),
                ADD FOREIGN KEY (urbanization_degree) REFERENCES institution_xref_urbanization_degree(Codevalue),
                ADD CHECK (open_to_public IN (1, 0)),
                ADD FOREIGN KEY (institution_status) REFERENCES institution_xref_institution_status(Codevalue),
                ADD CHECK (active_in_current_year IN (1, 2, 3)),
                ADD CHECK (primarily_postsecondary IN (1, 2, 3)),
                ADD CHECK (inst_indicator IN (1, 2, 3)),
                ADD CHECK (title_iv_indicator IN (1, 2, 3, 4, 5, 6, 9)),
                ADD FOREIGN KEY (cbsa) REFERENCES institution_xref_cbsa(Codevalue),
                ADD CHECK (cbsa_type IN (1, 2, -2, -3)),
                ADD FOREIGN KEY (csa) REFERENCES institution_xref_csa(Codevalue),
                ADD FOREIGN KEY (necta) REFERENCES institution_xref_necta(Codevalue),
                ADD FOREIGN KEY (fips_county_code) REFERENCES institution_xref_fips_county_code(Codevalue),
                ADD FOREIGN KEY (congressional_district_id) REFERENCES institution_xref_congressional_district_id(Codevalue),
                ADD CHECK (cert_lt_1yr IN (1, 0, -1)),
                ADD CHECK (cert_lt_12wks IN (1, 0, -1)),
                ADD CHECK (cert_12wks_lt_1yr IN (1, 0, -1)),
                ADD CHECK (cert_1yr_lt_2yr IN (1, 0, -1)),
                ADD CHECK (associates_degree IN (1, 0, -1)),
                ADD CHECK (cert_2yr_lt_4yr IN (1, 0, -1)),
                ADD CHECK (bachelors_degree IN (1, 0, -1, -2)),
                ADD CHECK (postbacc_cert IN (1, 0, -1, -2)),
                ADD CHECK (masters_degree IN (1, 0, -1, -2)),
                ADD CHECK (post_masters_cert IN (1, 0, -1, -2)),
                ADD CHECK (doctors_degree_research IN (1, 0, -1, -2)),
                ADD CHECK (doctors_degree_prof_practice IN (1, 0, -1, -2)),
                ADD CHECK (doctors_degree_other IN (1, 0, -1, -2)),
                ADD CHECK (fulltime_undergrad_enrolled IN (1, 2, -2)),
                ADD CHECK (fulltime_undergrad_live_on_cmps IN (1, 2, -1, -2)),
                ADD CHECK (oncampus_housing IN (1, 2, -1, -2)),
                ADD FOREIGN KEY (cip_code) REFERENCES institution_xref_cip_code(Codevalue),
                ADD CHECK (largest_program_length_credit_clock IN (1, 2, -1, -2));