ALTER TABLE institution_gr_gt2yr 
    ADD COLUMN cohort_data SMALLINT COMMENT "GRTYPE|Cohort data",
    ADD COLUMN grad_rate_status TINYINT COMMENT "CHRTSTAT|Graduation rate status in cohort",
    ADD COLUMN survey_section TINYINT COMMENT "SECTION|Section of survey form",
    ADD COLUMN cohort TINYINT COMMENT "COHORT|Cohort",
    ADD COLUMN survey_line_num VARCHAR(3) COMMENT "LINE|Original line number of survey form",
  ADD COLUMN grand_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRTOTLT|Grand total",
    ADD COLUMN grand_total MEDIUMINT COMMENT "GRTOTLT|Grand total",
  ADD COLUMN total_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRTOTLM|Total men",
    ADD COLUMN total_men MEDIUMINT COMMENT "GRTOTLM|Total men",
  ADD COLUMN total_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRTOTLW|Total women",
    ADD COLUMN total_women MEDIUMINT COMMENT "GRTOTLW|Total women",
  ADD COLUMN ai_an_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRAIANT|American Indian or Alaska Native total",
    ADD COLUMN ai_an_total MEDIUMINT COMMENT "GRAIANT|American Indian or Alaska Native total",
  ADD COLUMN ai_an_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRAIANM|American Indian or Alaska Native men",
    ADD COLUMN ai_an_men MEDIUMINT COMMENT "GRAIANM|American Indian or Alaska Native men",
  ADD COLUMN ai_an_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRAIANW|American Indian or Alaska Native women",
    ADD COLUMN ai_an_women MEDIUMINT COMMENT "GRAIANW|American Indian or Alaska Native women",
  ADD COLUMN asian_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRASIAT|Asian total",
    ADD COLUMN asian_total MEDIUMINT COMMENT "GRASIAT|Asian total",
  ADD COLUMN asian_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRASIAM|Asian men",
    ADD COLUMN asian_men MEDIUMINT COMMENT "GRASIAM|Asian men",
  ADD COLUMN asian_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRASIAW|Asian women",
    ADD COLUMN asian_women MEDIUMINT COMMENT "GRASIAW|Asian women",
  ADD COLUMN black_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRBKAAT|Black or African American total",
    ADD COLUMN black_total MEDIUMINT COMMENT "GRBKAAT|Black or African American total",
  ADD COLUMN black_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRBKAAM|Black or African American men",
    ADD COLUMN black_men MEDIUMINT COMMENT "GRBKAAM|Black or African American men",
  ADD COLUMN black_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRBKAAW|Black or African American women",
    ADD COLUMN black_women MEDIUMINT COMMENT "GRBKAAW|Black or African American women",
  ADD COLUMN hispanic_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRHISPT|Hispanic total",
    ADD COLUMN hispanic_total MEDIUMINT COMMENT "GRHISPT|Hispanic total",
  ADD COLUMN hispanic_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRHISPM|Hispanic men",
    ADD COLUMN hispanic_men MEDIUMINT COMMENT "GRHISPM|Hispanic men",
  ADD COLUMN hispanic_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRHISPW|Hispanic women",
    ADD COLUMN hispanic_women MEDIUMINT COMMENT "GRHISPW|Hispanic women",
  ADD COLUMN nhopi_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNHPIT|Native Hawaiian or Other Pacific Islander total",
    ADD COLUMN nhopi_total MEDIUMINT COMMENT "GRNHPIT|Native Hawaiian or Other Pacific Islander total",
  ADD COLUMN nhopi_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNHPIM|Native Hawaiian or Other Pacific Islander men",
    ADD COLUMN nhopi_men MEDIUMINT COMMENT "GRNHPIM|Native Hawaiian or Other Pacific Islander men",
  ADD COLUMN nhopi_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNHPIW|Native Hawaiian or Other Pacific Islander women",
    ADD COLUMN nhopi_women MEDIUMINT COMMENT "GRNHPIW|Native Hawaiian or Other Pacific Islander women",
  ADD COLUMN white_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRWHITT|White total",
    ADD COLUMN white_total MEDIUMINT COMMENT "GRWHITT|White total",
  ADD COLUMN white_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRWHITM|White men",
    ADD COLUMN white_men MEDIUMINT COMMENT "GRWHITM|White men",
  ADD COLUMN white_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRWHITW|White women",
    ADD COLUMN white_women MEDIUMINT COMMENT "GRWHITW|White women",
  ADD COLUMN two_or_more_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GR2MORT|Two or more races total",
    ADD COLUMN two_or_more_total MEDIUMINT COMMENT "GR2MORT|Two or more races total",
  ADD COLUMN two_or_more_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GR2MORM|Two or more races men",
    ADD COLUMN two_or_more_men MEDIUMINT COMMENT "GR2MORM|Two or more races men",
  ADD COLUMN two_or_more_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GR2MORW|Two or more races women",
    ADD COLUMN two_or_more_women MEDIUMINT COMMENT "GR2MORW|Two or more races women",
  ADD COLUMN race_ethnicity_unknown_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRUNKNT|Race/ethnicity unknown total",
    ADD COLUMN race_ethnicity_unknown_total MEDIUMINT COMMENT "GRUNKNT|Race/ethnicity unknown total",
  ADD COLUMN race_ethnicity_unknown_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRUNKNM|Race/ethnicity unknown men",
    ADD COLUMN race_ethnicity_unknown_men MEDIUMINT COMMENT "GRUNKNM|Race/ethnicity unknown men",
  ADD COLUMN race_ethnicity_unknown_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRUNKNW|Race/ethnicity unknown women",
    ADD COLUMN race_ethnicity_unknown_women MEDIUMINT COMMENT "GRUNKNW|Race/ethnicity unknown women",
  ADD COLUMN nonresident_alien_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNRALT|Nonresident alien total",
    ADD COLUMN nonresident_alien_total MEDIUMINT COMMENT "GRNRALT|Nonresident alien total",
  ADD COLUMN nonresident_alien_men_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNRALM|Nonresident alien men",
    ADD COLUMN nonresident_alien_men MEDIUMINT COMMENT "GRNRALM|Nonresident alien men",
  ADD COLUMN nonresident_alien_women_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "GRNRALW|Nonresident alien women",
    ADD COLUMN nonresident_alien_women MEDIUMINT COMMENT "GRNRALW|Nonresident alien women";