ALTER TABLE institution_gr_grant_loan 
    ADD COLUMN cohort_type SMALLINT COMMENT "PSGRTYPE|Cohort type",
  ADD COLUMN pell_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGREVCT|Pell Grant recipients - revised cohort",
    ADD COLUMN pell_revised_cohort MEDIUMINT COMMENT "PGREVCT|Pell Grant recipients - revised cohort",
  ADD COLUMN pell_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGEXCLU|Pell Grant recipients - exclusions",
    ADD COLUMN pell_exclusions MEDIUMINT COMMENT "PGEXCLU|Pell Grant recipients - exclusions",
  ADD COLUMN pell_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGADJCT|Pell Grant recipients - adjusted  cohort (revised minus exclusions)",
    ADD COLUMN pell_adjusted_cohort MEDIUMINT COMMENT "PGADJCT|Pell Grant recipients - adjusted  cohort (revised minus exclusions)",
  ADD COLUMN pell_completed_bachelors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGCMBAC|Pell Grant  recipients - number that completed a bachelor's or equivalent degree within 150% of normal time",
    ADD COLUMN pell_completed_bachelors FLOAT COMMENT "PGCMBAC|Pell Grant  recipients - number that completed a bachelor's or equivalent degree within 150% of normal time",
  ADD COLUMN pell_completed_less_than_4_years_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGCMOBA|Pell Grant  recipients - number that completed an award of less than 4 academic years or equivalent within 150% of normal time",
    ADD COLUMN pell_completed_less_than_4_years FLOAT COMMENT "PGCMOBA|Pell Grant  recipients - number that completed an award of less than 4 academic years or equivalent within 150% of normal time",
  ADD COLUMN pell_completed_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGCMTOT|Pell Grant  recipients - total number that completed an award  within 150% of normal time",
    ADD COLUMN pell_completed_total MEDIUMINT COMMENT "PGCMTOT|Pell Grant  recipients - total number that completed an award  within 150% of normal time",
  ADD COLUMN subsidized_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSREVCT|Subsidized Stafford Loan recipients not receiving Pell Grants - revised cohort",
    ADD COLUMN subsidized_revised_cohort MEDIUMINT COMMENT "SSREVCT|Subsidized Stafford Loan recipients not receiving Pell Grants - revised cohort",
  ADD COLUMN subsidized_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSEXCLU|Subsidized Stafford Loan recipients not receiving Pell Grants - exclusions",
    ADD COLUMN subsidized_exclusions MEDIUMINT COMMENT "SSEXCLU|Subsidized Stafford Loan recipients not receiving Pell Grants - exclusions",
  ADD COLUMN subsidized_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSADJCT|Subsidized Stafford Loan recipients not receiving Pell Grants - adjusted cohort (revised minus exclusions)",
    ADD COLUMN subsidized_adjusted_cohort MEDIUMINT COMMENT "SSADJCT|Subsidized Stafford Loan recipients not receiving Pell Grants - adjusted cohort (revised minus exclusions)",
  ADD COLUMN subsidized_completed_bachelors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSCMBAC|Subsidized Stafford Loan recipients not receiving Pell Grants - number completed a bachelor's or equivalent within 150% of normal time",
    ADD COLUMN subsidized_completed_bachelors FLOAT COMMENT "SSCMBAC|Subsidized Stafford Loan recipients not receiving Pell Grants - number completed a bachelor's or equivalent within 150% of normal time",
  ADD COLUMN subsidized_completed_less_than_4_years_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSCMOBA|Subsidized Stafford Loan recipients not receiving Pell Grants - number completed an award of less than 4 academic years within 150% of normal time",
    ADD COLUMN subsidized_completed_less_than_4_years FLOAT COMMENT "SSCMOBA|Subsidized Stafford Loan recipients not receiving Pell Grants - number completed an award of less than 4 academic years within 150% of normal time",
  ADD COLUMN subsidized_completed_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSCMTOT|Subsidized Stafford Loan recipients not receiving Pell Grants - total number completed an award within 150% of normal time",
    ADD COLUMN subsidized_completed_total MEDIUMINT COMMENT "SSCMTOT|Subsidized Stafford Loan recipients not receiving Pell Grants - total number completed an award within 150% of normal time",
  ADD COLUMN no_pell_subsidized_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRREVCT|Did not receive Pell grant or subsidized Stafford loan - revised cohort",
    ADD COLUMN no_pell_subsidized_revised_cohort MEDIUMINT COMMENT "NRREVCT|Did not receive Pell grant or subsidized Stafford loan - revised cohort",
  ADD COLUMN no_pell_subsidized_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NREXCLU|Did not receive Pell grant or subsidized Stafford loan - exclusions",
    ADD COLUMN no_pell_subsidized_exclusions MEDIUMINT COMMENT "NREXCLU|Did not receive Pell grant or subsidized Stafford loan - exclusions",
  ADD COLUMN no_pell_subsidized_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRADJCT|Did not receive Pell grant or subsidized Stafford loan - adjusted  cohort (revised minus exclusions)",
    ADD COLUMN no_pell_subsidized_adjusted_cohort MEDIUMINT COMMENT "NRADJCT|Did not receive Pell grant or subsidized Stafford loan - adjusted  cohort (revised minus exclusions)",
  ADD COLUMN no_pell_subsidized_completed_bachelors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRCMBAC|Did not receive Pell grant or subsidized Stafford loan - number that completed a bachelor's or equivalent degree within 150% of normal time",
    ADD COLUMN no_pell_subsidized_completed_bachelors FLOAT COMMENT "NRCMBAC|Did not receive Pell grant or subsidized Stafford loan - number that completed a bachelor's or equivalent degree within 150% of normal time",
  ADD COLUMN no_pell_subsidized_completed_less_than_4_years_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRCMOBA|Did not receive Pell grant or subsidized Stafford loan - number that completed an award of less than 4 academic years within 150% of normal time",
    ADD COLUMN no_pell_subsidized_completed_less_than_4_years FLOAT COMMENT "NRCMOBA|Did not receive Pell grant or subsidized Stafford loan - number that completed an award of less than 4 academic years within 150% of normal time",
  ADD COLUMN no_pell_subsidized_completed_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRCMTOT|Did not receive Pell grant or subsidized Stafford loan - total number that completed an award  within 150% of normal time",
    ADD COLUMN no_pell_subsidized_completed_total MEDIUMINT COMMENT "NRCMTOT|Did not receive Pell grant or subsidized Stafford loan - total number that completed an award  within 150% of normal time",
  ADD COLUMN total_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTREVCT|Total revised cohort",
    ADD COLUMN total_revised_cohort MEDIUMINT COMMENT "TTREVCT|Total revised cohort",
  ADD COLUMN total_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTEXCLU|Total exclusions",
    ADD COLUMN total_exclusions MEDIUMINT COMMENT "TTEXCLU|Total exclusions",
  ADD COLUMN total_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTADJCT|Total adjusted cohort",
    ADD COLUMN total_adjusted_cohort MEDIUMINT COMMENT "TTADJCT|Total adjusted cohort",
  ADD COLUMN total_completed_bachelors_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTCMBAC|Total number that completed a bachelor's or equivalent degree within 150% of normal time",
    ADD COLUMN total_completed_bachelors_150pct FLOAT COMMENT "TTCMBAC|Total number that completed a bachelor's or equivalent degree within 150% of normal time",
  ADD COLUMN total_completed_less_than_4yrs_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTCMOBA|Total number that completed an award of less than 4 academic years within 150% of normal time",
    ADD COLUMN total_completed_less_than_4yrs_150pct FLOAT COMMENT "TTCMOBA|Total number that completed an award of less than 4 academic years within 150% of normal time",
  ADD COLUMN total_completed_award_150pct_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "TTCMTOT|Total number that completed an award  within 150% of normal time",
    ADD COLUMN total_completed_award_150pct MEDIUMINT COMMENT "TTCMTOT|Total number that completed an award  within 150% of normal time";