ALTER TABLE institution_fin_for_profit 
  ADD COLUMN tot_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A01|Total assets",
    ADD COLUMN tot_assets DOUBLE COMMENT "F3A01|Total assets",
  ADD COLUMN long_term_inv_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A01A|Long-term investments",
    ADD COLUMN long_term_inv DOUBLE COMMENT "F3A01A|Long-term investments",
  ADD COLUMN property_plant_equip_net_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A01B|Property, plant, and equipment, net of accumulated depreciation",
    ADD COLUMN property_plant_equip_net DOUBLE COMMENT "F3A01B|Property, plant, and equipment, net of accumulated depreciation",
  ADD COLUMN intangible_assets_net_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A01C|Intangible assets, net of accumulated amortization",
    ADD COLUMN intangible_assets_net DOUBLE COMMENT "F3A01C|Intangible assets, net of accumulated amortization",
  ADD COLUMN tot_liabilities_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A02|Total liabilities",
    ADD COLUMN tot_liabilities DOUBLE COMMENT "F3A02|Total liabilities",
  ADD COLUMN debt_property_plant_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A02A|Debt related to property, plant, and equipment",
    ADD COLUMN debt_property_plant_equip DOUBLE COMMENT "F3A02A|Debt related to property, plant, and equipment",
  ADD COLUMN tot_equity_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A03|Total equity",
    ADD COLUMN tot_equity DOUBLE COMMENT "F3A03|Total equity",
  ADD COLUMN tot_liabilities_equity_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A04|Total liabilities and equity",
    ADD COLUMN tot_liabilities_equity DOUBLE COMMENT "F3A04|Total liabilities and equity",
  ADD COLUMN land_land_improvements_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A05|Land and land improvements",
    ADD COLUMN land_land_improvements DOUBLE COMMENT "F3A05|Land and land improvements",
  ADD COLUMN buildings_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A06|Buildings",
    ADD COLUMN buildings DOUBLE COMMENT "F3A06|Buildings",
  ADD COLUMN equipment_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A07|Equipment, including art and library collections",
    ADD COLUMN equipment DOUBLE COMMENT "F3A07|Equipment, including art and library collections",
  ADD COLUMN const_in_progress_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A08|Construction in Progress",
    ADD COLUMN const_in_progress DOUBLE COMMENT "F3A08|Construction in Progress",
  ADD COLUMN other_plant_property_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A09|Other plant, property and equipment",
    ADD COLUMN other_plant_property_equip DOUBLE COMMENT "F3A09|Other plant, property and equipment",
  ADD COLUMN tot_plant_property_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A10|Total Plant, Property, and Equipment",
    ADD COLUMN tot_plant_property_equip DOUBLE COMMENT "F3A10|Total Plant, Property, and Equipment",
  ADD COLUMN accumulated_depreciation_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A11|Accumulated depreciation",
    ADD COLUMN accumulated_depreciation DOUBLE COMMENT "F3A11|Accumulated depreciation",
  ADD COLUMN property_plant_equip_net_a1b_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3A12|Property, Plant, and Equipment, net of accumulated depreciation (from A1b)",
    ADD COLUMN property_plant_equip_net_a1b DOUBLE COMMENT "F3A12|Property, Plant, and Equipment, net of accumulated depreciation (from A1b)",
  ADD COLUMN tot_rev_investment_return_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B01|Total revenues and investment return",
    ADD COLUMN tot_rev_investment_return DOUBLE COMMENT "F3B01|Total revenues and investment return",
  ADD COLUMN tot_exp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B02|Total expenses",
    ADD COLUMN tot_exp DOUBLE COMMENT "F3B02|Total expenses",
  ADD COLUMN sum_changes_equity_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B03|Sum of specific changes in equity",
    ADD COLUMN sum_changes_equity DOUBLE COMMENT "F3B03|Sum of specific changes in equity",
  ADD COLUMN net_inc_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B04|Net income",
    ADD COLUMN net_inc DOUBLE COMMENT "F3B04|Net income",
  ADD COLUMN other_changes_equity_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B05|Other changes in equity",
    ADD COLUMN other_changes_equity DOUBLE COMMENT "F3B05|Other changes in equity",
  ADD COLUMN equity_beg_year_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B06|Equity, beginning of year",
    ADD COLUMN equity_beg_year DOUBLE COMMENT "F3B06|Equity, beginning of year",
  ADD COLUMN adjustments_beg_net_equity_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B07|Adjustments to beginning net equity",
    ADD COLUMN adjustments_beg_net_equity DOUBLE COMMENT "F3B07|Adjustments to beginning net equity",
  ADD COLUMN equity_end_year_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3B08|Equity, end of year",
    ADD COLUMN equity_end_year DOUBLE COMMENT "F3B08|Equity, end of year",
  ADD COLUMN pell_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C01|Pell grants",
    ADD COLUMN pell_grants BIGINT COMMENT "F3C01|Pell grants",
  ADD COLUMN other_fed_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C02|Other federal grants",
    ADD COLUMN other_fed_grants BIGINT COMMENT "F3C02|Other federal grants",
  ADD COLUMN state_local_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C03|State and local grants",
    ADD COLUMN state_local_grants BIGINT COMMENT "F3C03|State and local grants",
  ADD COLUMN state_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C03A|State grants",
    ADD COLUMN state_grants BIGINT COMMENT "F3C03A|State grants",
  ADD COLUMN local_gov_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C03B|Local government grants",
    ADD COLUMN local_gov_grants BIGINT COMMENT "F3C03B|Local government grants",
  ADD COLUMN inst_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C04|Institutional grants",
    ADD COLUMN inst_grants BIGINT COMMENT "F3C04|Institutional grants",
  ADD COLUMN tot_student_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C05|Total student grants",
    ADD COLUMN tot_student_grants BIGINT COMMENT "F3C05|Total student grants",
  ADD COLUMN disc_allow_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C06|Discounts and allowances applied to tuition and fees",
    ADD COLUMN disc_allow_tuition_fees BIGINT COMMENT "F3C06|Discounts and allowances applied to tuition and fees",
  ADD COLUMN disc_allow_auxiliary_rev_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C07|Discounts and allowances applied to auxiliary enterprise revenues",
    ADD COLUMN disc_allow_auxiliary_rev BIGINT COMMENT "F3C07|Discounts and allowances applied to auxiliary enterprise revenues",
  ADD COLUMN tot_disc_allowances_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C08|Total discounts and allowances",
    ADD COLUMN tot_disc_allowances BIGINT COMMENT "F3C08|Total discounts and allowances",
  ADD COLUMN tot_disc_allow_pell_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C12|Total
 discounts and
 allowances from Pell grants",
    ADD COLUMN tot_disc_allow_pell_grants BIGINT COMMENT "F3C12|Total
 discounts and
 allowances from Pell grants",
  ADD COLUMN disc_allow_pell_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C121|Discounts and allowances from Pell grants applied to tuition and fees",
    ADD COLUMN disc_allow_pell_grants_tuition_fees BIGINT COMMENT "F3C121|Discounts and allowances from Pell grants applied to tuition and fees",
  ADD COLUMN disc_allow_pell_grants_auxiliary_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C122|Discounts and allowances from Pell grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_pell_grants_auxiliary BIGINT COMMENT "F3C122|Discounts and allowances from Pell grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_oth_fed_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C13|Total discounts and allowances from other federal grants",
    ADD COLUMN tot_disc_allow_oth_fed_grants BIGINT COMMENT "F3C13|Total discounts and allowances from other federal grants",
  ADD COLUMN disc_allow_oth_fed_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C131|Discounts and allowances from other federal grants applied to tuition and fees",
    ADD COLUMN disc_allow_oth_fed_grants_tuition_fees BIGINT COMMENT "F3C131|Discounts and allowances from other federal grants applied to tuition and fees",
  ADD COLUMN disc_allow_fed_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C132|Discounts and allowances from other federal grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_fed_grants_aux_ent BIGINT COMMENT "F3C132|Discounts and allowances from other federal grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_state_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C14|Total discounts and allowances from state government grants",
    ADD COLUMN tot_disc_allow_state_grants BIGINT COMMENT "F3C14|Total discounts and allowances from state government grants",
  ADD COLUMN disc_allow_state_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C141|Discounts and allowances from state government grants applied to tuition and fees",
    ADD COLUMN disc_allow_state_grants_tuition_fees BIGINT COMMENT "F3C141|Discounts and allowances from state government grants applied to tuition and fees",
  ADD COLUMN disc_allow_state_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C142|Discounts and allowances from state government grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_state_grants_aux_ent BIGINT COMMENT "F3C142|Discounts and allowances from state government grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_local_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C15|Total discounts and allowances from local government grants",
    ADD COLUMN tot_disc_allow_local_grants BIGINT COMMENT "F3C15|Total discounts and allowances from local government grants",
  ADD COLUMN disc_allow_local_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C151|Discounts and
 allowances from local government grants applied to tuition and fees",
    ADD COLUMN disc_allow_local_grants_tuition_fees BIGINT COMMENT "F3C151|Discounts and
 allowances from local government grants applied to tuition and fees",
  ADD COLUMN disc_allow_local_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C152|Discounts and allowances from local government grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_local_grants_aux_ent BIGINT COMMENT "F3C152|Discounts and allowances from local government grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_endow_gifts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C16|Total discounts and
 allowances from endowments and gifts",
    ADD COLUMN tot_disc_allow_endow_gifts BIGINT COMMENT "F3C16|Total discounts and
 allowances from endowments and gifts",
  ADD COLUMN disc_allow_endow_gifts_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C161|Discounts and 
allowances from endowments and gifts applied to tuition and fees",
    ADD COLUMN disc_allow_endow_gifts_tuition_fees BIGINT COMMENT "F3C161|Discounts and 
allowances from endowments and gifts applied to tuition and fees",
  ADD COLUMN disc_allow_endow_gifts_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C162|Discounts and allowances from endowments and gifts applied to auxiliary enterprises",
    ADD COLUMN disc_allow_endow_gifts_aux_ent BIGINT COMMENT "F3C162|Discounts and allowances from endowments and gifts applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_oth_inst_sources_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C17|Total discounts and allowances from other institutional sources",
    ADD COLUMN tot_disc_allow_oth_inst_sources BIGINT COMMENT "F3C17|Total discounts and allowances from other institutional sources",
  ADD COLUMN disc_allow_oth_inst_sources_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C171|Discounts and
 allowances from other institutional sources applied to tuition and fees",
    ADD COLUMN disc_allow_oth_inst_sources_tuition_fees BIGINT COMMENT "F3C171|Discounts and
 allowances from other institutional sources applied to tuition and fees",
  ADD COLUMN disc_allow_oth_inst_sources_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3C172|Discounts and allowances from other institutional sources applied to auxiliary enterprises",
    ADD COLUMN disc_allow_oth_inst_sources_aux_ent BIGINT COMMENT "F3C172|Discounts and allowances from other institutional sources applied to auxiliary enterprises",
  ADD COLUMN tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D01|Tuition and fees",
    ADD COLUMN tuition_fees BIGINT COMMENT "F3D01|Tuition and fees",
  ADD COLUMN federal_approp_grants_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D02|Federal appropriations, grants and contracts",
    ADD COLUMN federal_approp_grants_contracts BIGINT COMMENT "F3D02|Federal appropriations, grants and contracts",
  ADD COLUMN federal_approp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D02A|Federal appropriations",
    ADD COLUMN federal_approp BIGINT COMMENT "F3D02A|Federal appropriations",
  ADD COLUMN federal_grants_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D02B|Federal grants and contracts",
    ADD COLUMN federal_grants_contracts BIGINT COMMENT "F3D02B|Federal grants and contracts",
  ADD COLUMN state_local_approp_grants_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D03|State and local appropriations, grants and contracts",
    ADD COLUMN state_local_approp_grants_contracts BIGINT COMMENT "F3D03|State and local appropriations, grants and contracts",
  ADD COLUMN state_approp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D03A|State appropriations",
    ADD COLUMN state_approp BIGINT COMMENT "F3D03A|State appropriations",
  ADD COLUMN state_grants_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D03B|State grants and contracts",
    ADD COLUMN state_grants_contracts BIGINT COMMENT "F3D03B|State grants and contracts",
  ADD COLUMN local_gov_approp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D03C|Local government appropriations",
    ADD COLUMN local_gov_approp BIGINT COMMENT "F3D03C|Local government appropriations",
  ADD COLUMN local_gov_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D03D|Local government and contracts",
    ADD COLUMN local_gov_contracts BIGINT COMMENT "F3D03D|Local government and contracts",
  ADD COLUMN private_gifts_grants_contracts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D04|Private gifts, grants, and contracts",
    ADD COLUMN private_gifts_grants_contracts BIGINT COMMENT "F3D04|Private gifts, grants, and contracts",
  ADD COLUMN investment_inc_net_inc_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D05|Investment income and investment gains (losses) included in net income",
    ADD COLUMN investment_inc_net_inc BIGINT COMMENT "F3D05|Investment income and investment gains (losses) included in net income",
  ADD COLUMN sales_educational_activities_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D06|Sales and services of educational activities",
    ADD COLUMN sales_educational_activities BIGINT COMMENT "F3D06|Sales and services of educational activities",
  ADD COLUMN sales_auxiliary_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D07|Sales and services of auxiliary enterprises",
    ADD COLUMN sales_auxiliary_ent DOUBLE COMMENT "F3D07|Sales and services of auxiliary enterprises",
  ADD COLUMN hospital_revenue_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D12|Hospital revenue",
    ADD COLUMN hospital_revenue DOUBLE COMMENT "F3D12|Hospital revenue",
  ADD COLUMN other_revenue_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D08|Other revenue",
    ADD COLUMN other_revenue BIGINT COMMENT "F3D08|Other revenue",
  ADD COLUMN tot_rev_investment_return_2_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3D09|Total revenues and investment return",
    ADD COLUMN tot_rev_investment_return_2 BIGINT COMMENT "F3D09|Total revenues and investment return",
  ADD COLUMN instruction_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E011|Instruction-Total amount",
    ADD COLUMN instruction_tot_amt BIGINT COMMENT "F3E011|Instruction-Total amount",
  ADD COLUMN instruction_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E012|Instruction-Salaries and wages",
    ADD COLUMN instruction_salaries_wages BIGINT COMMENT "F3E012|Instruction-Salaries and wages",
  ADD COLUMN research_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E02A1|Research-Total amount",
    ADD COLUMN research_tot_amt BIGINT COMMENT "F3E02A1|Research-Total amount",
  ADD COLUMN research_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E02A2|Research-Salaries and wages",
    ADD COLUMN research_salaries_wages BIGINT COMMENT "F3E02A2|Research-Salaries and wages",
  ADD COLUMN public_service_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E02B1|Public service-Total amount",
    ADD COLUMN public_service_tot_amt BIGINT COMMENT "F3E02B1|Public service-Total amount",
  ADD COLUMN public_service_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E02B2|Public service-Salaries and wages",
    ADD COLUMN public_service_salaries_wages BIGINT COMMENT "F3E02B2|Public service-Salaries and wages",
  ADD COLUMN academic_support_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03A1|Academic support-Total amount",
    ADD COLUMN academic_support_tot_amt BIGINT COMMENT "F3E03A1|Academic support-Total amount",
  ADD COLUMN academic_support_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03A2|Academic support-Salaries and wages",
    ADD COLUMN academic_support_salaries_wages BIGINT COMMENT "F3E03A2|Academic support-Salaries and wages",
  ADD COLUMN student_service_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03B1|Student service-Total amount",
    ADD COLUMN student_service_tot_amt BIGINT COMMENT "F3E03B1|Student service-Total amount",
  ADD COLUMN student_service_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03B2|Student service-Salaries and wages",
    ADD COLUMN student_service_salaries_wages BIGINT COMMENT "F3E03B2|Student service-Salaries and wages",
  ADD COLUMN inst_support_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03C1|Institutional support-Total amount",
    ADD COLUMN inst_support_tot_amt BIGINT COMMENT "F3E03C1|Institutional support-Total amount",
  ADD COLUMN inst_support_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E03C2|Institutional support-Salaries and wages",
    ADD COLUMN inst_support_salaries_wages BIGINT COMMENT "F3E03C2|Institutional support-Salaries and wages",
  ADD COLUMN auxiliary_ent_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E041|Auxiliary enterprises-Total amount",
    ADD COLUMN auxiliary_ent_tot_amt DOUBLE COMMENT "F3E041|Auxiliary enterprises-Total amount",
  ADD COLUMN auxiliary_ent_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E042|Auxiliary enterprises-Salaries and wages",
    ADD COLUMN auxiliary_ent_salaries_wages DOUBLE COMMENT "F3E042|Auxiliary enterprises-Salaries and wages",
  ADD COLUMN net_grant_aid_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E051|Net grant aid to students-Total amount",
    ADD COLUMN net_grant_aid_tot_amt BIGINT COMMENT "F3E051|Net grant aid to students-Total amount",
  ADD COLUMN hospital_services_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E101|Hospital services-Total amount",
    ADD COLUMN hospital_services_tot_amt DOUBLE COMMENT "F3E101|Hospital services-Total amount",
  ADD COLUMN hospital_services_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E102|Hospital services-Salaries and wages",
    ADD COLUMN hospital_services_salaries_wages DOUBLE COMMENT "F3E102|Hospital services-Salaries and wages",
  ADD COLUMN other_exp_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E061|Other expenses-Total amount",
    ADD COLUMN other_exp_tot_amt BIGINT COMMENT "F3E061|Other expenses-Total amount",
  ADD COLUMN other_exp_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E062|Other expenses-Salaries and wages",
    ADD COLUMN other_exp_salaries_wages BIGINT COMMENT "F3E062|Other expenses-Salaries and wages",
  ADD COLUMN tot_exp_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E071|Total expenses-Total amount",
    ADD COLUMN tot_exp_tot_amt BIGINT COMMENT "F3E071|Total expenses-Total amount",
  ADD COLUMN tot_exp_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E072|Total expenses-Salaries and wages",
    ADD COLUMN tot_exp_salaries_wages BIGINT COMMENT "F3E072|Total expenses-Salaries and wages",
  ADD COLUMN tot_exp_benefits_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E073|Total expenses-Benefits",
    ADD COLUMN tot_exp_benefits BIGINT COMMENT "F3E073|Total expenses-Benefits",
  ADD COLUMN tot_exp_ops_maint_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E074|Total expenses-Operations and maintenance",
    ADD COLUMN tot_exp_ops_maint BIGINT COMMENT "F3E074|Total expenses-Operations and maintenance",
  ADD COLUMN tot_exp_depreciation_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E075|Total expenses-Depreciation",
    ADD COLUMN tot_exp_depreciation BIGINT COMMENT "F3E075|Total expenses-Depreciation",
  ADD COLUMN tot_exp_interest_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E076|Total expenses-Interest",
    ADD COLUMN tot_exp_interest BIGINT COMMENT "F3E076|Total expenses-Interest",
  ADD COLUMN tot_exp_all_oth_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3E077|Total expenses-All other",
    ADD COLUMN tot_exp_all_oth BIGINT COMMENT "F3E077|Total expenses-All other",
  ADD COLUMN federal_inc_tax_exp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3F01|Federal income tax expenses",
    ADD COLUMN federal_inc_tax_exp DOUBLE COMMENT "F3F01|Federal income tax expenses",
  ADD COLUMN state_local_inc_tax_exp_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3F02|State and local income tax expenses",
    ADD COLUMN state_local_inc_tax_exp DOUBLE COMMENT "F3F02|State and local income tax expenses",
    ADD COLUMN designee_paid_tax_exp TINYINT COMMENT "F3F03|Designee who paid the reported tax expenses for the institution",
  ADD COLUMN pretax_inc_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G01|Pretax income",
    ADD COLUMN pretax_inc DOUBLE COMMENT "F3G01|Pretax income",
  ADD COLUMN rev_tot_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G02|Total revenues",
    ADD COLUMN rev_tot DOUBLE COMMENT "F3G02|Total revenues",
  ADD COLUMN equity_tot_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G03|Total equity",
    ADD COLUMN equity_tot DOUBLE COMMENT "F3G03|Total equity",
  ADD COLUMN assets_tot_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G04|Total assets",
    ADD COLUMN assets_tot DOUBLE COMMENT "F3G04|Total assets",
  ADD COLUMN equity_adjusted_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G05|Adjusted equity",
    ADD COLUMN equity_adjusted DOUBLE COMMENT "F3G05|Adjusted equity",
  ADD COLUMN plant_debt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G06|Plant-related debt",
    ADD COLUMN plant_debt DOUBLE COMMENT "F3G06|Plant-related debt",
  ADD COLUMN exp_tot_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F3G07|Total expenses",
    ADD COLUMN exp_tot DOUBLE COMMENT "F3G07|Total expenses";