ALTER TABLE institution_hr_fte_rank_tenure 
    ADD COLUMN faculty_tenure_status SMALLINT COMMENT "FACSTAT|Faculty and tenure status",
  ADD COLUMN all_ranks_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISTOTL|All ranks",
    ADD COLUMN all_ranks SMALLINT COMMENT "SISTOTL|All ranks",
  ADD COLUMN professors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISPROF|Professors",
    ADD COLUMN professors SMALLINT COMMENT "SISPROF|Professors",
  ADD COLUMN associate_professors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISASCP|Associate professors",
    ADD COLUMN associate_professors SMALLINT COMMENT "SISASCP|Associate professors",
  ADD COLUMN assistant_professors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISASTP|Assistant professors",
    ADD COLUMN assistant_professors SMALLINT COMMENT "SISASTP|Assistant professors",
  ADD COLUMN instructors_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISINST|Instructors",
    ADD COLUMN instructors SMALLINT COMMENT "SISINST|Instructors",
  ADD COLUMN lecturers_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISLECT|Lecturers",
    ADD COLUMN lecturers SMALLINT COMMENT "SISLECT|Lecturers",
  ADD COLUMN no_rank_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SISNORK|No academic rank",
    ADD COLUMN no_rank SMALLINT COMMENT "SISNORK|No academic rank";