ALTER TABLE institution_hr_salary 
  ADD COLUMN staff_non_instr_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN01|Full-time non-instructional staff - number",
    ADD COLUMN staff_non_instr_num MEDIUMINT COMMENT "SANIN01|Full-time non-instructional staff - number",
  ADD COLUMN staff_non_instr_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT01|Full-time non-instructional staff - outlays",
    ADD COLUMN staff_non_instr_outlays BIGINT COMMENT "SANIT01|Full-time non-instructional staff - outlays",
  ADD COLUMN research_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN02|Research - number",
    ADD COLUMN research_num MEDIUMINT COMMENT "SANIN02|Research - number",
  ADD COLUMN research_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT02|Research - outlays",
    ADD COLUMN research_outlays BIGINT COMMENT "SANIT02|Research - outlays",
  ADD COLUMN public_service_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN03|Public service - number",
    ADD COLUMN public_service_num MEDIUMINT COMMENT "SANIN03|Public service - number",
  ADD COLUMN public_service_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT03|Public service - Outlays",
    ADD COLUMN public_service_outlays BIGINT COMMENT "SANIT03|Public service - Outlays",
  ADD COLUMN librarians_curators_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN04|Librarians, Curators, Archivists, and Academic Affairs and Other Education Services  - number",
    ADD COLUMN librarians_curators_num MEDIUMINT COMMENT "SANIN04|Librarians, Curators, Archivists, and Academic Affairs and Other Education Services  - number",
  ADD COLUMN librarians_curators_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT04|Librarians, Curators, Archivists and Academic Affairs and Other Education Services - outlays",
    ADD COLUMN librarians_curators_outlays BIGINT COMMENT "SANIT04|Librarians, Curators, Archivists and Academic Affairs and Other Education Services - outlays",
  ADD COLUMN management_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN05|Management - number",
    ADD COLUMN management_num MEDIUMINT COMMENT "SANIN05|Management - number",
  ADD COLUMN management_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT05|Management - outlays",
    ADD COLUMN management_outlays BIGINT COMMENT "SANIT05|Management - outlays",
  ADD COLUMN business_financial_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN06|Business and Financial Operations - number",
    ADD COLUMN business_financial_num MEDIUMINT COMMENT "SANIN06|Business and Financial Operations - number",
  ADD COLUMN business_financial_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT06|Business and Financial Operations - outlays",
    ADD COLUMN business_financial_outlays BIGINT COMMENT "SANIT06|Business and Financial Operations - outlays",
  ADD COLUMN computer_engineering_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN07|Computer, Engineering, and Science - number",
    ADD COLUMN computer_engineering_num MEDIUMINT COMMENT "SANIN07|Computer, Engineering, and Science - number",
  ADD COLUMN computer_engineering_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT07|Computer, Engineering, and Science - outlays",
    ADD COLUMN computer_engineering_outlays BIGINT COMMENT "SANIT07|Computer, Engineering, and Science - outlays",
  ADD COLUMN community_social_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN08|Community, Social  Service, Legal, Arts, Design, Entertainment, Sports and Media - number",
    ADD COLUMN community_social_num MEDIUMINT COMMENT "SANIN08|Community, Social  Service, Legal, Arts, Design, Entertainment, Sports and Media - number",
  ADD COLUMN community_social_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT08|Community, Social  Service, Legal, Arts, Design, Entertainment, Sports and Media - outlays",
    ADD COLUMN community_social_outlays BIGINT COMMENT "SANIT08|Community, Social  Service, Legal, Arts, Design, Entertainment, Sports and Media - outlays",
  ADD COLUMN healthcare_practitioners_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN09|Healthcare Practioners and Technical -number",
    ADD COLUMN healthcare_practitioners_num MEDIUMINT COMMENT "SANIN09|Healthcare Practioners and Technical -number",
  ADD COLUMN healthcare_practitioners_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT09|Healthcare Practioners and Technical - outlays",
    ADD COLUMN healthcare_practitioners_outlays BIGINT COMMENT "SANIT09|Healthcare Practioners and Technical - outlays",
  ADD COLUMN service_num_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN10|Service - number",
    ADD COLUMN service_num MEDIUMINT COMMENT "SANIN10|Service - number",
  ADD COLUMN service_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT10|Service - outlays",
    ADD COLUMN service_outlays BIGINT COMMENT "SANIT10|Service - outlays",
  ADD COLUMN sales_related_number_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN11|Sales and related - number",
    ADD COLUMN sales_related_number MEDIUMINT COMMENT "SANIN11|Sales and related - number",
  ADD COLUMN sales_related_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT11|Sales and related - outlays",
    ADD COLUMN sales_related_outlays BIGINT COMMENT "SANIT11|Sales and related - outlays",
  ADD COLUMN office_admin_support_number_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN12|Office and Administrative Support - number",
    ADD COLUMN office_admin_support_number MEDIUMINT COMMENT "SANIN12|Office and Administrative Support - number",
  ADD COLUMN office_admin_support_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT12|Office and Administrative Support - outlays",
    ADD COLUMN office_admin_support_outlays BIGINT COMMENT "SANIT12|Office and Administrative Support - outlays",
  ADD COLUMN nat_resources_construction_maintenance_number_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN13|Natural Resources, Construction, and Maintenance - number",
    ADD COLUMN nat_resources_construction_maintenance_number MEDIUMINT COMMENT "SANIN13|Natural Resources, Construction, and Maintenance - number",
  ADD COLUMN nat_resources_construction_maintenance_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT13|Natural Resources, Construction, and Maintenance - outlays",
    ADD COLUMN nat_resources_construction_maintenance_outlays BIGINT COMMENT "SANIT13|Natural Resources, Construction, and Maintenance - outlays",
  ADD COLUMN prod_transport_material_moving_number_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIN14|Production, Transportation, and Material Moving - number",
    ADD COLUMN prod_transport_material_moving_number MEDIUMINT COMMENT "SANIN14|Production, Transportation, and Material Moving - number",
  ADD COLUMN prod_transport_material_moving_outlays_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SANIT14|Production, Transportation, and Material Moving - outlays",
    ADD COLUMN prod_transport_material_moving_outlays BIGINT COMMENT "SANIT14|Production, Transportation, and Material Moving - outlays";