ALTER TABLE institution_fin_not_for_profit 
  ADD COLUMN long_term_invs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A01|Long-term investments",
    ADD COLUMN long_term_invs DOUBLE COMMENT "F2A01|Long-term investments",
  ADD COLUMN property_plant_equip_net_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A19|Property, Plant, and Equipment, net of accumulated depreciation",
    ADD COLUMN property_plant_equip_net DOUBLE COMMENT "F2A19|Property, Plant, and Equipment, net of accumulated depreciation",
  ADD COLUMN intangible_assets_net_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A20|Intangible Assets, net of accumulated amortization",
    ADD COLUMN intangible_assets_net DOUBLE COMMENT "F2A20|Intangible Assets, net of accumulated amortization",
  ADD COLUMN tot_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A02|Total assets",
    ADD COLUMN tot_assets DOUBLE COMMENT "F2A02|Total assets",
  ADD COLUMN tot_liabilities_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A03|Total liabilities",
    ADD COLUMN tot_liabilities DOUBLE COMMENT "F2A03|Total liabilities",
  ADD COLUMN debt_property_plant_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A03A|Debt related to Property, Plant, and Equipment",
    ADD COLUMN debt_property_plant_equip DOUBLE COMMENT "F2A03A|Debt related to Property, Plant, and Equipment",
  ADD COLUMN tot_unres_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A04|Total unrestricted net assets",
    ADD COLUMN tot_unres_net_assets DOUBLE COMMENT "F2A04|Total unrestricted net assets",
  ADD COLUMN tot_restr_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A05|Total restricted net assets",
    ADD COLUMN tot_restr_net_assets DOUBLE COMMENT "F2A05|Total restricted net assets",
  ADD COLUMN perm_restr_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A05A|Permanently restricted net assets included in total restricted net assets",
    ADD COLUMN perm_restr_net_assets DOUBLE COMMENT "F2A05A|Permanently restricted net assets included in total restricted net assets",
  ADD COLUMN temp_restr_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A05B|Temporarily restricted net assets",
    ADD COLUMN temp_restr_net_assets DOUBLE COMMENT "F2A05B|Temporarily restricted net assets",
  ADD COLUMN tot_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A06|Total net assets",
    ADD COLUMN tot_net_assets DOUBLE COMMENT "F2A06|Total net assets",
  ADD COLUMN land_improvements_end_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A11|Land  improvements - End of year",
    ADD COLUMN land_improvements_end DOUBLE COMMENT "F2A11|Land  improvements - End of year",
  ADD COLUMN buildings_end_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A12|Buildings - End of year",
    ADD COLUMN buildings_end DOUBLE COMMENT "F2A12|Buildings - End of year",
  ADD COLUMN equipment_end_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A13|Equipment, including art and library collections - End of year",
    ADD COLUMN equipment_end DOUBLE COMMENT "F2A13|Equipment, including art and library collections - End of year",
  ADD COLUMN construction_in_progress_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A15|Construction in Progress",
    ADD COLUMN construction_in_progress DOUBLE COMMENT "F2A15|Construction in Progress",
  ADD COLUMN other_plant_property_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A16|Other plant, property and equipment",
    ADD COLUMN other_plant_property_equip DOUBLE COMMENT "F2A16|Other plant, property and equipment",
  ADD COLUMN tot_plant_property_equip_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A17|Total Plant, Property, and Equipment",
    ADD COLUMN tot_plant_property_equip DOUBLE COMMENT "F2A17|Total Plant, Property, and Equipment",
  ADD COLUMN accumulated_depreciation_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2A18|Accumulated depreciation",
    ADD COLUMN accumulated_depreciation DOUBLE COMMENT "F2A18|Accumulated depreciation",
  ADD COLUMN tot_revs_inv_return_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B01|Total revenues and investment return",
    ADD COLUMN tot_revs_inv_return DOUBLE COMMENT "F2B01|Total revenues and investment return",
  ADD COLUMN tot_expenses_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B02|Total expenses",
    ADD COLUMN tot_expenses DOUBLE COMMENT "F2B02|Total expenses",
  ADD COLUMN other_changes_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B03|Other specific changes in net assets",
    ADD COLUMN other_changes_net_assets DOUBLE COMMENT "F2B03|Other specific changes in net assets",
  ADD COLUMN tot_change_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B04|Total change in net assets",
    ADD COLUMN tot_change_net_assets DOUBLE COMMENT "F2B04|Total change in net assets",
  ADD COLUMN net_assets_beg_yr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B05|Net assets, beginning of the year",
    ADD COLUMN net_assets_beg_yr DOUBLE COMMENT "F2B05|Net assets, beginning of the year",
  ADD COLUMN adjustments_beg_yr_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B06|Adjustments to beginning of year net assets",
    ADD COLUMN adjustments_beg_yr_net_assets DOUBLE COMMENT "F2B06|Adjustments to beginning of year net assets",
  ADD COLUMN net_assets_end_yr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2B07|Net assets, end of the year",
    ADD COLUMN net_assets_end_yr DOUBLE COMMENT "F2B07|Net assets, end of the year",
  ADD COLUMN pell_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C01|Pell grants",
    ADD COLUMN pell_grants BIGINT COMMENT "F2C01|Pell grants",
  ADD COLUMN other_fed_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C02|Other federal grants",
    ADD COLUMN other_fed_grants BIGINT COMMENT "F2C02|Other federal grants",
  ADD COLUMN state_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C03|State grants",
    ADD COLUMN state_grants BIGINT COMMENT "F2C03|State grants",
  ADD COLUMN local_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C04|Local grants",
    ADD COLUMN local_grants BIGINT COMMENT "F2C04|Local grants",
  ADD COLUMN inst_grants_funded_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C05|Institutional grants (funded)",
    ADD COLUMN inst_grants_funded BIGINT COMMENT "F2C05|Institutional grants (funded)",
  ADD COLUMN inst_grants_unfunded_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C06|Institutional grants (unfunded)",
    ADD COLUMN inst_grants_unfunded BIGINT COMMENT "F2C06|Institutional grants (unfunded)",
  ADD COLUMN tot_student_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C07|Total student grants",
    ADD COLUMN tot_student_grants BIGINT COMMENT "F2C07|Total student grants",
  ADD COLUMN allow_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C08|Allowances applied to tuition and fees",
    ADD COLUMN allow_tuition_fees BIGINT COMMENT "F2C08|Allowances applied to tuition and fees",
  ADD COLUMN allow_auxiliary_revs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C09|Allowances applied to auxiliary enterprise revenues",
    ADD COLUMN allow_auxiliary_revs BIGINT COMMENT "F2C09|Allowances applied to auxiliary enterprise revenues",
  ADD COLUMN tot_disc_allowances_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C10|Total discounts and allowances",
    ADD COLUMN tot_disc_allowances BIGINT COMMENT "F2C10|Total discounts and allowances",
  ADD COLUMN tot_disc_allow_pell_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C12|Total discounts and
 allowances from Pell grants",
    ADD COLUMN tot_disc_allow_pell BIGINT COMMENT "F2C12|Total discounts and
 allowances from Pell grants",
  ADD COLUMN disc_allow_pell_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C121|Discounts and
 allowances from Pell grants applied to tuition and fees",
    ADD COLUMN disc_allow_pell_tuition_fees BIGINT COMMENT "F2C121|Discounts and
 allowances from Pell grants applied to tuition and fees",
  ADD COLUMN disc_allow_pell_auxiliary_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C122|Discounts and allowances from Pell grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_pell_auxiliary BIGINT COMMENT "F2C122|Discounts and allowances from Pell grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_fed_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C13|Total discounts and allowances from other federal grants",
    ADD COLUMN tot_disc_allow_fed BIGINT COMMENT "F2C13|Total discounts and allowances from other federal grants",
  ADD COLUMN disc_allow_fed_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C131|Discounts and allowances from other federal grants applied to tuition and fees",
    ADD COLUMN disc_allow_fed_grants_tuition_fees BIGINT COMMENT "F2C131|Discounts and allowances from other federal grants applied to tuition and fees",
  ADD COLUMN disc_allow_fed_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C132|Discounts and allowances from other federal grants applied to auxiliary
 enterprises",
    ADD COLUMN disc_allow_fed_grants_aux_ent BIGINT COMMENT "F2C132|Discounts and allowances from other federal grants applied to auxiliary
 enterprises",
  ADD COLUMN tot_disc_allow_state_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C14|Total discounts and
 allowances from state government grants",
    ADD COLUMN tot_disc_allow_state_grants BIGINT COMMENT "F2C14|Total discounts and
 allowances from state government grants",
  ADD COLUMN disc_allow_state_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C141|Discounts and
 allowances from state government grants applied to tuition and fees",
    ADD COLUMN disc_allow_state_grants_tuition_fees BIGINT COMMENT "F2C141|Discounts and
 allowances from state government grants applied to tuition and fees",
  ADD COLUMN disc_allow_state_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C142|Discounts and allowances from state government grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_state_grants_aux_ent BIGINT COMMENT "F2C142|Discounts and allowances from state government grants applied to auxiliary enterprises",
  ADD COLUMN disc_allow_local_grants_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C15|Discounts and allowances from local government grants",
    ADD COLUMN disc_allow_local_grants BIGINT COMMENT "F2C15|Discounts and allowances from local government grants",
  ADD COLUMN disc_allow_local_grants_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C151|Discounts and allowances from local government grants applied to tuition and fees",
    ADD COLUMN disc_allow_local_grants_tuition_fees BIGINT COMMENT "F2C151|Discounts and allowances from local government grants applied to tuition and fees",
  ADD COLUMN disc_allow_local_grants_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C152|Discounts and allowances from local government grants applied to auxiliary enterprises",
    ADD COLUMN disc_allow_local_grants_aux_ent BIGINT COMMENT "F2C152|Discounts and allowances from local government grants applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_endowments_gifts_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C16|Total discounts and allowances from endowments and gifts",
    ADD COLUMN tot_disc_allow_endowments_gifts BIGINT COMMENT "F2C16|Total discounts and allowances from endowments and gifts",
  ADD COLUMN disc_allow_endowments_gifts_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C161|Discounts and allowances from endowments and gifts applied to tuition and fees",
    ADD COLUMN disc_allow_endowments_gifts_tuition_fees BIGINT COMMENT "F2C161|Discounts and allowances from endowments and gifts applied to tuition and fees",
  ADD COLUMN disc_allow_endowments_gifts_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C162|Discounts and allowances from endowments and gifts applied to auxiliary enterprises",
    ADD COLUMN disc_allow_endowments_gifts_aux_ent BIGINT COMMENT "F2C162|Discounts and allowances from endowments and gifts applied to auxiliary enterprises",
  ADD COLUMN tot_disc_allow_other_inst_sources_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C17|Total discounts and allowances from other institutional sources",
    ADD COLUMN tot_disc_allow_other_inst_sources BIGINT COMMENT "F2C17|Total discounts and allowances from other institutional sources",
  ADD COLUMN disc_allow_other_inst_sources_tuition_fees_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C171|Discounts and allowances from other institutional sources applied to tuition and fees",
    ADD COLUMN disc_allow_other_inst_sources_tuition_fees BIGINT COMMENT "F2C171|Discounts and allowances from other institutional sources applied to tuition and fees",
  ADD COLUMN disc_allow_other_inst_sources_aux_ent_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2C172|Discounts and allowances from other institutional sources applied to auxiliary enterprises",
    ADD COLUMN disc_allow_other_inst_sources_aux_ent BIGINT COMMENT "F2C172|Discounts and allowances from other institutional sources applied to auxiliary enterprises",
  ADD COLUMN tuition_fees_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D01|Tuition and fees - Total",
    ADD COLUMN tuition_fees_total BIGINT COMMENT "F2D01|Tuition and fees - Total",
  ADD COLUMN tuition_fees_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D012|Tuition and fees - Unrestricted",
    ADD COLUMN tuition_fees_unres BIGINT COMMENT "F2D012|Tuition and fees - Unrestricted",
  ADD COLUMN tuition_fees_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D013|Tuition and fees - Temporarily restricted",
    ADD COLUMN tuition_fees_temp_restr BIGINT COMMENT "F2D013|Tuition and fees - Temporarily restricted",
  ADD COLUMN tuition_fees_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D014|Tuition and fees - Permanently restricted",
    ADD COLUMN tuition_fees_perm_restr BIGINT COMMENT "F2D014|Tuition and fees - Permanently restricted",
  ADD COLUMN fed_appropriations_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D02|Federal appropriations - Total",
    ADD COLUMN fed_appropriations_total BIGINT COMMENT "F2D02|Federal appropriations - Total",
  ADD COLUMN fed_appropriations_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D022|Federal appropriations - Unrestricted",
    ADD COLUMN fed_appropriations_unres BIGINT COMMENT "F2D022|Federal appropriations - Unrestricted",
  ADD COLUMN fed_app_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D023|Federal appropriations - Temporarily restricted",
    ADD COLUMN fed_app_temp_restr BIGINT COMMENT "F2D023|Federal appropriations - Temporarily restricted",
  ADD COLUMN fed_app_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D024|Federal appropriations - Permanently restricted",
    ADD COLUMN fed_app_perm_restr BIGINT COMMENT "F2D024|Federal appropriations - Permanently restricted",
  ADD COLUMN state_app_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D03|State appropriations - Total",
    ADD COLUMN state_app_total BIGINT COMMENT "F2D03|State appropriations - Total",
  ADD COLUMN state_app_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D032|State appropriations - Unrestricted",
    ADD COLUMN state_app_unres BIGINT COMMENT "F2D032|State appropriations - Unrestricted",
  ADD COLUMN state_app_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D033|State appropriations - Temporarily restricted",
    ADD COLUMN state_app_temp_restr BIGINT COMMENT "F2D033|State appropriations - Temporarily restricted",
  ADD COLUMN state_app_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D034|State appropriations - Permanently restricted",
    ADD COLUMN state_app_perm_restr BIGINT COMMENT "F2D034|State appropriations - Permanently restricted",
  ADD COLUMN local_app_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D04|Local appropriations - Total",
    ADD COLUMN local_app_total BIGINT COMMENT "F2D04|Local appropriations - Total",
  ADD COLUMN local_app_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D042|Local appropriations - Unrestricted",
    ADD COLUMN local_app_unres BIGINT COMMENT "F2D042|Local appropriations - Unrestricted",
  ADD COLUMN local_app_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D043|Local appropriations -  Temporarily restricted",
    ADD COLUMN local_app_temp_restr BIGINT COMMENT "F2D043|Local appropriations -  Temporarily restricted",
  ADD COLUMN local_app_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D044|Local appropriations - Permanently restricted",
    ADD COLUMN local_app_perm_restr BIGINT COMMENT "F2D044|Local appropriations - Permanently restricted",
  ADD COLUMN fed_grants_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D05|Federal grants and contracts - Total",
    ADD COLUMN fed_grants_total BIGINT COMMENT "F2D05|Federal grants and contracts - Total",
  ADD COLUMN fed_grants_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D052|Federal grants and contracts - Unrestricted",
    ADD COLUMN fed_grants_unres BIGINT COMMENT "F2D052|Federal grants and contracts - Unrestricted",
  ADD COLUMN fed_grants_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D053|Federal grants and contracts  - Temporarily restricted",
    ADD COLUMN fed_grants_temp_restr BIGINT COMMENT "F2D053|Federal grants and contracts  - Temporarily restricted",
  ADD COLUMN fed_grants_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D054|Federal grants and contracts - Pemanently restricted",
    ADD COLUMN fed_grants_perm_restr BIGINT COMMENT "F2D054|Federal grants and contracts - Pemanently restricted",
  ADD COLUMN state_grants_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D06|State grants and contracts - Total",
    ADD COLUMN state_grants_total BIGINT COMMENT "F2D06|State grants and contracts - Total",
  ADD COLUMN state_grants_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D062|State grants and contracts - Unrestricted",
    ADD COLUMN state_grants_unres BIGINT COMMENT "F2D062|State grants and contracts - Unrestricted",
  ADD COLUMN state_grants_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D063|State grants and contracts - Temporarily restricted",
    ADD COLUMN state_grants_temp_restr BIGINT COMMENT "F2D063|State grants and contracts - Temporarily restricted",
  ADD COLUMN state_grants_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D064|State grants and contracts - Permanently restricted",
    ADD COLUMN state_grants_perm_restr BIGINT COMMENT "F2D064|State grants and contracts - Permanently restricted",
  ADD COLUMN local_grants_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D07|Local grants and contracts - Total",
    ADD COLUMN local_grants_total BIGINT COMMENT "F2D07|Local grants and contracts - Total",
  ADD COLUMN local_grants_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D072|Local grants and contracts - Unrestricted",
    ADD COLUMN local_grants_unres BIGINT COMMENT "F2D072|Local grants and contracts - Unrestricted",
  ADD COLUMN local_grants_cntrcts_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D073|Local grants and contracts - Temporarily restricted",
    ADD COLUMN local_grants_cntrcts_temp_restr BIGINT COMMENT "F2D073|Local grants and contracts - Temporarily restricted",
  ADD COLUMN local_grants_cntrcts_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D074|Local grants and contracts  - Permanently restricted",
    ADD COLUMN local_grants_cntrcts_perm_restr BIGINT COMMENT "F2D074|Local grants and contracts  - Permanently restricted",
  ADD COLUMN priv_gifts_grants_cntrcts_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D08|Private gifts, grants, and contracts - Total",
    ADD COLUMN priv_gifts_grants_cntrcts_total BIGINT COMMENT "F2D08|Private gifts, grants, and contracts - Total",
  ADD COLUMN priv_gifts_grants_cntrcts_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D082|Private gifts, grants, and contracts - Unrestricted",
    ADD COLUMN priv_gifts_grants_cntrcts_unres BIGINT COMMENT "F2D082|Private gifts, grants, and contracts - Unrestricted",
  ADD COLUMN priv_gifts_grants_cntrcts_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D083|Private gifts, grants and contracts - Temporarily restricted",
    ADD COLUMN priv_gifts_grants_cntrcts_temp_restr BIGINT COMMENT "F2D083|Private gifts, grants and contracts - Temporarily restricted",
  ADD COLUMN priv_gifts_grants_cntrcts_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D084|Private gifts, grants, and contracts - Permanently restricted",
    ADD COLUMN priv_gifts_grants_cntrcts_perm_restr BIGINT COMMENT "F2D084|Private gifts, grants, and contracts - Permanently restricted",
  ADD COLUMN priv_gifts_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D08A|Private gifts - Total",
    ADD COLUMN priv_gifts_total BIGINT COMMENT "F2D08A|Private gifts - Total",
  ADD COLUMN priv_gifts_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D082A|Private gifts - Unrestricted",
    ADD COLUMN priv_gifts_unres BIGINT COMMENT "F2D082A|Private gifts - Unrestricted",
  ADD COLUMN priv_gifts_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D083A|Private gifts - Temporarily restricted",
    ADD COLUMN priv_gifts_temp_restr BIGINT COMMENT "F2D083A|Private gifts - Temporarily restricted",
  ADD COLUMN priv_gifts_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D084A|Private gifts - Permanentlly restricted",
    ADD COLUMN priv_gifts_perm_restr BIGINT COMMENT "F2D084A|Private gifts - Permanentlly restricted",
  ADD COLUMN priv_grants_cntrcts_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D08B|Private grants and contracts - Total",
    ADD COLUMN priv_grants_cntrcts_total BIGINT COMMENT "F2D08B|Private grants and contracts - Total",
  ADD COLUMN priv_grants_cntrcts_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D082B|Private grants and contracts - Unrestricted",
    ADD COLUMN priv_grants_cntrcts_unres BIGINT COMMENT "F2D082B|Private grants and contracts - Unrestricted",
  ADD COLUMN priv_grants_cntrcts_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D083B|Private grants and contracts - Temporarily restricted",
    ADD COLUMN priv_grants_cntrcts_temp_restr BIGINT COMMENT "F2D083B|Private grants and contracts - Temporarily restricted",
  ADD COLUMN priv_grants_cntrcts_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D084B|Private grants, and contracts - Permanently restricted",
    ADD COLUMN priv_grants_cntrcts_perm_restr BIGINT COMMENT "F2D084B|Private grants, and contracts - Permanently restricted",
  ADD COLUMN contrib_affiliated_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D09|Contributions from affiliated entities - Total",
    ADD COLUMN contrib_affiliated_total BIGINT COMMENT "F2D09|Contributions from affiliated entities - Total",
  ADD COLUMN contrib_affiliated_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D092|Contributions from affiliated entities - Unrestricted",
    ADD COLUMN contrib_affiliated_unres BIGINT COMMENT "F2D092|Contributions from affiliated entities - Unrestricted",
  ADD COLUMN contrib_affiliated_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D093|Contributions from affiliated entities - Temporarily restricted",
    ADD COLUMN contrib_affiliated_temp_restr BIGINT COMMENT "F2D093|Contributions from affiliated entities - Temporarily restricted",
  ADD COLUMN contrib_affiliated_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D094|Contributions from affiliated entities - Permanently restricted",
    ADD COLUMN contrib_affiliated_perm_restr BIGINT COMMENT "F2D094|Contributions from affiliated entities - Permanently restricted",
  ADD COLUMN investment_return_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D10|Investment return - Total",
    ADD COLUMN investment_return_total BIGINT COMMENT "F2D10|Investment return - Total",
  ADD COLUMN investment_return_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D102|Investment return - Unrestricted",
    ADD COLUMN investment_return_unres BIGINT COMMENT "F2D102|Investment return - Unrestricted",
  ADD COLUMN investment_return_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D103|Investment return - Temporarily restricted",
    ADD COLUMN investment_return_temp_restr BIGINT COMMENT "F2D103|Investment return - Temporarily restricted",
  ADD COLUMN investment_return_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D104|Investment return - Permanently restricted",
    ADD COLUMN investment_return_perm_restr BIGINT COMMENT "F2D104|Investment return - Permanently restricted",
  ADD COLUMN sales_edu_activities_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D11|Sales and services of educational activities - Total",
    ADD COLUMN sales_edu_activities_total BIGINT COMMENT "F2D11|Sales and services of educational activities - Total",
  ADD COLUMN sales_edu_activities_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D112|Sales and services of educational activities - Unrestricted",
    ADD COLUMN sales_edu_activities_unres BIGINT COMMENT "F2D112|Sales and services of educational activities - Unrestricted",
  ADD COLUMN sales_aux_ent_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D12|Sales and services of auxiliary enterprises - Total",
    ADD COLUMN sales_aux_ent_total DOUBLE COMMENT "F2D12|Sales and services of auxiliary enterprises - Total",
  ADD COLUMN sales_aux_ent_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D122|Sales and services of auxiliary enterprises - Unrestricted",
    ADD COLUMN sales_aux_ent_unres DOUBLE COMMENT "F2D122|Sales and services of auxiliary enterprises - Unrestricted",
  ADD COLUMN hospital_rev_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D13|Hospital revenue - Total",
    ADD COLUMN hospital_rev_total DOUBLE COMMENT "F2D13|Hospital revenue - Total",
  ADD COLUMN hospital_rev_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D132|Hospital revenue - Unrestricted",
    ADD COLUMN hospital_rev_unres DOUBLE COMMENT "F2D132|Hospital revenue - Unrestricted",
  ADD COLUMN ind_ops_rev_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D14|Independent operations revenue - Total",
    ADD COLUMN ind_ops_rev_total DOUBLE COMMENT "F2D14|Independent operations revenue - Total",
  ADD COLUMN ind_ops_rev_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D142|Independent operations revenue - Unrestricted",
    ADD COLUMN ind_ops_rev_unres DOUBLE COMMENT "F2D142|Independent operations revenue - Unrestricted",
  ADD COLUMN ind_ops_rev_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D143|Independent operations revenue - Temporarily restricted",
    ADD COLUMN ind_ops_rev_temp_restr DOUBLE COMMENT "F2D143|Independent operations revenue - Temporarily restricted",
  ADD COLUMN ind_ops_rev_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D144|Independent operations revenue - Permanently restricted",
    ADD COLUMN ind_ops_rev_perm_restr DOUBLE COMMENT "F2D144|Independent operations revenue - Permanently restricted",
  ADD COLUMN other_rev_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D15|Other revenue - Total",
    ADD COLUMN other_rev_total BIGINT COMMENT "F2D15|Other revenue - Total",
  ADD COLUMN other_rev_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D152|Other revenue - Unrestricted",
    ADD COLUMN other_rev_unres BIGINT COMMENT "F2D152|Other revenue - Unrestricted",
  ADD COLUMN other_rev_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D153|Other revenue - Temporarily restricted",
    ADD COLUMN other_rev_temp_restr BIGINT COMMENT "F2D153|Other revenue - Temporarily restricted",
  ADD COLUMN other_rev_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D154|Other revenue - Permanently restricted",
    ADD COLUMN other_rev_perm_restr BIGINT COMMENT "F2D154|Other revenue - Permanently restricted",
  ADD COLUMN tot_revs_inv_return_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D16|Total revenues and investment return - Total",
    ADD COLUMN tot_revs_inv_return_total BIGINT COMMENT "F2D16|Total revenues and investment return - Total",
  ADD COLUMN tot_revs_inv_return_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D162|Total revenues and investment return - Unrestricted",
    ADD COLUMN tot_revs_inv_return_unres BIGINT COMMENT "F2D162|Total revenues and investment return - Unrestricted",
  ADD COLUMN tot_revs_inv_return_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D163|Total revenues and investment return - Temporarily restricted",
    ADD COLUMN tot_revs_inv_return_temp_restr BIGINT COMMENT "F2D163|Total revenues and investment return - Temporarily restricted",
  ADD COLUMN tot_revs_inv_return_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D164|Total revenues and investment return - Permanently restricted",
    ADD COLUMN tot_revs_inv_return_perm_restr BIGINT COMMENT "F2D164|Total revenues and investment return - Permanently restricted",
  ADD COLUMN net_assets_released_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D17|Net assets released from restriction - Total",
    ADD COLUMN net_assets_released_total BIGINT COMMENT "F2D17|Net assets released from restriction - Total",
  ADD COLUMN net_assets_released_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D172|Net assets released from restriction - Unrestricted",
    ADD COLUMN net_assets_released_unres BIGINT COMMENT "F2D172|Net assets released from restriction - Unrestricted",
  ADD COLUMN net_assets_released_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D173|Net assets released from restriction - Temporarily restricted",
    ADD COLUMN net_assets_released_temp_restr BIGINT COMMENT "F2D173|Net assets released from restriction - Temporarily restricted",
  ADD COLUMN net_assets_released_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D174|Net assets released from restriction - Permanently restricted",
    ADD COLUMN net_assets_released_perm_restr BIGINT COMMENT "F2D174|Net assets released from restriction - Permanently restricted",
  ADD COLUMN net_tot_revs_after_assets_released_total_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D18|Net total revenues, after assets released from restriction - Total",
    ADD COLUMN net_tot_revs_after_assets_released_total BIGINT COMMENT "F2D18|Net total revenues, after assets released from restriction - Total",
  ADD COLUMN net_tot_revs_after_assets_released_unres_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D182|Net total revenues, after assets released from restriction - Unrestricted",
    ADD COLUMN net_tot_revs_after_assets_released_unres BIGINT COMMENT "F2D182|Net total revenues, after assets released from restriction - Unrestricted",
  ADD COLUMN net_tot_revs_after_assets_released_temp_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D183|Net total revenues, after assets released from restriction - Temporarily restricted",
    ADD COLUMN net_tot_revs_after_assets_released_temp_restr BIGINT COMMENT "F2D183|Net total revenues, after assets released from restriction - Temporarily restricted",
  ADD COLUMN net_tot_revs_after_assets_released_perm_restr_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2D184|Net total revenues, after assets released from restriction - Permanently restricted",
    ADD COLUMN net_tot_revs_after_assets_released_perm_restr BIGINT COMMENT "F2D184|Net total revenues, after assets released from restriction - Permanently restricted",
  ADD COLUMN instruction_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E011|Instruction-Total amount",
    ADD COLUMN instruction_tot_amt BIGINT COMMENT "F2E011|Instruction-Total amount",
  ADD COLUMN instruction_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E012|Instruction-Salaries and wages",
    ADD COLUMN instruction_salaries_wages BIGINT COMMENT "F2E012|Instruction-Salaries and wages",
  ADD COLUMN research_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E021|Research-Total amount",
    ADD COLUMN research_tot_amt BIGINT COMMENT "F2E021|Research-Total amount",
  ADD COLUMN research_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E022|Research-Salaries and wages",
    ADD COLUMN research_salaries_wages BIGINT COMMENT "F2E022|Research-Salaries and wages",
  ADD COLUMN public_service_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E031|Public service-Total amount",
    ADD COLUMN public_service_tot_amt BIGINT COMMENT "F2E031|Public service-Total amount",
  ADD COLUMN public_service_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E032|Public service-Salaries and wages",
    ADD COLUMN public_service_salaries_wages BIGINT COMMENT "F2E032|Public service-Salaries and wages",
  ADD COLUMN academic_support_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E041|Academic support-Total amount",
    ADD COLUMN academic_support_tot_amt BIGINT COMMENT "F2E041|Academic support-Total amount",
  ADD COLUMN academic_support_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E042|Academic support-Salaries and wages",
    ADD COLUMN academic_support_salaries_wages BIGINT COMMENT "F2E042|Academic support-Salaries and wages",
  ADD COLUMN student_service_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E051|Student service-Total amount",
    ADD COLUMN student_service_tot_amt BIGINT COMMENT "F2E051|Student service-Total amount",
  ADD COLUMN student_service_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E052|Student service-Salaries and wages",
    ADD COLUMN student_service_salaries_wages BIGINT COMMENT "F2E052|Student service-Salaries and wages",
  ADD COLUMN institutional_support_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E061|Institutional support-Total amount",
    ADD COLUMN institutional_support_tot_amt BIGINT COMMENT "F2E061|Institutional support-Total amount",
  ADD COLUMN institutional_support_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E062|Institutional support-Salaries and wages",
    ADD COLUMN institutional_support_salaries_wages BIGINT COMMENT "F2E062|Institutional support-Salaries and wages",
  ADD COLUMN aux_ent_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E071|Auxiliary enterprises-Total amount",
    ADD COLUMN aux_ent_tot_amt DOUBLE COMMENT "F2E071|Auxiliary enterprises-Total amount",
  ADD COLUMN aux_ent_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E072|Auxiliary enterprises-Salaries and wages",
    ADD COLUMN aux_ent_salaries_wages DOUBLE COMMENT "F2E072|Auxiliary enterprises-Salaries and wages",
  ADD COLUMN net_grant_aid_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E081|Net grant aid to students-Total amount",
    ADD COLUMN net_grant_aid_tot_amt BIGINT COMMENT "F2E081|Net grant aid to students-Total amount",
  ADD COLUMN hospital_services_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E091|Hospital services-Total amount",
    ADD COLUMN hospital_services_tot_amt DOUBLE COMMENT "F2E091|Hospital services-Total amount",
  ADD COLUMN hospital_services_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E092|Hospital services-Salaries and wages",
    ADD COLUMN hospital_services_salaries_wages DOUBLE COMMENT "F2E092|Hospital services-Salaries and wages",
  ADD COLUMN ind_ops_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E101|Independent operations-Total Amount",
    ADD COLUMN ind_ops_tot_amt DOUBLE COMMENT "F2E101|Independent operations-Total Amount",
  ADD COLUMN ind_ops_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E102|Independent operations-Salaries and wages",
    ADD COLUMN ind_ops_salaries_wages DOUBLE COMMENT "F2E102|Independent operations-Salaries and wages",
  ADD COLUMN other_exp_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E121|Other expenses-Total amount",
    ADD COLUMN other_exp_tot_amt BIGINT COMMENT "F2E121|Other expenses-Total amount",
  ADD COLUMN other_exp_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E122|Other expenses-Salaries and wages",
    ADD COLUMN other_exp_salaries_wages BIGINT COMMENT "F2E122|Other expenses-Salaries and wages",
  ADD COLUMN tot_exp_tot_amt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E131|Total expenses-Total amount",
    ADD COLUMN tot_exp_tot_amt BIGINT COMMENT "F2E131|Total expenses-Total amount",
  ADD COLUMN tot_exp_salaries_wages_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E132|Total expenses-Salaries and wages",
    ADD COLUMN tot_exp_salaries_wages BIGINT COMMENT "F2E132|Total expenses-Salaries and wages",
  ADD COLUMN tot_exp_benefits_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E133|Total expenses-Benefits",
    ADD COLUMN tot_exp_benefits BIGINT COMMENT "F2E133|Total expenses-Benefits",
  ADD COLUMN tot_exp_operation_maintenance_plant_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E134|Total expenses-Operation and maintenance of plant",
    ADD COLUMN tot_exp_operation_maintenance_plant BIGINT COMMENT "F2E134|Total expenses-Operation and maintenance of plant",
  ADD COLUMN tot_exp_depreciation_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E135|Total expenses-Depreciation",
    ADD COLUMN tot_exp_depreciation BIGINT COMMENT "F2E135|Total expenses-Depreciation",
  ADD COLUMN tot_exp_interest_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E136|Total expenses-Interest",
    ADD COLUMN tot_exp_interest BIGINT COMMENT "F2E136|Total expenses-Interest",
  ADD COLUMN tot_exp_all_other_nat_class_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2E137|Total expenses-All other natural classification",
    ADD COLUMN tot_exp_all_other_nat_class BIGINT COMMENT "F2E137|Total expenses-All other natural classification",
    ADD COLUMN endow_assets_owned TINYINT COMMENT "F2FHA|Does this institution or any of its foundations or other affiliated organizations own endowment assets ?",
  ADD COLUMN endow_assets_beg_fy_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H01|Value of endowment assets at the beginning of the fiscal year",
    ADD COLUMN endow_assets_beg_fy DOUBLE COMMENT "F2H01|Value of endowment assets at the beginning of the fiscal year",
  ADD COLUMN endow_assets_end_fy_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H02|Value of endowment assets at the end of the fiscal year",
    ADD COLUMN endow_assets_end_fy DOUBLE COMMENT "F2H02|Value of endowment assets at the end of the fiscal year",
  ADD COLUMN change_endow_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H03|Change in value of endowment net assets",
    ADD COLUMN change_endow_net_assets DOUBLE COMMENT "F2H03|Change in value of endowment net assets",
  ADD COLUMN new_gifts_additions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H03A|New gifts and additions",
    ADD COLUMN new_gifts_additions DOUBLE COMMENT "F2H03A|New gifts and additions",
  ADD COLUMN endow_net_inv_return_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H03B|Endowment net investment return",
    ADD COLUMN endow_net_inv_return DOUBLE COMMENT "F2H03B|Endowment net investment return",
  ADD COLUMN spending_distribution_current_use_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H03C|Spending distribution for current use",
    ADD COLUMN spending_distribution_current_use DOUBLE COMMENT "F2H03C|Spending distribution for current use",
  ADD COLUMN other_changes_value_endow_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2H03D|Other changes in value of endowment net assets",
    ADD COLUMN other_changes_value_endow_net_assets DOUBLE COMMENT "F2H03D|Other changes in value of endowment net assets",
  ADD COLUMN change_unres_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I01|Change in unrestricted net assets",
    ADD COLUMN change_unres_net_assets DOUBLE COMMENT "F2I01|Change in unrestricted net assets",
  ADD COLUMN tot_unres_operating_revs_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I02|Total unrestricted operating revenues",
    ADD COLUMN tot_unres_operating_revs DOUBLE COMMENT "F2I02|Total unrestricted operating revenues",
  ADD COLUMN change_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I03|Change in net assets",
    ADD COLUMN change_net_assets DOUBLE COMMENT "F2I03|Change in net assets",
  ADD COLUMN tot_net_assets_2_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I04|Total net assets",
    ADD COLUMN tot_net_assets_2 DOUBLE COMMENT "F2I04|Total net assets",
  ADD COLUMN expendable_net_assets_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I05|Expendable net assets",
    ADD COLUMN expendable_net_assets DOUBLE COMMENT "F2I05|Expendable net assets",
  ADD COLUMN plant_related_debt_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I06|Plant-related debt",
    ADD COLUMN plant_related_debt DOUBLE COMMENT "F2I06|Plant-related debt",
  ADD COLUMN tot_expenses_2_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "F2I07|Total expenses",
    ADD COLUMN tot_expenses_2 DOUBLE COMMENT "F2I07|Total expenses";