ALTER TABLE institution_gr_lt2yr 
  ADD COLUMN revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_10|Revised Cohort",
    ADD COLUMN revised_cohort MEDIUMINT COMMENT "LINE_10|Revised Cohort",
  ADD COLUMN exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_45|Exclusions",
    ADD COLUMN exclusions MEDIUMINT COMMENT "LINE_45|Exclusions",
  ADD COLUMN adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_50|Adjusted cohort (revised cohort minus exclusions)",
    ADD COLUMN adjusted_cohort MEDIUMINT COMMENT "LINE_50|Adjusted cohort (revised cohort minus exclusions)",
  ADD COLUMN completers_100pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_55|Completers within 100% of norm time",
    ADD COLUMN completers_100pct_norm_time MEDIUMINT COMMENT "LINE_55|Completers within 100% of norm time",
  ADD COLUMN completers_150pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_11|Completers within 150% of norm time",
    ADD COLUMN completers_150pct_norm_time MEDIUMINT COMMENT "LINE_11|Completers within 150% of norm time",
  ADD COLUMN transfer_out_students_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_30|Transfer-out students",
    ADD COLUMN transfer_out_students MEDIUMINT COMMENT "LINE_30|Transfer-out students",
  ADD COLUMN still_enrolled_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_51|Still enrolled",
    ADD COLUMN still_enrolled MEDIUMINT COMMENT "LINE_51|Still enrolled",
  ADD COLUMN no_longer_enrolled_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "LINE_52|No longer enrolled",
    ADD COLUMN no_longer_enrolled MEDIUMINT COMMENT "LINE_52|No longer enrolled",
  ADD COLUMN pell_recipients_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGLIN10|Pell Grant recipients - revised cohort",
    ADD COLUMN pell_recipients_revised_cohort MEDIUMINT COMMENT "PGLIN10|Pell Grant recipients - revised cohort",
  ADD COLUMN pell_recipients_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGLIN45|Pell Grant recipients - exclusions",
    ADD COLUMN pell_recipients_exclusions MEDIUMINT COMMENT "PGLIN45|Pell Grant recipients - exclusions",
  ADD COLUMN pell_recipients_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGLIN50|Pell Grant recipients - adjusted  cohort (revised minus exclusions)",
    ADD COLUMN pell_recipients_adjusted_cohort MEDIUMINT COMMENT "PGLIN50|Pell Grant recipients - adjusted  cohort (revised minus exclusions)",
  ADD COLUMN pell_recipients_completed_150pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "PGLIN11|Pell Grant  recipients - total number that completed an award  within 150% of norm time to completion",
    ADD COLUMN pell_recipients_completed_150pct_norm_time MEDIUMINT COMMENT "PGLIN11|Pell Grant  recipients - total number that completed an award  within 150% of norm time to completion",
  ADD COLUMN stafford_recipients_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSLIN10|Subsidized Stafford Loan recipients not receiving Pell Grants - revised cohort",
    ADD COLUMN stafford_recipients_revised_cohort MEDIUMINT COMMENT "SSLIN10|Subsidized Stafford Loan recipients not receiving Pell Grants - revised cohort",
  ADD COLUMN stafford_recipients_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSLIN45|Subsidized Stafford Loan recipients not receiving Pell Grants - exclusions",
    ADD COLUMN stafford_recipients_exclusions MEDIUMINT COMMENT "SSLIN45|Subsidized Stafford Loan recipients not receiving Pell Grants - exclusions",
  ADD COLUMN stafford_recipients_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSLIN50|Subsidized Stafford Loan recipients not receiving Pell Grants - adjusted cohort (revised minus exclusions)",
    ADD COLUMN stafford_recipients_adjusted_cohort MEDIUMINT COMMENT "SSLIN50|Subsidized Stafford Loan recipients not receiving Pell Grants - adjusted cohort (revised minus exclusions)",
  ADD COLUMN stafford_recipients_completed_150pct_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "SSLIN11|Subsidized Stafford Loan recipients not receiving Pell Grants - total number completed an award within 150% of norm time to completion",
    ADD COLUMN stafford_recipients_completed_150pct_norm_time MEDIUMINT COMMENT "SSLIN11|Subsidized Stafford Loan recipients not receiving Pell Grants - total number completed an award within 150% of norm time to completion",
  ADD COLUMN no_pell_or_stafford_revised_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRLIN10|Did not receive Pell grant or subsidized Stafford loan - revised cohort",
    ADD COLUMN no_pell_or_stafford_revised_cohort MEDIUMINT COMMENT "NRLIN10|Did not receive Pell grant or subsidized Stafford loan - revised cohort",
  ADD COLUMN no_pell_or_stafford_exclusions_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRLIN45|Did not receive Pell grant or subsidized Stafford loan - exclusions",
    ADD COLUMN no_pell_or_stafford_exclusions MEDIUMINT COMMENT "NRLIN45|Did not receive Pell grant or subsidized Stafford loan - exclusions",
  ADD COLUMN no_pell_or_stafford_adjusted_cohort_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRLIN50|Did not receive Pell grant or subsidized Stafford loan - adjusted cohort",
    ADD COLUMN no_pell_or_stafford_adjusted_cohort MEDIUMINT COMMENT "NRLIN50|Did not receive Pell grant or subsidized Stafford loan - adjusted cohort",
  ADD COLUMN did_not_receive_pell_or_stafford_norm_time_imp ENUM('A','B','C','D','G','H','J','K','L','N','P','R','Y','Z','') COMMENT "NRLIN11|Did not receive Pell grant or subsidized Stafford loan -  total number completed an award within 150% of norm time to completion",
    ADD COLUMN did_not_receive_pell_or_stafford_norm_time MEDIUMINT COMMENT "NRLIN11|Did not receive Pell grant or subsidized Stafford loan -  total number completed an award within 150% of norm time to completion";